### ISSUE TITLE
gRPC Error Codes final vs const

### ISSUE THREAD

**Issue by Sub6Resources** [grpc/grpc-dart#102]
The gRPC error codes are defined here:
https://github.com/grpc/grpc-dart/blob/c32a9e97be7b2935616a7ea46b31415f2b09de51/lib/src/shared/status.dart#L16-L118

Is there a reason why these error codes are marked as `final` rather than `const`? They seem pretty constant to me, and I was hoping to use the values in a `switch`statement.

**Comment by mit-mit** [comment]
Cc @sigurdm

**Comment by sigurdm** [comment]
No I don't see a good reason for that.
It could even have been an enum, but I guess that is too late to change now.

I made a PR for a fix.
