### ISSUE TITLE
repeated field generated code is not correct

### ISSUE THREAD

**Issue by Kleak** [grpc/grpc-dart#107]
##   Step to reproduce
int `demo_bug.proto` :
```proto
syntax = "proto3";

package repros_bug;

message TestMessage {
    repeated string test = 2;
}
```
then generate the code with :
`protoc --dart_out=grpc:lib/src/generated -Iprotos protos/demo_bug.proto`

then look at the generated code in `lib/src/generated/demo_bug.pb.dart`
here is the code 
```dart
class TestMessage extends GeneratedMessage {
  static final BuilderInfo _i = new BuilderInfo('TestMessage')
    ..pPS(2, 'test')
    ..hasRequiredFields = false
  ;

  TestMessage() : super();
  TestMessage.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  TestMessage.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);
  TestMessage clone() => new TestMessage()..mergeFromMessage(this);
  BuilderInfo get info_ => _i;
  static TestMessage create() => new TestMessage();
  static PbList<TestMessage> createRepeated() => new PbList<TestMessage>();
  static TestMessage getDefault() {
    if (_defaultInstance == null) _defaultInstance = new _ReadonlyTestMessage();
    return _defaultInstance;
  }
  static TestMessage _defaultInstance;
  static void $checkItem(TestMessage v) {
    if (v is! TestMessage) checkItemFailed(v, 'TestMessage');
  }

  List<String> get test => $_getList(0);
}
```
As we can see there is no setter for the test field.

**Comment by Kleak** [comment]
same bug as https://github.com/dart-lang/protobuf/issues/102

**Comment by kevmoo** [comment]
@mit-mit @sigurdm FYI

**Comment by sigurdm** [comment]
Also the java version has no generated setter: https://developers.google.com/protocol-buffers/docs/reference/java-generated#repeated-fields .
The java version has a setter for setting the value at a single index, but that can be done in dart by:
```
message.repeatedField[i]=value;
```

If you want to set a whole list, I would repeat the suggestion from dart-lang/protobuf#102 to do:
```
message.repeatedField..clear()..addAll(values);
```

**Comment by Kleak** [comment]
Do we have a Builder in dart like in Java ? https://stackoverflow.com/questions/29170183/how-to-set-repeated-fields-in-protobuf-before-building-the-message

**Comment by sigurdm** [comment]
No - in dart the message itself is mutable.

**Comment by Kleak** [comment]
I think, the setter can be really cool to simplofy the api and it will be
more idiomatic dart.
Especially if the field is mutable.

**Comment by sigurdm** [comment]
I think you are right.
Also the javascript api has it.
We have to make sure that the setter wraps the list in a PBList.
I don't think this a priority currently, but we are open for external contributions.

**Comment by Kleak** [comment]
the change need to be added in protoc_plugin right ?

if we generate this code is it ok ? 
```
List<Ingredient> get ingredients => $_getList(0);
set ingredients(List<Ingredient> v) { setField(0, PbList.from<Ingredient>(v)); }
bool hasIngredients() => $_has(0);
void clearIngredients() => clearField(1);
```

**Comment by sigurdm** [comment]
Yes the main change would be in dart_protoc_plugin.
I don't think we want the last two. There is always a list, but it can be empty.
I think you want to make a `$_setList<T>(List<T> v)` on GeneratedMessage - that would be a change in protobuf.

One problem with using PbList.from() is that it makes a copy - this seems unexpected to me.
You ideally want to wrap the original list somehow, so that changes to that are reflected.
But that would might ruin PbList's chances of validating changes. 

This might not be as easy as it first sounded. Perhaps generating a method like
```
void setAllIngredients(List<Ingredient> v) { getIngredients..clear()..addAll(v); }
```
would be better. But then I don't know how much we really win.

**Comment by huuang** [comment]
I need the setter method too.

**Comment by sigurdm** [comment]
What do you need it for?

**Comment by sigurdm** [comment]
After further considerations I will close this bug as a wontfix.
I think the functionality can easily be reached with ..clear()..addAll(), using the idiomatic dart List interface.

**Comment by divan** [comment]
I've stumbled upon this issue as well, and seeing no setter for repeatable field made me thing that I did something wrong, as grpc-dart looks more or less mature to have these kinds of omissions. Couple of hours of googling and reading docs led to nothing, so I started browsing issues and found this one.

I believe other newcomers to grpc-dart would expect consistency in the generated code and it will take roughly the same time to discover this issue. So, adding a setter for repeatable feild as for other fields would save people time I believe.

**Comment by wb14123** [comment]
@sigurdm by using ` ..clear()..addAll(),`, does that mean I should create the message first and then set it like this:

```
var message = Message()
  ..field1 = abc;
message.filed2..clear()..addAll(list);
```

This is much worse than just simply write 

```
var message = Message()
  ..flied1 = abc
  ..field2 = list;
```

Especially considering use this message in a request:

```
var message = Message()
  ..field1 = abc;
message.filed2..clear()..addAll(list);
apiRequest(message);
```

vs

```
apiRequest(Message()
  ..flied1 = abc
  ..field2 = list
)
```

**Comment by sigurdm** [comment]
Yeah I guess so - though If you have just created the message there is of course no reason to clear it first.

(don't look at me, I didn't design this)

I guess the advantage is that the list (which is mutable) will not be shared with other contexts.

Also dart protobuf has a proto-list wrapper that checks types, and can be set to frozen. That would not be possible if you just assigned the list.
