### ISSUE TITLE
Flutter - OS Error: Connection refused

### ISSUE THREAD

**Issue by medke** [grpc/grpc-dart#110]
I am using protobuf and gRPC to exchange information between a Flutter app and a python server (client in Flutter and the server in python). Server running on 0.0.0.0 and the client is using the IP address of the server machine.
```
import 'dart:async';
import 'User.pbgrpc.dart';
import 'User.pb.dart';
import 'package:grpc/grpc.dart';

Future<Null> main() async {
  final channel = new ClientChannel('IP_ADDRESS',
      port: 50051,
      options: const ChannelOptions(
          credentials: const ChannelCredentials.insecure()));
  final stub = new StorageClient(channel);

  Test input = new Test();
  input.id = 1;
  try {
    var response = await stub.getPerson(input);
    print('Greeter client received: ${response}');
  } catch (e) {
    print('Caught error: $e');
  }
  await channel.shutdown();
}
```

if I run this client using dart client.dart everything works fine and I get the expected response. But if I embed this method in a flutter app like:

```
@override
Widget build(BuildContext context) {

Future<Null> testRPC() async {
  final channel = new ClientChannel('IP_ADDRESS',
      port: 50051,
      options: const ChannelOptions(
          credentials: const ChannelCredentials.insecure()));
  final stub = new StorageClient(channel);

  Test input = new Test();
  input.id = 1;
  try {
    var response = await stub.getPerson(input);
    print('Greeter client received: ${response}');
  } catch (e) {
    print('Caught error: $e');
  }
  await channel.shutdown();
}

testRPC();
...etc
}
```
I get:

> I/flutter (18824): Caught error: gRPC Error (14, Error connecting: SocketException: OS Error: No route to host, errno = 111, address = localhost, port = 45638)

**Comment by Kleak** [comment]
Yes it's normal localhost on the device is not the same.
You machine has one and the device has also one.
Try to put the ip of your laptop in place of localhost.

**Comment by medke** [comment]
I did. Same results. Using dart command works but not Flutter (same error).

**Comment by Kleak** [comment]
And you should also change the python server

**Comment by medke** [comment]
@Kleak The python server is running on 0.0.0.0

**Comment by medke** [comment]
@Kleak I just tested it with an emulator and it is working. The problem is happening only with a real device.

**Comment by medke** [comment]
It was a firewall problem in the server. Running `systemctl enable firewalld` solved it.

**Comment by Kleak** [comment]
Great ! Could you close the issue if it's solved ?

**Comment by medke** [comment]
@Kleak yes.

**Comment by JamesHolland181** [comment]
Hello, I've encountered this issue when implementing a dart client in flutter app.

Running from terminal (with correct IP addr) yields no errors but when added to the application, I receive an OS error. Below is my code for the Python server, Dart client bit from flutter application, and any red text I receive from emulator/event log.

**Locally Hosted Python Server**
`import socket


# get the hostname
host = socket.gethostname()
port = 8888  # initiate port no above 1024
print('Server On\n')
print('Host: '+host)
server_socket = socket.socket()  # get instance
# look closely. The bind() function takes tuple as argument
server_socket.bind((host, port))  # bind host address and port together

# configure how many client the server can listen simultaneously
server_socket.listen(2)
conn, address = server_socket.accept()  # accept new connection
print("Connection from: " + str(address))
while True:
    # receive data stream. it won't accept data packet greater than 1024 bytes
    data = conn.recv(1024).decode()
    
    
    
    if not data:
        # if data is not received break
        break
    
    print("from connected user: " + str(data))
    #data = input(' -> ')
    #conn.send(data.encode())  # send data to the client

conn.close()  # close the connection`

**Application main.dart file**
`import 'package:flutter/material.dart';
import 'app.dart';
import 'dart:io';
import 'dart:async';

String _request = "Hello World";
Socket socket;

void main(){
  Socket.connect("10.0.3.2", 8888)
      .then((Socket sock) {
    socket = sock;
    socket.listen(dataHandler,
        onError: errorHandler,
        onDone: doneHandler,
        cancelOnError: false);
  }).then((_) {
    print(_request); // so that your code runs AFTER the TCP/IP connection
    socket.write('$_request\r\n');

    // once socket is connected run the application
    runApp(App()); // calls 'runApp()' with the parameter 'App()', the class of our application in app.dart

  })
      .catchError((Object e) {
    print("Unable to connect: $e");
    exit(1);
  });
}

void dataHandler(data){
  print(new String.fromCharCodes(data).trim());
}

void errorHandler(error, StackTrace trace){
  print(error);
}`

**Event Log**
`6:11 PM	Emulator: emulator: WARNING: EmulatorService.cpp:448: Cannot find certfile: /home/james/.android/emulator-grpc.cer security will be disabled.

6:11 PM	Emulator: E0221 18:11:55.773497783   13298 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1582326715.773458393","description":"SO_REUSEPORT unavailable on compiling system","file":"/mnt/tmpfs/src/android/emu-master-dev/external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}

6:11 PM	Emulator: Started GRPC server at 127.0.0.1:8554`

Possibly relevant details: OS is Ubuntu (firewall disabled), IDE is Android Studio, using Android emulator.

Thank you in advanced!

**Comment by JamesHolland181** [comment]
Hello, I've encountered this issue when implementing a dart client in flutter app.

Running from terminal (with correct IP addr) yields no errors but when added to the application, I receive an OS error. Below is my code for the Python server, Dart client bit from flutter application, and any red text I receive from emulator/event log.

**Locally Hosted Python Server**

```
import socket
get the hostname

host = socket.gethostname()
port = 8888 # initiate port no above 1024
print('Server On\n')
print('Host: '+host)
server_socket = socket.socket() 

server_socket.bind((host, port)) 

server_socket.listen(2)
conn, address = server_socket.accept() 
print("Connection from: " + str(address))
while True:
data = conn.recv(1024).decode()

if not data:
    # if data is not received break
    break

print("from connected user: " + str(data))
#data = input(' -> ')

conn.close() 
```

**Application main.dart file**

```
import 'package:flutter/material.dart';
import 'app.dart';
import 'dart:io';
import 'dart:async';

String _request = "Hello World";
Socket socket;

void main(){
Socket.connect("10.0.3.2", 8888)
.then((Socket sock) {
socket = sock;
socket.listen(dataHandler,
onError: errorHandler,
onDone: doneHandler,
cancelOnError: false);
}).then((_) {
print(_request); // so that your code runs AFTER the TCP/IP connection
socket.write('$_request\r\n');

// once socket is connected run the application
runApp(App()); // calls 'runApp()' with the parameter 'App()', the class of our application in app.dart

})
.catchError((Object e) {
print("Unable to connect: $e");
exit(1);
});
}

void dataHandler(data){
print(new String.fromCharCodes(data).trim());
}

void errorHandler(error, StackTrace trace){
print(error);
}
```

**Event Log**
```

6:11 PM Emulator: emulator: WARNING: EmulatorService.cpp:448: Cannot find certfile: /home/james/.android/emulator-grpc.cer security will be disabled.

6:11 PM Emulator: E0221 18:11:55.773497783 13298 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1582326715.773458393","description":"SO_REUSEPORT unavailable on compiling system","file":"/mnt/tmpfs/src/android/emu-master-dev/external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}

6:11 PM Emulator: Started GRPC server at 127.0.0.1:8554
```

Possibly relevant details: OS is Ubuntu (firewall disabled), IDE is Android Studio, using Android emulator.

Thank you in advanced!

**Comment by flutter-painter** [comment]
keep local host on the server side
only update the ip in the flutter app to match device ip as said Kleak
