### ISSUE TITLE
Dart Flutter

### ISSUE THREAD

**Issue by uheredia** [grpc/grpc-dart#113]
Bidireccional stream

0.6.1

Hello, sorry for my english, someone know how to make a duplex connection over exists channel for flutter client-side. This is my code.

  ClientChannel _channel;
  ClientConnection _connection;
  ClientMethod<Q, R> _method;
  ClientCall<Q, R> _call;

 _channel = new ClientChannel('192.168.0.9',
        port: 5001,
        options: const ChannelOptions(
            credentials: const ChannelCredentials.insecure()));

    _method = new ClientMethod<TransportPayloadStringBondEN, ResultDtoBondEN>(
        '/S/m',
        (TransportPayloadStringBondEN value) => value.writeToBuffer(),
        (List<int> value) => new ResultDtoBondEN.fromBuffer(value));

ResponseStream<R> response(Stream<Q> request, {CallOptions options}) {
    _call = new ClientCall(_method, request, new CallOptions());
    _connection.dispatchCall(_call);
    return new ResponseStream(_call);
  }
startSendAndReciveMessages() async {
    if (_connection == null) {
      _connection = await _channel.getConnection();
    }
 
    var i = new Q();
    i.payload = 'START DUPLEX CONNECTION';

    Stream<Q> request() async* {
      for (final mess in [i]) {
        // Short delay to simulate some other interaction.
        await new Future.delayed(new Duration(milliseconds: 10));
        print('Sending message ${mess.payload}');
        yield note;
      }
    }

    final call = response(request());
    await for (var res in call) {
      print('Got message ${res.dto.payload}');
    }
  }

This code create a channel and send one message from the client to the server, the server response one time, and later the call is closed and when I try to send one message from the server over the channel, the server trow an exception "Response stream has already been completed."

"   at Grpc.Core.Internal.AsyncCallServer`2.CheckSendAllowedOrEarlyResult()\r\n   at Grpc.Core.Internal.AsyncCallBase`2.SendMessageInternalAsync(TWrite msg, WriteFlags writeFlags)\r\n   at Grpc.Core.Internal.ServerResponseStream`2.WriteAsync(TResponse message)\r\n   at Test.Communication.gRPC.Server.WinForm.ServerForm.<>c__DisplayClass16_0.<<SendData>b__0>d.MoveNext() "

The server is c# .NET core.
I try the same with a client winForm, and the channel is keep open, and I can send messages from the server to the client and from the client to server, over the connected channel.

Again, sorry for my very basic english.

Tnks

**Comment by recoilme** [comment]
Hello!
I have the same issue, completely misunderstand how to send more than "one-time " messages in dart

For example, in golang, I may just send a message in the channel and that's all. It's just working.
In Dart i try to implement something similar with no luck(

```
Stream<Channel> out(String url) async* {
    if (url != "") {
      var c = new Channel();
      c.url = url;
      yield c;
    }
}

var client = SrvClient(GrpcClientSingleton().client);
var stream =client.channels(out("11"));// here it work- but if i call out from other place it didn't work
stream.forEach((a) {
      print(a);
    });
```

**Comment by recoilme** [comment]
i resolved this with StreamController (i'm new in dart, it may be wrong)
```
// rpc Channels(stream Channel) returns (stream Channel) {} // proto

final StreamController<Channel> cmdController = new StreamController();
final cmdStream = cmdController.stream;
...
    var client = SrvClient(GrpcClientSingleton().client);
  
    var stream =client.channels(cmdStream);
    stream.forEach((a) {
      //read from stream
      print(a);
    });
...
cmdController.add(c);//write to stream
```
