### ISSUE TITLE
Feature Request: Client Interceptors

### ISSUE THREAD

**Issue by nevi-me** [grpc/grpc-dart#121]
It looks like the implemented interceptors are only server interceptors. Is it possible to create client interceptors?

I need to intercept calls that I make from a Flutter application and add authentication metadata

Using v 0.6.4

## Repro steps

None

## Details

I don't think this would need a gRFC, as I presume a general one exists since Java has client interceptors
.

**Comment by sigurdm** [comment]
I am not against client interceptors, but it is not on the current list of priorities.

We are open for contributions...

**Comment by TinoGuo** [comment]
I found a solution but not verify.

In j
```
class ExampleClientChannel extends ClientChannel {
  ExampleClientChannel(String host, {int port, ChannelOptions options})
      : super(host, port: port, options: options);

  ClientConnection _connection;

  bool _isShutdown = false;

  /// Shuts down this channel.
  ///
  /// No further RPCs can be made on this channel. RPCs already in progress will
  /// be allowed to complete.
  Future<Null> shutdown() {
    if (_isShutdown) return new Future.value();
    _isShutdown = true;
    return _connection.shutdown();
  }

  /// Terminates this channel.
  ///
  /// RPCs already in progress will be terminated. No further RPCs can be made
  /// on this channel.
  Future<Null> terminate() {
    _isShutdown = true;
    return _connection.terminate();
  }

  /// Returns a connection to this [Channel]'s RPC endpoint.
  ///
  /// The connection may be shared between multiple RPCs.
  Future<ClientConnection> getConnection() async {
    if (_isShutdown) throw new GrpcError.unavailable('Channel shutting down.');
    return _connection ??= new ArkClientCall(host, port, options);
  }

  /// Initiates a new RPC on this connection.
  ClientCall<Q, R> createCall<Q, R>(
      ClientMethod<Q, R> method, Stream<Q> requests, CallOptions options) {
    final call = new ClientCall(method, requests, options);
    getConnection().then((connection) {
      if (call.isCancelled) return;
      connection.dispatchCall(call);
    }, onError: call.onConnectionError);
    return call;
  }
}
```

**Comment by TinoGuo** [comment]
I found a solution but not verify.

Inherit from ClinetChannel, and just copy the ClientChannel source code.
```
class ExampleClientChannel extends ClientChannel {
  ExampleClientChannel(String host, {int port, ChannelOptions options})
      : super(host, port: port, options: options);

  ClientConnection _connection;

  bool _isShutdown = false;

  /// Shuts down this channel.
  ///
  /// No further RPCs can be made on this channel. RPCs already in progress will
  /// be allowed to complete.
  Future<Null> shutdown() {
    if (_isShutdown) return new Future.value();
    _isShutdown = true;
    return _connection.shutdown();
  }

  /// Terminates this channel.
  ///
  /// RPCs already in progress will be terminated. No further RPCs can be made
  /// on this channel.
  Future<Null> terminate() {
    _isShutdown = true;
    return _connection.terminate();
  }

  /// Returns a connection to this [Channel]'s RPC endpoint.
  ///
  /// The connection may be shared between multiple RPCs.
  Future<ClientConnection> getConnection() async {
    if (_isShutdown) throw new GrpcError.unavailable('Channel shutting down.');
    return _connection ??= new ArkClientCall(host, port, options);
  }

  /// Initiates a new RPC on this connection.
  ClientCall<Q, R> createCall<Q, R>(
      ClientMethod<Q, R> method, Stream<Q> requests, CallOptions options) {
    final call = new ClientCall(method, requests, options);
    getConnection().then((connection) {
      if (call.isCancelled) return;
      connection.dispatchCall(call);
    }, onError: call.onConnectionError);
    return call;
  }
}
```

Declare a class named ExampleClientConnection inherit from ClientConnection, override the function makeRequest.

```
class ExampleClientConnection extends ClientConnection {
  ExampleClientConnection(String host, int port, ChannelOptions options)
      : super(host, port, options);

  @override
  ClientTransportStream makeRequest(
      String path, Duration timeout, Map<String, String> metadata) {
    //insert the custom header here.
    return super.makeRequest(path, timeout, metadata);
  }
}
```

BTW, it doesn't support async in this way.

**Comment by facundomedica** [comment]
This would be nice to have, I could do it if pointed in the right direction. I've read some of the java implementation but wouldn't know where to start here. Let me know if you can give me a hand on this @sigurdm

**Comment by MartinNiederl** [comment]
Any news on that?
I would need a way to execute code after each request bevor it returns.

Kind of the way it's done here with the `UnaryClientInterceptor`:
https://github.com/grpc/grpc-go/tree/master/examples/features/interceptor

I don't have time to study the whole code so if you don't intend to implement such a function, please tell me where to best implement such functionality in your package.

**Comment by dxGuan** [comment]
@sigurdm 
What is a good starting point of implementing this feature?
I am trying to contribute and hope to get some suggestions from you.

**Comment by jtmcdole** [comment]
I'd like to have something similar to this feature; the ability to generally intercept responses (more specifically, generally handle response errors). There are times when a generic GprcError.unauthenticated could be handled in one location (force the user to sign in again) vs having every try/catch of a service care for this.

**Comment by fdcgr** [comment]
I would also like to add here the request for this feature. Client interceptors are an excellent way of providing behaviour that is the same for all endpoints..

**Comment by mit-mit** [comment]
For anyone interested in this, please try out the patch in https://github.com/grpc/grpc-dart/pull/261 and let us know if that resolve the issue
