### ISSUE TITLE
flutter_appgrpc depends on both grpc ^0.6.5 and flutter_test any from sdk, version solving failed

### ISSUE THREAD

**Issue by luojianming2010** [grpc/grpc-dart#125]
<short description>

<version of the grpc-dart packages used; see your `pubspec.lock` file>

## Repro steps

1. step1
1. step2
1. step3

Expected result: <describe what should have happened>

Actual result: <describe what actually happened>

## Details

<Include any other relevant details, logs, etc.>

**Comment by luojianming2010** [comment]
/Users/mac/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in flutter_appgrpc...            
Because every version of flutter_test from sdk depends on http 0.12.0 and grpc 0.6.5 depends on http ^0.11.3+16, flutter_test from sdk is incompatible with grpc 0.6.5.
And because no versions of grpc match >0.6.5 <0.7.0, flutter_test from sdk is incompatible with grpc ^0.6.5.
So, because flutter_appgrpc depends on both grpc ^0.6.5 and flutter_test any from sdk, version solving failed.

pub get failed (1)
Process finished with exit code 1

**Comment by fuzzybinary** [comment]
This appears to be be an incompatibility with this using package ^0.11.3, but this can't be fixed by simply updating the dependency. googleapis_auth also has a dependency on http 0.11.x.

What version of flutter are you using? Did they upgrade to http 0.12 recently?

**Comment by medke** [comment]
I am getting the same error. I tried it on flutter 0.10 and 0.9.6.
