### ISSUE TITLE
TLS Client certificate support?

### ISSUE THREAD

**Issue by Ragnaroek** [grpc/grpc-dart#134]
Is there client certificate support in grpc-dart?

The guide here only describes server certificates:
https://grpc.io/docs/guides/auth.html#dart

From the code I can not see that this is supported.

**Comment by zoechi** [comment]
For Flutter, web, server, ...?

**Comment by Ragnaroek** [comment]
That would be for the Flutter context

**Comment by Ragnaroek** [comment]
any hints on that?

**Comment by Ragnaroek** [comment]
anything?
I can make a PR if you push me in the right direction...

**Comment by zhouzr** [comment]
Will this feature be supported?

I try to move my app from rn to flutter, but be defeated at this.

**Comment by sigurdm** [comment]
cc: @sortie . Do we have support for client TLS certificates in dart:io?

**Comment by michaellee8** [comment]
@sigurdm @sortie It will be good if we can get mutual TLS.

**Comment by mpwalkerdine** [comment]
You can extend `ChannelCredentials` to return a custom `SecurityContext`, for example:

```dart
class ClientCertificateChannelCredentials extends ChannelCredentials {
  final List<int> _cert;
  final List<int> _key;
  final String _pass;

  const ClientCertificateChannelCredentials(
    this._cert,
    this._key,
    this._pass,
  ) : super.secure();

  @override
  SecurityContext get securityContext {
    return SecurityContext(withTrustedRoots: true)
      ..useCertificateChainBytes(_cert)
      ..usePrivateKeyBytes(_key, password: _pass)
      ..setAlpnProtocols(supportedAlpnProtocols, false);
  }
}
```

Then when creating the channel:

```dart
final channel = ClientChannel(host,
        port: port,
        options: ChannelOptions(
          credentials: ClientCertificateChannelCredentials(cert, key, pass),
        ));
```

**Comment by mraleph** [comment]
The question is answered by @mpwalkerdine.

**Comment by pranavpsawant** [comment]
@mpwalkerdine  Do we have this support for flutter web. The securityContext comes from dart io which doesnt seem to be supported in web ?
