### ISSUE TITLE
Shelf middleware equivalent

### ISSUE THREAD

**Issue by Kleak** [grpc/grpc-dart#140]
Is there a shelf middleware equivalent ?
I would like to know how much time is passed inside my endpoint.
And maybe also get and release db connection from a pool inside it.

**Comment by Kleak** [comment]
they are called before the endpoint only it seems

**Comment by sigurdm** [comment]
Could you wrap the endpoint itself in a time-taking endpoint?

**Comment by Kleak** [comment]
what do you mean ?
the goal is to not have to modify the endpoint and add a Middleware to get this kind of information

**Comment by sigurdm** [comment]
Good point. You are right that would require using something ugly like `noSuchMethod` which is usually less nice.

I think we have to change the interceptor-concept to cover your mentioned use-cases.
What if we change the interceptor type to be along the lines of
```dart
typedef Interceptor = Future<void> Function(ServiceCall call, ServiceMethod method, Future<void> Function(ServiceCall call, ServiceMethod method) next);
```
Where next is the method to call to continue to the next interceptor (or the handler) if there are no more interceptors.

Then a time-taking interceptor would look like:

```dart
Future<void> measureInterceptor(ServiceCall call, ServiceMethod method, Future<void> Function(ServiceCall call, ServiceMethod method) next) async {
   final Stopwatch stopwatch = Stopwatch()..start();
   await next(call, method);
   stopwatch.stop();
   print("method: ${method.name}, took ${stopwatch.elapsedMilliseconds} ms");
}
```

**Comment by Kleak** [comment]
Yes that seems good :)
One question do next will push automatically the value returned by the handler ?
in your example next return a Future<void>

**Comment by sigurdm** [comment]
Good question. It would probably be better to pass the return value along...

```
typedef Interceptor = Future<dynamic> Function(ServiceCall call, ServiceMethod method, Future<dynamic> Function(ServiceCall call, ServiceMethod method) next);
```

```dart
Future<dynamic> measureInterceptor(ServiceCall call, ServiceMethod method, Future<void> Function(ServiceCall call, ServiceMethod method) next) async {
   final Stopwatch stopwatch = Stopwatch()..start();
   final result = await next(call, method);
   stopwatch.stop();
   print("method: ${method.name}, took ${stopwatch.elapsedMilliseconds} ms");
   return result;
}
```
Is this interface too complicated to use / too easy to use wrongly?

How would your example with a database connection from a pool look in this world?

**Comment by Kleak** [comment]
I think it's less complicated to have the return value else it's a bit of magic :)
for the database example we need something like :
```dart
  ReturnValue myHandler() {
    final db = Zone.current['db'];
    return ReturnValue();
  }

  return runZoned(() {
    final result = myHandler();
    return result;
  }, zoneValues: {
    'db': gettingDatabaseFromAPoolOrSomewhere(),
  });
```
or something else.

**Comment by sigurdm** [comment]
How would this work with streaming requests?

**Comment by Kleak** [comment]
As reference GO provide 2 types of interceptor:
one for Unary RPC
one for Streamed RPC.

Maybe we should also distinct the two type to keep them easy to use and implement.

**Comment by mraleph** [comment]
There are different ways to approach this (e.g. redesign interceptor API or change `ServiceCall` APIs to expose lifecycle events). However we don't have immediate plans to address that - we welcome PRs though.

**Comment by Pingear** [comment]
@Kleak Did you find a way to add a database connection to the service, or did you solve the problem in a different way?

@mraleph As far as I understand from your answers in other threads, there are no development plans for this project, is this really so? I am considering grpc for our project and would like to understand the perspectives of the grpc-dart project, please tell me :)
