### ISSUE TITLE
No Client created with protoc_plugin

### ISSUE THREAD

**Issue by herry1234** [grpc/grpc-dart#141]
<short description>
No Client classed has been generated. 
<version of the grpc-dart packages used;">
 "0.6.8"

## Repro steps

1. build dart lib
on Makefile,
%.grpc.pb.cc: %.proto
	$(PROTOC) -I $(PROTOS_PATH) **--dart_out**=. --grpc_out=. --plugin=protoc-gen-grpc=$(GRPC_CPP_PLUGIN_PATH) $<

1. copy over all the dart files to app folder.

Expected result: <describe what should have happened>
```
As shown in the samples, one client class would be generated. 
class GreeterClient extends Client {
...
  ResponseFuture<HelloReply> sayHello(HelloRequest request,
      {CallOptions options}) {
    final call = $createCall(_$sayHello, new Stream.fromIterable([request]),
        options: options);
    return new ResponseFuture(call);
  }
}
```
Actual result: <describe what actually happened>
there is one xxxApi class created including RpcClient.   I have no idea how to incorporate it into my gRPC client app. 
```
class PkApi {
  $pb.RpcClient _client;
  PkApi(this._client);

  $async.Future<CamStatus> getCamStatus($pb.ClientContext ctx, Field request) {
    var emptyResponse = new MyStatus();
    return _client.invoke<MyStatus>(ctx, 'Pk', 'GetMyStatus', request, emptyResponse);
  }
}
```
## Details

<Include any other relevant details, logs, etc.>

**Comment by sigurdm** [comment]
I believe you are missing the grpc option to the dart_out parameter

```
protoc --dart_out=grpc:lib/src/generated -Iprotos protos/helloworld.proto
```

**Comment by herry1234** [comment]
oh, it's my mistake. i over looked this option. 
thanks @sigurdm
