### ISSUE TITLE
Permit setting user agent

### ISSUE THREAD

**Issue by rajpara** [grpc/grpc-dart#153]
It would be useful to be able to control the User-Agent used by the gRPC package. This can either be set on the client channel or whether the rpc is made maybe even.

Other grpc client libraries (like the Objective-C one) provided a way to add a prefix to the user agent and our team utilizes this on the server side to figure out what clients a rpc is coming from.

In https://github.com/grpc/grpc-dart/blob/master/lib/src/client/connection.dart it seems as if though user-agent is hardcoded and in https://github.com/grpc/grpc-dart/blob/master/lib/src/client/call.dart the metadata is sanitized so the a new user-agent value can't be added (which is why we can't set it in the metadata).

**Comment by listepo** [comment]
@rajpara fix https://github.com/grpc/grpc-dart/pull/155

**Comment by listepo** [comment]
@sigurdm I think we can close this issue
