### ISSUE TITLE
Extremly slow server-side streams when using SSL termination

### ISSUE THREAD

**Issue by Entsch** [grpc/grpc-dart#154]
I'm experiencing a weird issue with gRPC in combination with nginx as a reverse proxy for ssl termination. As the code basis is rather huge, I'm just explaining the scenario. Maybe someone has any thoughts on what might cause the issue.

We have a java based server running on a remote host. The server is proxied by a nginx for ssl termination. The server provides many grpc methods, some of them supporting server-side streams.

The issue is that all items are transmitted extremely slow by means of the server-side streams. Yet, this issue only occurs when we use the proxy. If we use a ssh tunnel in order to talk to the server directly, it's blazingly fast.

Moreover, this issue only affects grpc/dart. We also have a client implemented in grpc/swift which does not suffer from this problem. Hence, I don't think that it's an issue with the server and/or the proxy.

I'm rather clueless. Does anyone have any advice on this?

**Comment by as3445** [comment]
were you able to find solutions to this issue?
