### ISSUE TITLE
Grpc Quickstart for Dart, does not work

### ISSUE THREAD

**Issue by robinbakkerus** [grpc/grpc-dart#158]
I exactly followed this quick start: https://grpc.io/docs/quickstart/dart.html. 
pub run bin/server.dart run fine: 
```
mint:helloworld>pub run bin/server.dart 
Server listening on port 50051...
```
But running the client gives errors:
**mint:helloworld>pub run bin/client.dart** 

> Caught error: gRPC Error (14, Error making call: NoSuchMethodError: The method 'makeRequest' was called on null.
> Receiver: null
> Tried calling: makeRequest(Instance(length:8) of '_GrowableList'))
> Unhandled exception:
> NoSuchMethodError: The method 'finish' was called on null.
> Receiver: null
> Tried calling: finish()
> #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
> #1      Http2Transport.finish (package:grpc/src/client/transport/http2_transport.dart:145:31)
> <asynchronous suspension>
> #2      ClientConnection.shutdown (package:grpc/src/client/connection.dart:128:23)
> <asynchronous suspension>
> #3      ClientChannel.shutdown (package:grpc/src/client/channel.dart:55:48)
> <asynchronous suspension>
> #4      main (file:///home/mint/Projects/dart/grpc-dart/example/helloworld/bin/client.dart:39:17)
> <asynchronous suspension>
> #5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
> #6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Flutter / Dart version**

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [!] Android Studio (version 3.3)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] Connected device (1 available)
> ! Doctor found issues in 1 category.

**OS**

>  System:    Host: mint-VirtualBox Kernel: 4.15.0-20-generic x86_64 bits: 64 Desktop: Cinnamon 4.0.9 
>             Distro: Linux Mint 19.1 Tessa 
>  

**Steps to reproduce**
Simply follow the steps described in quickstart.

**Comment by supermuka** [comment]
I'm getting this error with _last version on github._ (https://github.com/grpc/grpc-dart) too. I think that folks are with work in progress in this repository yet. 

However, for me the version 1.0.1 published on Pub (https://pub.dartlang.org/packages/grpc) is working to the Quickstart for Dart example.

**Comment by supermuka** [comment]
On (https://github.com/grpc/grpc-dart) the last changes were reverted on March 18th.  So, that code should be working now, too.
