### ISSUE TITLE
Unable to use authority in an insecure call

### ISSUE THREAD

**Issue by JCzz** [grpc/grpc-dart#170]
Unable to use authority in an insecure call

For secure I can use, but not for insecure - any suggestions?
https://github.com/grpc/grpc-dart/blob/master/lib/src/client/options.dart
```
    final channel = new ClientChannel('x.x.x.x',
        port: 80,
        options: const ChannelOptions(
            credentials: const ChannelCredentials.secure(authority: "grpc-test.default.example.com"))
            );
```

**Comment by mit-mit** [comment]
Bug appears to be stale, we now have: https://pub.dev/documentation/grpc/latest/grpc/ChannelCredentials/ChannelCredentials.insecure.html

**Comment by kevinxxq** [comment]
Is there anybody let me know what is "authority"? CommonName/SubjectAltName? I am unclear and can't figure out the relationship.

Thank you.
