### ISSUE TITLE
Add git tag corresponding to pub versions

### ISSUE THREAD

**Issue by a14n** [grpc/grpc-dart#173]
https://pub.dev/packages/grpc#-versions-tab- lists 21 versions but there are no git tags for those versions.

**Comment by sigurdm** [comment]
I never used these tags myself, so I'm a bit hesitant to start adding them.
I think for them to be really useful there should be a `pub publish --tag xxx` option that would make a clean checkout and publish only the files from the tagged commit - or some other way of validating the correspondence.
@jonasfj what do you feel about version tags?

**Comment by mraleph** [comment]
We are going to tag all new releases going forward.
