### ISSUE TITLE
grpc-dart with flutter_web 

### ISSUE THREAD

**Issue by huy-lv** [grpc/grpc-dart#175]
I have cloned the flutter web example from https://github.com/flutter/flutter_web and define grpc 1.0.2 in pubspec, but when i run project, i received this warning
```
[WARNING] build_web_compilers:entrypoint on web/houdini_main.dart: Skipping compiling flutter_web.examples.gallery|web/houdini_main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:
```
and then the web can not start.
So does grpc-dart can run with flutter_web? :D

**Comment by sigurdm** [comment]
You should 
```
import 'package:grpc/grpc-web.dart';
```
instead of
```
import 'package:grpc/grpc.dart';
```

Hope it helps

**Comment by sh0umik** [comment]
@sigurdm `import 'package:grpc/grpc-web.dart';` doesn't seems to work. I am getting an import error . According to grpc 2.0.0 , doc they said they included web support but i am still getting the warning messages and no output in on webdev serve!

**Comment by supermuka** [comment]
Try `import 'package:grpc/grpc_web.dart';`

`grpc_web.dart` with _underline_ instead `grpc-web.dart`.

**Comment by sigurdm** [comment]
Thanks! yes it is an underline. I fixed the description.

**Comment by sigurdm** [comment]
@huy-lv you should also use grpc-2.0.0+1

**Comment by sh0umik** [comment]
The error message is gone but not able to connect to my grpc server which is build with golang!
Any idea on how to debug this ? 

Here is my connection parameter.
```
searchServiceClient = SearchServiceClient(
          GrpcWebClientChannel.xhr(Uri.parse("http://localhost:8011")));
```

**Comment by sigurdm** [comment]
Did you set up envoy or other grpc-web to grpc proxying?

**Comment by sh0umik** [comment]
I was using grpcweb wrapper package to proxy grpc web request. I got it working after adding few `cors` parameter to request handler. Thank you Guys.

**Comment by sigurdm** [comment]
Great!
