### ISSUE TITLE
grpc-dart 2.0.0 (web context): dependencies not supported error 

### ISSUE THREAD

**Issue by supermuka** [grpc/grpc-dart#195]
This error is occurring on _web side_ after update to last `grpc` version and when it is ran `pub run build_runner serve web:8083`:

```
...
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms
[WARNING] build_web_compilers:entrypoint on web/main.dart:
Skipping compiling auge_web|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

grpc|lib/src/client/transport/http2_credentials.dart
grpc|lib/src/shared/security.dart
googleapis_auth|lib/src/oauth2_flows/auth_code.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
...
```
_**_Versions used_**_:
grpc-dart package: ^2.0.0
build_runner package: ^1.5.2
build_web_compilers package: ^2.1.1
webdev package: 2.1.0

Dart sdk: 2.3.2
SO: Windows 10

**Steps**

1. ran `pub get update`
2. ran `pub global activate webdev`
3. ran `pub run build_runner serve web:8083`
4. the error occurs

_Note_: before this project was working with `grpc-web` branch from a few days ago.

**Comment by sigurdm** [comment]
I don't seem to be able to reproduce.

Are you able to give more details (pubspec.lock, imports from main etc) or perhaps create a small reproduction?

**Comment by supermuka** [comment]
I created [this](https://github.com/supermuka/angular_grpc_web) repository just to reproduce this error. It just pull it. 

It is based on IntelliJ template _AngularDart Web App_ provided when it is created a new Dart Project.

I just added `grpc 2.0.0` package and included code below on `todo_list_service.dart` to reference the package in compile time:

```
...
import 'package:grpc/grpc_web.dart';
...
  final String _uriChannel = 'http://localhost:8080';

  //GRPC NOT USED IN THIS APP. JUST PUB HERE FOR COMPILER PURPOSE
  GrpcWebClientChannel _channel;

  TodoListService(this._channel) {
    _channel = GrpcWebClientChannel.xhr(Uri.parse(_uriChannel));
  }

  GrpcWebClientChannel get channel {

    return _channel;
  }
...
```

`pubspec.lock` is in the repository too.

**Comment by sigurdm** [comment]
Thanks! I am now able to reproduce!
Will investigate...

**Comment by sigurdm** [comment]
Hmm - it seems the newer build_runner is more strict with not having dart:io in the transitive import chain. I fixed all of them in https://github.com/sigurdm/grpc-dart/tree/Fix_imports (mostly stray unused imports), but it seems build runner still finds one.
I hope we find a solution quickly.

**Comment by sigurdm** [comment]
Should be fixed in v. 2.0.0+1

**Comment by supermuka** [comment]
Great, it's working now!
