### ISSUE TITLE
Do allow usages of Connection after it has started finishing

### ISSUE THREAD

**Issue by jonasfj** [grpc/grpc-dart#202]
I'm not 100% sure this is what is happening. But what we experienced is that a connection being finished (not by us, but broken socket or go-away-frame), caused many sequential operations to fail. We suspect that there was only a single connection being finished, but that this caused sequential calls to fail, though it could also be that we had hundreds of connections failures in a row (unlikely).

We were doing the calls sequentially with async/await, which means our requests were all happening on the micro-task-queue, which can starve the event-queue.

However, it seems very likely that `Connection._finishing` in `http2`:
```dart
  void _finishing({bool active: true, String message}) {
    // If this connection is already dead, we return.
    if (_state.isTerminated) return;

    // If this connection is already finishing, we make sure to store the
    // passive bit, since this information is used by [StreamHandler].
    //
    // Vice versa should not matter: If we started passively finishing, an
    // active finish should be a NOP.
    if (_state.isFinishing) {
      if (!active) _state.finishingState |= ConnectionState.FinishingPassive;
      return;
    }

    assert(_state.isInitialized || _state.isOperational);

    // If we are actively finishing this connection, we'll send a
    // GoawayFrame otherwise we'll just propagate the message.
    if (active) {
      _state.state = ConnectionState.Finishing;
      _state.finishingState |= ConnectionState.FinishingActive;

      _outgoingQueue.enqueueMessage(new GoawayMessage(
          _streams.highestPeerInitiatedStream,
          ErrorCode.NO_ERROR,
          message != null ? utf8.encode(message) : []));
    } else {
      _state.state = ConnectionState.Finishing;
      _state.finishingState |= ConnectionState.FinishingPassive;
    }

    _streams.startClosing();
  }
```
Occurs on an event before `socket.done.then(_handleSocketClosed);`.

Hence, we could imagine a time-line as follows:
 1. Event: `go-away-frame` arrives, `http2.Connection` enters state finishing.
    * Micro-task: active call is resolved with an error.
    * Micro-task: next active call is initiated,
    * Micro-task: next active call is resolved with an error.
    * Micro-task: next next active call is initiated,
    * Micro-task: next next active call is resolved with an error.
    * ....
 2. Event: `socket.done.then(` occurs and calls from now on will use a new `http2.Connection`.

I imagine this could happen. Maybe my time-line is missing something :)

**Comment by sigurdm** [comment]
I believe this is fixed in 2.1.1
