### ISSUE TITLE
Support 'details' from the RPC Error Model

### ISSUE THREAD

**Issue by kriswuollett** [grpc/grpc-dart#209]
It currently isn't possible to fully take advantage of and interact with (and produce) gRPC services that make use of the full [RPC Error Model](https://cloud.google.com/apis/design/errors#error_model) because the `GrpcError` class is missing the [`details`](https://github.com/googleapis/googleapis/blob/f46206aff84f4b2cde590f1e0791112214f07080/google/rpc/status.proto#L93) field as defined in `google/rpc/status.proto`.

One example use case out of many is being able to access [`retry_delay`](https://github.com/googleapis/googleapis/blob/f46206aff84f4b2cde590f1e0791112214f07080/google/rpc/error_details.proto#L42) for behaving nicely with a service.

This would help developers avoid baking in custom error details into their custom response message definitions themselves. My current workaround for Dart (and the other languages that don't support this yet) is to encode [`google.rpc.Status`](https://github.com/googleapis/googleapis/blob/f46206aff84f4b2cde590f1e0791112214f07080/google/rpc/status.proto#L80) into (a JSON String field in) the [`message`](https://github.com/grpc/grpc-dart/blob/561f8fe7164b84a37b47fcc32e262d829d8f6f88/lib/src/shared/status.dart#L122) field.

**Comment by hrpath** [comment]
Any news on this front, this could help a lot adoption or cut it down.
Thx

**Comment by acoutts** [comment]
Is there any progress on this support? Currently we can't access the error details and it makes it hard to gracefully handle errors on the frontend when there's no details of the error.

**Comment by acoutts** [comment]
@kriswuollett I got started on this, please see my PR here: #349
