### ISSUE TITLE
ChannelCredentials.secure

### ISSUE THREAD

**Issue by qiuguian** [grpc/grpc-dart#219]
<short description>

<version of the grpc-dart packages used; see your `pubspec.lock` file>

## Repro steps

1. step1
1. step2
1. step3

Expected result: <describe what should have happened>

Actual result: <describe what actually happened>

## Details

<Include any other relevant details, logs, etc.>

**Comment by friddle** [comment]
你应该问的更具体+最好用英文问。

**Comment by qiuguian** [comment]
run in ios is no error but  run in android use flutter,thent got error:Error connecting: HandshakeException: Handshake error in client (OS Error: 
I/flutter ( 8621):   CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:352))

**Comment by friddle** [comment]
你的地址假如和你证书的地址对不上。
即证书的公用名必须和你的请求地址对上。

或者你需要加上secure的authority
```
    return ClientChannel('appapi.github.com',
        port: 443,
        options:
        ChannelOptions(credentials: ChannelCredentials.secure(
            certificates: sslKey, authority: "appapi.github.com"
        )));
```

**Comment by friddle** [comment]
还有一个问题开多个issues一样没人看的。。。

**Comment by sigurdm** [comment]
I am not sure I follow this issue very well. I don't read Chinese.
Any chance you could clarify the issue description in English?

But it is surprising if there is a different behavior between ios and android.
@sortie do you know if there are differences between the Android and ios embeddings that could cause the HandshakeException?

**Comment by friddle** [comment]
@sigurdm  seem's like the problem is he forget to input  ChannelCredentials.secure authority options

**Comment by sigurdm** [comment]
Is this solved?

**Comment by sortie** [comment]
I'm unsubscribing from this issue since the notifications go to my personal mail as this repository is not inside the google organization. If you have any action items for me, please file a Dart SDK issue.

**Comment by nevi-me** [comment]
I also can't read Chinese, but I'm wondering if the issue is the same as the one I've started noticing since upgrading from a very old grpc version (0.x) to the latest.

@sigurdm it looks like the `secure` channel's broken on the latest version. When I try to connect to a grpc server using the default `ChannesCredentials.secure()` option, I'm unable to connect.

Passing the `authority` on `secure()` above fixed it. If it's intended behaviour that the authority always be present, we might need to document it somewhere. Where can I do that, if it's the case and hasn't been documented? Thanks

**Comment by sigurdm** [comment]
@nevi-me thanks What what versions did you switch to and from?
I might have broken the default behavior unintendedly.

**Comment by nevi-me** [comment]
I went from 0.6.4 to 2.1.1. It is for an app that I hadn't updated in a year

**Comment by sigurdm** [comment]
In 0.6.4 authority is computed as:
```
  String get authority => options.credentials.authority ?? host;
```

In 2.1.1 the authority is computed as:
```
  String get authority =>
      options.credentials.authority ?? (port == 443 ? host : "$host:$port");
```

That might be what makes the difference - are you using a non-default port?

**Comment by nevi-me** [comment]
Yes, I'm using ports in the 5000's. I'm curious as to why the check for 443; was it a Google specific thing? I've so far come across more people using non-default ports for gRPC than 80/443.

**Comment by sigurdm** [comment]
I think I made the mistake. The "authority" of the grpc header needs the `(port == 443 ? host : "$host:$port")` logic in, and I thought I could reuse it in the logic that computes the authority for the http2 connection. But that should only have the host name it seems.
