### ISSUE TITLE
Stream error when connection is just initialized

### ISSUE THREAD

**Issue by Sub6Resources** [grpc/grpc-dart#222]
When calling a client method immediately after initializing the connection, sometimes a stream error is thrown. Any subsequent calls on the client are successful. I'm guessing this is some sort of race condition in the initialization of the channel connection.

grpc-dart v2.0.0+1 (on Flutter)

## Repro steps

1. Create a channel and client (I don't believe the configuration matters too much).
      ```dart
      _channel = ClientChannel(
        kGrpcURL,
        port: kGrpcPort,
        options: ChannelOptions(credentials: kChannelCredentials, idleTimeout: Duration(days: 10)),
      );
      
      _client = MyClient(
        _channel,
        options: CallOptions(timeout: Duration(seconds: 10)),
      );
      ```
1. Make an rpc call soon after.
      ```dart
      _client.myRpcMethod(request);
      ```

Expected result: The client should successfully complete the call.

Actual result: An http2 error was occasionally thrown (about once in every 5 times): 

```
gRPC Error (2, HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 2).)
```

## Details

I don't know enough about the internal workings of gRPC to know for sure whether or not this is a race condition, but that's what it seems to be, since only the first call fails, and only occasionally. All consecutive calls work as expected.

/cc @ryan-berger

**Comment by mit-mit** [comment]
Closing as assumed stale
