### ISSUE TITLE
grpc >=2.0.0 dependency conflict with flutter 1.7.8-hotfix-4

### ISSUE THREAD

**Issue by NocturnScholar** [grpc/grpc-dart#226]
Hello,
flutter pub get command failed when i'm trying to use grpc ver. 2.0.0+1.

error output:
"Because grpc >=2.0.0 depends on meta ^1.1.7 and every version of flutter from sdk depends on meta 1.1.6, grpc >=2.0.0 is incompatible with flutter from sdk."

flutter pub get command run successfully when using gprc ver. 1.0.3

## Repro steps

1. add or update grpc to version >= 2.0.0 in pubspec.yaml
2. run flutter pub get

Expected result: command executed succesfully without any warning or error output

Actual result: command failed with error message:
Because grpc >=2.0.0 depends on meta ^1.1.7 and every version of flutter from sdk depends on meta 1.1.6, grpc >=2.0.0 is incompatible with flutter from sdk.

## Details

relevant pubspec.yaml content:
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  grpc: ^2.0.0+1

relevant flutter doctor output:
 Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.12.6 16G2128, locale en-ID)
    • Flutter version 1.7.8+hotfix.4 at /Volumes/Data/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

**Comment by sigurdm** [comment]
We could relax that dependency. I don't think we are using anything from 1.1.7.

Until we have a fix out you should be able to compile using something like:
```
dependency_overrides: {meta: ^1.1.6}
```

**Comment by sigurdm** [comment]
This should be fixed in version 2.0.3.

Thanks for reporting.
