### ISSUE TITLE
Not properly handling http/2 connection becoming not healthy

### ISSUE THREAD

**Issue by tvolkert** [grpc/grpc-dart#228]
Spawned from https://github.com/dart-lang/appengine/issues/117 and https://github.com/dart-lang/http2/issues/46.

For consolidation, I'll leave the original reported issue text the same below and copy any relevant comments over from the other issues.

---

`package:appengine` registers a single `gcloud:DatastoreDB` instance upon server startup, which triggers the following objects to be persisted as part of its object graph:
*  ↳ gcloud:DatastoreDB maintains a reference to a `gcloud:Datastore`
    * (implemented by `appengine:GrpcDatastoreImpl`)
*  ↳ `appengine:GrpcDatastoreImpl` maintains a reference to `grpc:ClientChannel`
*  ↳ `grpc:ClientChannel` maintains a reference to `grpc:Http2ClientConnection`
*  ↳ `grpc:Http2ClientConnection` maintains a reference to `http2:ClientTransportConnection`

I'm seeing cases where the following code is hitting [these lines](https://github.com/dart-lang/http2/blob/04843721d4778dcba8e9b490efca9c0ea809fec8/lib/src/connection.dart#L354-L356):

```dart
} else if (frame is GoawayFrame) { 
  _streams.processGoawayFrame(frame); 
  _finishing(active: false);
}
```

This causes the connection's state to get marked as `IsFinishing/PassiveFinishing`. Then later, grpc tries to issue another request [here](https://github.com/grpc/grpc-dart/blob/1213bc546b46da385afc94e645dd44fefcfb7f82/lib/src/client/http2_connection.dart#L130):

```dart
GrpcTransportStream makeRequest(String path, Duration timeout,
    Map<String, String> metadata, ErrorHandler onRequestFailure) {
  final headers = createCallHeaders(
      credentials.isSecure, authority, path, timeout, metadata,
      userAgent: options.userAgent);
  final stream = _transportConnection.makeRequest(headers);
  return Http2TransportStream(stream, onRequestFailure);
}
```

And it results in the [following error](https://github.com/dart-lang/http2/blob/04843721d4778dcba8e9b490efca9c0ea809fec8/lib/src/connection.dart#L461-L463):

```dart
throw new StateError(
    'The http/2 connection is finishing and can therefore not be used to '
    'make new streams.');
```

Since the underlying http2 connection is retained by our server-wide connection to the datastore, _every single subsequent HTTP request_ to my App Engine server that tries to talk to the datastore fails with this error ("gRPC Error (14, Error making call: Bad state: The http/2 connection is finishing and can therefore not be used to make new streams")

**Comment by tvolkert** [comment]
Copying comment from @mkustermann in https://github.com/dart-lang/appengine/issues/117#issuecomment-520333097

---

To me the issue seems in the code from [package:grpc/src/client.call.dart](https://github.com/grpc/grpc-dart/blob/1213bc546b46da385afc94e645dd44fefcfb7f82/lib/src/client/call.dart#L165):
```dart
 void _sendRequest(ClientConnection connection, Map<String, String> metadata) {
    try {
      _stream = connection.makeRequest(
          _method.path, options.timeout, metadata, _onRequestError);
    } catch (e) {
      _terminateWithError(GrpcError.unavailable('Error making call: $e'));
      return;
    }
    _requestSubscription = _requests
        .map(_method.requestSerializer)
        .handleError(_onRequestError)
        .listen(_stream.outgoingMessages.add,
            onError: _stream.outgoingMessages.addError,
            onDone: _stream.outgoingMessages.close,
            cancelOnError: true);
    // The response stream might have been listened to before _stream was ready,
    // so try setting up the subscription here as well.
    _onResponseListen();
  }
```

which seems to call [package:grpc/src/client/http2_connection.dart](https://github.com/grpc/grpc-dart/blob/1213bc546b46da385afc94e645dd44fefcfb7f82/lib/src/client/http2_connection.dart#L130):

```dart
  GrpcTransportStream makeRequest(String path, Duration timeout,
      Map<String, String> metadata, ErrorHandler onRequestFailure) {
    final headers = createCallHeaders(
        credentials.isSecure, authority, path, timeout, metadata,
        userAgent: options.userAgent);
    final stream = _transportConnection.makeRequest(headers);
    return Http2TransportStream(stream, onRequestFailure);
  }
```

Any http/2 connection can be in a finishing state (for different reasons, maybe the server wants to close the connection soon, we ran out of stream ids, ...). In this state it's not possible to make new http/2 streams.

Yet this code unconditionally calls `_transportConnection.makeRequest()`, which causes an exception to be thrown, which then eventually results in this error coming from `GrpcDatastoreImpl.lookup()` in the stack from https://github.com/dart-lang/appengine/issues/117#issuecomment-520174092.

What the code should do instead is check whether we're allowed to make new requests (via `_transportConnection.isOpen`), if not, we can simply make a fresh http/2 connection.

In fact until recently `package:appengine` had it's own grpc implementation which handled this better (after [22f7c09](https://github.com/dart-lang/appengine/commit/22f7c097a6d0063f1f98415c30df3ad5b2fee697)  `package:appengine` uses `package:grpc`).

Looking at the former grpc implementation in [package:appengine/src/grpc_api_impl/grpc.dart](https://github.com/dart-lang/appengine/blob/039684887f97bc1281882f1209b0ac66b98349da/lib/src/grpc_api_impl/grpc.dart#L116):
```dart
  Future<T> invoke<T extends protobuf.GeneratedMessage>(String service,
      String method, protobuf.GeneratedMessage request, T response) async {
    ...

    // If the current connection is not healthy we'll make a new one:
    // NOTE: Several concurrent callers will end up using the same dialer and
    // will therefore obtain the same connection.
    // NOTE: It seems like Google's gRPC endpoints will forcefully close the
    // connection after precisely 1 hour. So we *proactively* refresh our
    // connection after 50 minutes. This will avoid one failed RPC call.
    final bool isHealthy = _connection != null && _connection.isOpen;
    final bool shouldRefresh = _stopwatch.elapsed.inMinutes > 50;
    if (!isHealthy || shouldRefresh) {
      if (isHealthy) _connection.finish();
      _connection = await _dialer.dial();
      _stopwatch.reset();
    }
```

=> The comment basically explains it: If the connection `!isHealthy` we will make a new http/2 connection.

Since there can be several such `invoke` calls going on at the same time it uses a [Dialer](https://github.com/dart-lang/appengine/blob/039684887f97bc1281882f1209b0ac66b98349da/lib/src/grpc_api_impl/grpc.dart#L298) to ensure only one new http/2 connection is made:

```dart
/// Used for dialing http/2 endpoints.
///
/// If several callers attempt to dial at the same point in time, only the first
/// one will trigger a http/2 connection attempt and all of them will receive
/// the same connection (or an error).
///
/// The number of http/2 dialing attempts will be rate-limited in order to not
/// flood the server and avoid busy loops where callers constantly attempt
/// to dial a nonexistent/down peer.
class Dialer {
```

**Comment by tvolkert** [comment]
@jonasfj @sigurdm @mkustermann, is anyone looking into this?

If I try to fix, who's the right person to review?

**Comment by friddle** [comment]
thanks！

**Comment by tvolkert** [comment]
@sigurdm just noticed https://github.com/grpc/grpc-dart/pull/231 - thanks!

**Comment by sigurdm** [comment]
https://github.com/grpc/grpc-dart/pull/231 is landed now.

**Comment by tvolkert** [comment]
Thanks for the fix @sigurdm 🙂
