### ISSUE TITLE
Add dart client to grpc-web-compatibility-test repo

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc/grpc-dart#235]
Hi!

I'm the author of https://github.com/johanbrandhorst/grpc-web-compatibility-test, where I've been testing various grpc-web proxies with grpc-web clients. I'd love to have a Dart grpc-web client compiled using the provided proto file and tested against the proxies (envoy, improbable).

What do you think?

**Comment by joeblew99** [comment]
Seems that Flutter Web is on the Roadmap ?
https://github.com/grpc/grpc-web/blob/master/ROADMAP.md#web-framework-integration

**Comment by sigurdm** [comment]
That would give some nice extra testing! I'm sure we'll uncover issues.
I think we should do this for sure!
Not sure when we can make it happen though.

**Comment by johanbrandhorst** [comment]
Great, I might look into it myself, but I have no Dart experience so any pointers to solve this specific problem would be great. Also, we're currently using an automated testing framework to run the tests in CI, what would be the easiest way to create something like a .js bundle that could be run in a browser?

**Comment by sigurdm** [comment]
You can probably get inspiration from https://github.com/grpc/grpc-dart/tree/master/example/grpc-web

You need a `pubspec.yaml` that declares grpc-web as a dependency.
And you need a web/main.dart

If you have dart installed on the CI you should be able to run something along the lines of:
```bash
## Install protoc, skip if it is installed by CI.
wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip 
unzip -d protoc protoc.zip
export PATH=$PWD/protoc/bin:$PATH

pub global install protoc_plugin # installs dart support for protoc
## Make sure protoc can find protoc-gen-dart
export PATH=$HOME/.pub-cache/bin:$PATH

## Compile protos
protoc --dart_out=grpc:lib/src/generated -Iprotos protos/*.proto

## Install program dependencies, should run from program folder
pub get

## Compile dart to js bundle
dart2js web/main.dart -o main.js
```

**Comment by johanbrandhorst** [comment]
Thanks a lot!

**Comment by joeblew99** [comment]
@johanbrandhorst If you get stuck on the dart flutter stuff buzz me and i can help.

**Comment by mit-mit** [comment]
Closing as presumed answered
