### ISSUE TITLE
Flutter: gRPC secure connection works in debug but not in release mode

### ISSUE THREAD

**Issue by fusion44** [grpc/grpc-dart#236]
Hi!

I try to establish a secure connection to a [gRPC server](https://github.com/lightningnetwork/lnd). This works in debug mode but fails in release mode. See my code below.

Library versions
```
grpc: ^2.1.1 
protobuf: ^0.13.15
```
I've also tried grpc: ^1.0.3 but same issue.

## Repro steps
```dart
_establishConnection(DoCheckLNDConnectionEvent event) async {
    ChannelCredentials creds = ChannelCredentials.secure(
      certificates: event.data.certificate, 
      onBadCertificate: (X509Certificate certificate, String host) {
        // Trust the certificate
        // This is never called in release mode
        print("trusting cert");
        return true;
      },
    );

    CallOptions opts = CallOptions(
      metadata: {"macaroon": event.data.macaroon},
    );

    _clientChannel = ClientChannel(
      event.data.host,
      port: event.data.port,
      options: ChannelOptions(credentials: creds),
    );

    _lightningClient = LightningClient(
      _clientChannel,
      options: opts,
    );

    print("client ready");

    var infoRequest = GetInfoRequest();
    try {
      print("awaiting response");
      var response = await _lightningClient.getInfo(infoRequest, options: opts);
      print("got response");
      return CheckLNDConnectionSuccessState(info: response);
    } catch (e) {
      return CheckLNDConnectionErrorState(error: e.toString());
    }
  }
```

Expected result: 
Connect to the server in release mode and get a successful response like it does in debug mode.

The call
```dart 
var response = await _lightningClient.getInfo(infoRequest, options: opts);
```
just throws a gRPC exception:
`
gRPC Error (14, Error connecting: SocketException: Connection failed (OS Error: Permission denied, errno = 13), address = xxx.xx.xxx.xxx, port = 10009)
`
## Details
I notice the onBadCertificate callback is only called in debug mode.

**Comment by sigurdm** [comment]
This is very mysterious - there should be no reason code runs different in release mode.
Do you think you can make a small reproduction and post (eg. in a repo?)

**Comment by fusion44** [comment]
I've created a [minimal sample](https://github.com/fusion44/grpc_dart_error). 

Unfortunately, I have no idea on how to implement the server side of this issue except giving you acces to my test server. Can I send you the necessary certificate and macaroon through a private gist? It contains only test data for development, but I still don't want to publish the keys on github publicly :smile:. Unfortunately, setting up the server yourself is quite involved.

**Comment by sigurdm** [comment]
Yes, I don't know how private gists work. But you can also send to sigurdm@google.com

**Comment by sigurdm** [comment]
You need permission to access the internet.
add:
```
    <uses-permission android:name="android.permission.INTERNET"/>
```
to `android/app/src/main/AndroidManifest.xml`.

Per default only `debug` and `profile` mode has access to the internet (that is needed to connect with the flutter tools and observatory).

See: https://github.com/flutter/flutter/issues/8421

**Comment by sigurdm** [comment]
thanks to @sortie for knowing this!

**Comment by fusion44** [comment]
Oh, sorry about that. Setting the permission did the trick! Knowing this the error message makes sense. 

Thanks!
