### ISSUE TITLE
Certificate validation fails when trying to establish secure connection to endpoint on port other than 443

### ISSUE THREAD

**Issue by tp** [grpc/grpc-dart#237]
As I commented https://github.com/grpc/grpc-dart/issues/50#issuecomment-527879094 I have some issue connecting to a server with a self-signed certificate on port 50051 on localhost, while it works fine on our staging setup on port 443.

> When trying to access it locally (localhost:50051) I get an error:

```
gRPC Error (14, Error connecting: HandshakeException: Handshake error in client (OS Error: 
        CERTIFICATE_VERIFY_FAILED: ok(handshake.cc:352)))
```

~~After some debugging I think that it's related to the authority building added in https://github.com/grpc/grpc-dart/pull/207~~ (see below, I think the authority is not the real breaking change here, but it's usage in establishing the secure connection)

This is an excerpt from my certificate:

```
…
            X509v3 Subject Alternative Name: 
                DNS:localhost, DNS:grips.staging.de, DNS:grips.production.de, IP Address:127.0.0.1, IP Address:0.0.0.0
    Signature Algorithm: sha256WithRSAEncryption
…
```

So I guess in order to comply with the authority in [here](https://github.com/sigurdm/grpc-dart/blob/35d627dbb248ce1e846d992bcd75e6048861b0ff/lib/src/client/http2_connection.dart#L65)  I would have to add an alternative name like `localhost:50051` to the certificate.

My question though then is whether it's correct to specify ports in the certificate (some quick googling indicated it's not a common/recommended practice), or whether we should change the authority calculation?

**Comment by tp** [comment]
Ok, seems like for the authority that is desired to include the port
https://github.com/grpc/grpc-dart/commit/b7be3af34bba6a6f2ea2862e8d5397cbcda59abc / https://stackoverflow.com/questions/50034792/should-the-http-2-authority-header-include-port-number

But then there is the question why this changed from passing the `host` to passing the `authority` to create the connection.

cc @sigurdm as you were driving that linked change.

**Comment by tp** [comment]
I had the error with version `2.0.0+1`, so I thought above trying the latest versions (even thought I initially assumed security wouldn't be prone to much change, but since this is under active development why not try it out.)

It's now fine on version 2.1.0 (which uses `host`) as well as 2.1.1 (which uses `authority`).

So it seems solved to me. There's probably some other change in the 2.0.0 to 2.1.0 diff that affected how the certificate validation works which I have not found yet.

**Comment by tp** [comment]
Re-opening, I seem to have been misguided by hot-restarting, now I see the issue again. Will add more details shortly.

**Comment by tp** [comment]
I had the error originally with version `2.0.0+1`.

It's fine on version 2.1.0 (which uses `host`), but doesn't work with 2.1.1 (which uses `authority`, introduced in https://github.com/grpc/grpc-dart/pull/233).

For now I have pinned the dependency to 2.1.0 as a workaround.

**Comment by sigurdm** [comment]
> But then there is the question why this changed from passing the host to passing the authority to create the connection.

This was a failed refactor :( . Hopefully the patch fixes it.

**Comment by mit-mit** [comment]
Closing as presumed fixed in above mentioned PR
