### ISSUE TITLE
Gets the header returned by the server

### ISSUE THREAD

**Issue by dingzuhua** [grpc/grpc-dart#246]
I needed to get some information from the header returned from the server and update the local, but I didn't find a good way

**Comment by sigurdm** [comment]
I'm not sure I fully understand the issue, but can you:

```
    final responseFuture =  client.foo(FooRequest());
    final headers = await responseFuture.headers;
    final response = await response;
```

**Comment by dingzuhua** [comment]
> final headers = await

Thank you very much. It's just what I wanted
