### ISSUE TITLE
Support CompositeChannelCredentials

### ISSUE THREAD

**Issue by yuphing-ong** [grpc/grpc-dart#248]
What is the equivalent in dart/flutter for using CompositeChannelCredentials (as per https://grpc.io/docs/guides/auth/)?  

## Details

In python, I would do this:
```
client_token = grpc.access_token_call_credentials("access_token_for_testing")
credentials = grpc.ssl_channel_credentials(root_certificates=trusted_cert)
composite_credentials = grpc.composite_channel_credentials(credentials, client_token)
channel = grpc.secure_channel(f"{server_host}:{server_port}", composite_credentials)
```
And on the server side, I would use a key of "authorization" to get the access token value, from the context invocation metadata.

But in dart, I see no such equivalent.  Or do we have to extent the base ChannelCredentials and manually add our own invocation metadata map for ```{'authorization': 'bearer '+acess_token}```, which would seem really strange.

**Comment by ansarizafar** [comment]
It would be great If someone from the core team can reply?

**Comment by yuphing-ong** [comment]
I don't know if this is right, but I did exactly what I wrote above, i.e. used CallOptions to add the medata, e.g.
`final stub = Client(channel, options: CallOptions(metadata:{'authorization':'Bearer accesstokendetails'}))`

**Comment by mraleph** [comment]
The solution right now is to manually change `metadata` through `CallOptions` (or when interceptors land - use interceptors).
