### ISSUE TITLE
Server crash with Stream broadcast

### ISSUE THREAD

**Issue by Xyzcancer** [grpc/grpc-dart#262]
Hi, I'm experiencing an issue with Streams in grpc package. Version is 2.1.3.
I'm trying to build simple chat app with one broadcast stream.

## Repro steps
1) I'm connecting to server's stream
2) Send message to StreamController
3) Reload the app 
4) Subscribe on stream and send message again 

Expected result: Stream doesn't close after app's relaunch, but if it does, then flag isClosed must be true

Actual result:  it leads to server crash. Bad state: Cannot add event after closing. Flag isClosed = false;

**Comment by mraleph** [comment]
Duplicate of #67
