### ISSUE TITLE
Grpc Error(14) If Metadata is passed with Streaming RPC call

### ISSUE THREAD

**Issue by sh0umik** [grpc/grpc-dart#264]
I have an upload stream rpc. And in the client side i am using grpc-web. 
```
rpc (stream request) returns (response);
```
I am using golang as backend. If i pass no metadata then it works fine but with the metadata provided in the client i am getting `gRPC Error (14, XhrConnection status 0)`

```
 var resp = await this
          .client
          .uploadFile(transformer.stream,
              options: CallOptions(metadata: {
                'upload_dir': 'store/logo',
              }));
```

Even if i send empty metadata it works !! `metadata: {}`

I am using the latest `grpc: ^2.1.3`

Expected result: Want to pass metadata from client to server ( golang )

Actual result: not working if metadata is passed in CallOptions

I need this functionality in grpc-web. Haven't tested with normal grpc yet.

**Comment by invidious9000** [comment]
We're seeing similar behavior, when the header value length <= 193 then metadata is successfully sent and the call proceeds as normal, but as soon the length of the value exceeds 193b the call fails with: gRPC Error (14, Failed parsing HTTP/2). From server side the connection appears to be partially established but fails before making it into implementation code - we are using C# server and are able to send larger header payloads without issue when going C# -> C#, it's only when grpc-dart client is used that we see this issue.

I have been digging through header sanitization / http2 limits but there's nothing that immediately stands out nor are there any real hints why this is breaking / where limits might need to be adjusted.

**Comment by sigurdm** [comment]
These sound like two different bugs. One is on grpc-web and one is grpc over http2...

**Comment by bsr203** [comment]
For me it only happens with grpc-web. Mobile client works fine.

```
gRPC Error (14, XhrConnection status 0)
```
get this when metadata is passed like 

```
options: CallOptions(metadata: {"token": "...token..."})
```

**Comment by chipkent** [comment]
I am seeing this problem as well.  I get the error with grpc-web, and the mobile client works fine.  I see the problem even though I do not use metadata.

**Comment by mraleph** [comment]
This seems stale. @sh0umik @invidious9000  if you are still having issues, please provide a reproduction. 

@chipkent if you are still experiencing issues please file a separate issue with as much details as possible.
