### ISSUE TITLE
Flutter-web equivalent of ChannelCredentials allowBadCertificates?

### ISSUE THREAD

**Issue by TannerYoung** [grpc/grpc-dart#266]
## Description
I want to test against a local grpc server with flutter web, but I keep getting `net::ERR_CERT_AUTHORITY_INVALID`. Is there a way to trust invalid certificates like I can with ClientChannel?

## Grpc Version 

grpc: ^2.1.3

## Current Code

```
  static final String _serviceAddress = 'grpc.localhost';
  static final int _servicePort = 8090;

  static final GrpcWebClientChannel _grpcChannel = GrpcWebClientChannel.xhr(
    Uri(scheme: "https", host: _serviceAddress, port: _servicePort),
  );

  static final _client = new AccountServiceClient(_grpcChannel,
      options: CallOptions(timeout: Duration(seconds: 30)));
```

**Comment by sigurdm** [comment]
This is not something that can be done from javascript(compiled from dart). You need to configure your browser to do this.
Perhaps routing through https://ngrok.com/ can create a nice development flow.

You can also look into https://letsencrypt.org/docs/certificates-for-localhost/
