### ISSUE TITLE
TLS or Authentication Support for grpc-web

### ISSUE THREAD

**Issue by sh0umik** [grpc/grpc-dart#268]
I am currently using dart grpc-web using `GrpcWebClientChannel.xhr` I was looking for a secure channel like `ChannelCredentials.secure` for web. My end goal is to establish a minimal security between the client and server ( golang grpc )

Is there are any other way to achieve this ? Or should I have to wait for `GrpcWebClientChannel.secure` ?

**Comment by ansarizafar** [comment]
Waiting for reply from a core team member.

**Comment by sigurdm** [comment]
grpc-web is based on an http-request (xmlHttpRequest) from the browser. If it accesses an https address it will have security one way (the browser will verify the server certificate).

Usually authentication of a web request would be by setting custom headers on the call.
That should already be possible by using client.call(request, options: CallOptions(metadata: {...}) ) to your call.

Cookie-based authentication would maybe make sense - maybe we could expose a way to set https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials .

**Comment by mraleph** [comment]
`withCredentials` got added by #347
