### ISSUE TITLE
why there is no onCompleted on the client site stream call  like java or node？

### ISSUE THREAD

**Issue by saber2coder** [grpc/grpc-dart#270]
my question is i use a stream call and steam response method，when stream call all send，the server response and close the stream，but i need this steam to stay alive for receive push data form the server ，in java or node ，the client site has a method requestObserver.onCompleted() or call.end to close the steam，if i dont call them ，the stream will stay alive，and receive the push data，why dart dont have this method

**Comment by saber2coder** [comment]
hope for answer

**Comment by ansarizafar** [comment]
I also need this.

**Comment by mraleph** [comment]
`ResponseStream` has `cancel` method which would close communication channel with the server.
