### ISSUE TITLE
Calls to other gRPC implementations with metadata fail with: gRPC Error (14, Failed parsing HTTP/2).

### ISSUE THREAD

**Issue by invidious9000** [grpc/grpc-dart#271]
We're seeing errant behavior when a header value length exceeds 193b, the call fails with: gRPC Error (14, Failed parsing HTTP/2). 

When using grpc-dart client -> grpc-dart server or C# client -> C# server this issue is not present, the specific combination we're seeing it with is grpc-dart client -> C# server (not grpc-dotnet). From server-side the connection appears to be partially established but fails before making it into implementation code due to missing auth context.

This can be reproduced with greeter/hello world examples and passing a binary (-bin) header
that exceeds 193 bytes in length.

I dug through header sanitization / http2 header limits but there's nothing that immediately stands out nor are there any real hints why this is breaking / where limits might need to be adjusted.  

@sigurdm Could this be an issue in grpc native core (or C#)? Would grpc repo be a better place for this issue?

_Originally posted by @invidious9000 in https://github.com/grpc/grpc-dart/issues/264#issuecomment-572256668_

**Comment by sigurdm** [comment]
This sounds very mysterious.

Could you try to monitor the network traffic with wireshark or similar to see differences in what is sent in the different configurations.

**Comment by mit-mit** [comment]
Closing as stale
