### ISSUE TITLE
Possibility to perform action after service call

### ISSUE THREAD

**Issue by radzish** [grpc/grpc-dart#277]
How can I perform action after service call is made?

I see that current server API can be configured with interceptors - but those get called only before service call is made. It looks like with current implementation it is not possible to perform action after request is done.

Examples of such usage:
- log execution time of the call
- perform DB connection to be closed (or released to the pool)
etc..

**Comment by mraleph** [comment]
No, this is not possible right now. Though one could imagine changing `ServiceCall` API to expose some of the lifecycle events as streams. Then you would be able to subscribe to them through interceptors. We don't have bandwidth to implement such feature but we would be happy to take a PR if you make one.
