### ISSUE TITLE
Feature Request: provide a way to set withCredentials with grpc-web

### ISSUE THREAD

**Issue by dotneet** [grpc/grpc-dart#280]
In my understanding setting true to withCredentials of a HttpRequest instance is needed to send a cookie.
However a way to set withCredentials does not seem to be provided.

I think http-only cookie is useful to realize secure authentication with grpc-web.
Without http-only cookie we wouldn't persist an access token securely on web environment.

**Comment by ansarizafar** [comment]
Is there any any on this issue? I badly need this.

**Comment by sigurdm** [comment]
It would make sense to allow this to be set when creating the channel.
I don't think we currently have cycles for this. But we would review a PR.

**Comment by mraleph** [comment]
This has been implemented in bb4eab0f1ff0649760f52e4f911b9e5cfc64df07
