### ISSUE TITLE
Match grpc/grpc release numbers?

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-dart#282]
Dart `grpc` [releases](https://github.com/grpc/grpc-dart/releases) went from v0.4.1 to 2.1.3; although, actually, it seems that 2.1.3 is't an official release.

Why not follow the [grpc/grpc release numbers](https://github.com/grpc/grpc/releases)?

cc @mit-mit @nicolasnoble @thisisnotapril

**Comment by mit-mit** [comment]
So far we've used the regular Dart semantic versioning process to version the Dart package. I'm happy to consider aligning more with other gRPC packages in the future. For now, there's isn't much we can do, as we're already on v 2.2.x.

**Comment by chalin** [comment]
Sure, I understand. Thanks for the followup @mit-mit.

On a related note, it would be helpful if every official release that lands in pub, also gets tagged as a release in the repo. Currently, [grpc on pub is at 2.2.0](https://pub.dev/packages/grpc), but there is no such [release on GitHub](https://github.com/grpc/grpc-dart/releases).
