### ISSUE TITLE
Support for setting ChannelOptions for GrpcWebClientChannel like http2Client channel

### ISSUE THREAD

**Issue by nateshmbhat** [grpc/grpc-dart#284]
Just like how : http2Client channel takes options : 

```
ClientChannel(this.host,
      {this.port = 443, this.options = const ChannelOptions()})
      : super();

```

Give option to set ChannelOption like this for GrpcWebClientChannel too which is now just limited to giving the url directly like this : 

`GrpcWebClientChannel.xhr(Uri.parse('http://localhost:8080',));`

**Comment by sigurdm** [comment]
That was part of the initial design. But in the end none of the existing options made much sense for the web channel.
What options would you like to give?

**Comment by nateshmbhat** [comment]
I just wanted it to be more consistent with the already http2 implementations.

I don't have any particular option in mind yet.

**Comment by nathantsoi** [comment]
Not sure where to ask this, so please point me in the right direction if this is not the right issue: I actually need to set the `GRPC_SSL_TARGET_NAME_OVERRIDE_ARG   "grpc.ssl_target_name_override"` channel arg in the ClientChannel (http2). Is this possible currently?

I see ChannelOptions doesn't have a parameter or map to pass this through, is that correct? If so, I can possibly add it, if someone could point me towards the grpc docs on how channel args are sent over http2.

**Comment by mraleph** [comment]
Closing this issue for now because it is unclear if this consistency buys anything.

@nathantsoi When you create `ChannelCredentials` you can supply `authority` which would be used to verify connection. In future please don't hijack unrelated issues with questions.

**Comment by TyBarthel** [comment]
@sigurdm Is there a way to do client certificates without ChannelOptions with the web channel?

See the following example for the normal gRPC ClientChannel:
https://github.com/grpc/grpc-dart/issues/134#issuecomment-502473319

**Comment by mraleph** [comment]
@TyBarthel I don't think browsers API like XHR support explicitly passing client certificates, so it is impossible.
