### ISSUE TITLE
Documentation Error for Dart GRPC Basics

### ISSUE THREAD

**Issue by stephengrice** [grpc/grpc-dart#286]
Hello, I got confused when following the GRPC Basics article about writing a client [here](https://grpc.io/docs/tutorials/basic/dart/#creating-a-stub). I had to examine the [example source code](https://github.com/grpc/grpc-dart/blob/master/example/route_guide/lib/src/client.dart) to figure out what the problem was. The variable referenced as "client" in the tutorial is later changed to "stub" without any explanation. I think this is an easy fix, just make them both match. Here is what I mean:

Code snippet 1 - Variable referred to as **client**:
```
final client = RouteGuideClient(channel,
    options: CallOptions(timeout: Duration(seconds: 30)));
```
Code snippet 2 - Variable referred to as **stub**:
```
final point = Point()
  ..latitude = 409146138
  ..longitude = -746188906;
final feature = await stub.getFeature(point));
```

<version of the grpc-dart packages used; see your `pubspec.lock` file>
n/a

## Repro steps

1. Visit the [article](https://grpc.io/docs/tutorials/basic/dart/#creating-a-stub).

2. View the code snippets side-by-side.

Expected result: **client** and **stub** should have been the same name

Actual result: I had no idea what **stub** was referring to until digging deeper.

## Details

Referred to [example source](https://github.com/grpc/grpc-dart/blob/master/example/route_guide/lib/src/client.dart) to find the answer. To match this, both references should be changed to **stub**.

**Comment by JarrodCColburn** [comment]
@stephengrice 
Hey, this might be a good suggestion it's been a while since I've done the tutorial. 
But the documentation is actually in the repo grpc.io (not here on grpc-dart) and the file is here https://github.com/grpc/grpc.io/blob/master/content/docs/languages/dart/basics.md

Could you please edit and open a PR there and close this one. thanks

**Comment by stephengrice** [comment]
Thank you Jarrod. I opened an issue on the repository as you suggested. Closing this one out.
