### ISSUE TITLE
Release 2.1.4...?

### ISSUE THREAD

**Issue by rajmaniar** [grpc/grpc-dart#289]
There's some sweet new code in master (like shared sockets)! :)
When can we expect to see a version bump in pub?

**Comment by ansarizafar** [comment]
I am also waiting for new release.

**Comment by gustav3d** [comment]
Could the contributors please clarify is they are to actively support this project ? 
And if not, if things are to continue like in 2020,  appoint other people as contributors.

**Comment by edyu** [comment]
2.2.0 is just released except I have no idea what's new. :)

**Comment by rajmaniar** [comment]
Looks like it's the tip of the master branch. 🎉
