### ISSUE TITLE
Can i use grpc in AngularDart?

### ISSUE THREAD

**Issue by upday7** [grpc/grpc-dart#294]
I got this error when compiling, does this mean i cannot use dart grpc in AngularDart?

[INFO] 10.8s elapsed, 2064/2068 actions completed.
[WARNING]build_web_compilers:entrypoint on web/main.dart: Skipping compiling angular_app|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

angular_app|lib/src/common/metadata.dart
angular_app|lib/src/common/api_client.dart
grpc|lib/src/client/transport/http2_credentials.dart
grpc|lib/src/client/http2_connection.dart
grpc|lib/src/server/server.dart
grpc|lib/src/shared/security.dart
http2|lib/transport.dart
http2|lib/src/hpack/huffman.dart
http2|lib/src/hpack/hpack.dart
http2|lib/src/async_utils/async_utils.dart
googleapis_auth|lib/src/oauth2_flows/metadata_server.dart
googleapis_auth|lib/src/oauth2_flows/auth_code.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
[INFO] Running build completed, took 12.0s
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 174ms
[INFO] Succeeded after 12.2s with 2169 outputs (6820 actions)
[INFO] ------------------------------------------------------------------------

**Comment by sigurdm** [comment]
You should be able to use the library `package:grpc/grpc_web.dart` to make grpc-web requests.

You cannot do regular grpc requests from the web.
