### ISSUE TITLE
GrpcError: Error connecting: HandshakeException

### ISSUE THREAD

**Issue by andreddie81** [grpc/grpc-dart#295]
I am trying to connect to a server using a secure client channel over grpc in my flutter app.

```
// read certificate from assets and convert to int
final cert = await rootBundle.load('assets/certificates/client_certificate.pem');
final certAsList = cert.buffer.asUint8List();

// add credentials
final creds = ChannelCredentials.secure(certificates: certAsList)

// create secure channel
final secureChannel = ClientChannel(_hostAddress,
        port: _port, options: ChannelOptions(credentials: creds));
```
I am getting 2 different types of errors, depending on the configuration of the ChannelCredentials:

if I code it like:

```
final creds = ChannelCredentials.secure(
        certificates: certAsList, onBadCertificate: (cert, host) => true); 
```
I get:

`gRPC Error (14, Error connecting: HandshakeException: Handshake error in client (OS Error:SSLV3_ALERT_BAD_CERTIFICATE(tls_record.cc:587)))`

If I code it skipping the onBadCertificate callback:

```
 final creds = ChannelCredentials.secure(
        certificates: certAsList);
```
I get:

`gRPC Error (14, Error connecting: HandshakeException: Handshake error in client (OS Error:CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354)))`

What to do here?

**Comment by mraleph** [comment]
Unfortunately hard to know what exactly is going wrong without a way to reproduce, something is wrong with your certificate, but unclear what exactly.
