### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by brianoh** [grpc/grpc-dart#296]
The documentation for the helloworld example states that the command to generate the proto files is:
```
$ protoc --dart_out=grpc:lib/src/generated -Iprotos protos/helloworld.proto
```

As far as I could ascertain, this is incorrect.

After some time I stumbled across what appears to be the correct syntax, viz:
```
protoc --dart_out=../lib/src/generated -I=. helloworld.proto
```

**Comment by sigurdm** [comment]
I think the documented command is right.

It works for me. You working directory needs to be `grpc-dart/example/helloworld`.

The `grpc:` part is needed to produce the grpc stubs for the service.

**Comment by brianoh** [comment]
It was the "-Iprotos" that I meant to highlight.

**Comment by sigurdm** [comment]
The -Iprotos is correct if your working directory is `grpc-dart/example/helloworld`. It tells protoc to use that as a base-dir for resolving imports.

**Comment by JarrodCColburn** [comment]
@brianoh It looks like you had cd'd into `protos` folder, but should have been one folder up. this is why your `-I=.` was in the same  folder, and your `--dart_out=..` had to back up a folder.
Can you please close #296

**Comment by mit-mit** [comment]
Yes, thanks @JarrodCColburn, closing
