### ISSUE TITLE
Could not get helloworld to work after generating proto files

### ISSUE THREAD

**Issue by brianoh** [grpc/grpc-dart#297]
The generated proto.dart files supplied with the helloworld example differ from those that I create using protoc. That is a problem for me because I want an example so that I can write a program based on the usage of the proto.dart files.

Am I doing something wrong, or has the example become out-of-date?

The supplied and newly generated Proto files are as follows:
```
   -- Supplied proto files --
      3,347 helloworld.pb.dart
        233 helloworld.pbenum.dart
      1,807 helloworld.pbgrpc.dart
        537 helloworld.pbjson.dart 
```
```
   -- Newly-generated proto files --
      3,598 helloworld.pb.dart
        226 helloworld.pbenum.dart
        851 helloworld.pbjson.dart
      1,287 helloworld.pbserver.dart
```

**Comment by sigurdm** [comment]
Notice the example uses an old version of protobuf, and the generated code was made with a corresponding version of protoc_plugin. If you want to use your newly generated files you need to update the version of protobuf in example/helloworld/pubspec.yaml and run `pub get` again.

We should ideally update the version of protobuf used by the examples, and regenerate with the newest protoc. But it has very low priority as newer versions have no relevant new features for the example.

**Comment by brianoh** [comment]
Thanks for the reply.
Not sure what I did that was wrong. I removed the version number from  "protobuf: ^1.0.1" and ran "pub get".
The version that it downloaded was 1.0.1 (the same as existing).

I checked the latest version on pub viz: https://pub.dev/packages/protobuf
and it shows:  "protobuf 1.0.1  Published Nov 11, 2019 "
afaik that is the same version as the example supplied.

Unsurprisingly, when I run the server, I get the following response:
```
dart server.dart
server.dart:14:43: Error: The parameter 'call' of the method 'GreeterService.sayHello' has type 'ServiceCall', which does not match the corresponding type, 'ServerContext', in the overridden method, 'GreeterServiceBase.sayHello'.
 - 'ServiceCall' is from 'package:grpc/src/server/call.dart' ('../../../../flutter/.pub-cache/hosted/pub.dartlang.org/grpc-2.1.3/lib/src/server/call.dart').
 - 'ServerContext' is from 'package:protobuf/protobuf.dart' ('../../../../flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-1.0.1/lib/protobuf.dart').
Change to a supertype of 'ServerContext', or, for a covariant parameter, a subtype.
  Future<HelloReply> sayHello(ServiceCall call, HelloRequest request) async {
                                          ^
../lib/src/generated/helloworld.pbserver.dart:19:32: Context: This is the overridden method ('sayHello').
  $async.Future<$0.HelloReply> sayHello($pb.ServerContext ctx, $0.HelloRequest request);
                               ^
server.dart:20:26: Error: A value of type 'GreeterService' can't be assigned to a variable of type 'Service'.
 - 'GreeterService' is from 'server.dart'.
 - 'Service' is from 'package:grpc/src/server/service.dart' ('../../../../flutter/.pub-cache/hosted/pub.dartlang.org/grpc-2.1.3/lib/src/server/service.dart').
  final server = Server([GreeterService()]);
```

Have I overlooked doing something?
Perhaps if you have the time, another updated version of helloworld would solve the problem.

**Comment by brianoh** [comment]
I should have read your response to #296 first, because that appears to have solved the problem.

The documentation does appear to need a slight change, because afaik the correct command for the generated files is:
```
protoc --dart_out=grpc:. -I=. helloworld.proto
```
This is slightly different to that which is documented viz:  "-I=."
