### ISSUE TITLE
Generated code does not comply with dartfmt standards

### ISSUE THREAD

**Issue by KOGI** [grpc/grpc-dart#305]
After generating dart files, said files are not compliant with `dartfmt` standards. This has the effect of causing builds to fail (several package developers require proper formatting in order to contribute) as well as significant score deductions employed by `dart.dev` itself when an author publishes a package that includes files generated by this library.

The gRPC lib should either run `dartfmt` or natively generate compliant code in order to avoid significant problems for authors that may choose to use this lib.

**Comment by sigurdm** [comment]
This is really a protoc_plugin issue.

**Comment by sigurdm** [comment]
But it is true! The easy work-around is to have your compilation script run `dartfmt` on the generated code before checking it in.

But it would not be too hard to make protoc_plugin call `dartfmt` itself. (only there might be version issues - but I don't think they would be too bad.)

**Comment by KOGI** [comment]
> This is really a protoc_plugin issue.

You're completely right! My bad. Sorry for the noise!

**Comment by KOGI** [comment]
For anyone else that might find themselves here, the resubmitted issue in the right project can be found here: https://github.com/dart-lang/protobuf/issues/368
