### ISSUE TITLE
[Question] Is HTTP2 supported with web?

### ISSUE THREAD

**Issue by muzzah** [grpc/grpc-dart#307]
Sorry but the documentation is not clear and I am assuming it is not just by looking at source code and seeing a HTTP1 request coming from the browser. I take it if we have a http2 based GRPC server running then this library is no good?

**Comment by JarrodCColburn** [comment]
@muzzah 
I think you're going to have to use `package:grpc/grpc_web.dart` for your browser on the client-side.
This has a different api. For example the constructor is `GrpcWebClientChannel.xhr(Uri uri)`).

Also, you'll have to setup a proxy for your server. Like https://www.envoyproxy.io/
I got the basic example working by following https://github.com/grpc/grpc-dart/tree/master/example/grpc-web

**Comment by JarrodCColburn** [comment]
Please take a look at grpc-web example:
https://github.com/grpc/grpc-dart/tree/master/example/grpc-web

**Comment by JarrodCColburn** [comment]
Please take a look at https://grpc.io/blog/state-of-grpc-web/#the-grpc-web-spec
"It is currently impossible to implement the HTTP/2 gRPC spec 3 in the browser, as there is simply no browser API with enough fine-grained control over the requests...."

Please give this a read, and kindly close issue. thanks
