### ISSUE TITLE
Add a common import file

### ISSUE THREAD

**Issue by long1eu** [grpc/grpc-dart#308]
Right now when I want to use conditional importing if the target platform supports `dart.library.html`, there is no way to only import the base classes for `CallOptions` and `ClientChannel`. Because of this I ended up importing then from `src`:

```
import 'package:grpc/src/client/call.dart' show CallOptions;
import 'package:grpc/src/client/channel.dart' show ClientChannel;
```

There should be a way to only import the common interface between `io` and `web`, something this `import 'package:grpc/common.dart';`.

**Comment by JarrodCColburn** [comment]
@long1eu Is that what `import 'package:grpc/service_api.dart` does?
The service API is supposed to exports the minimum api to define server and client stubs.

**Comment by long1eu** [comment]
@JarrodCColburn you are right. Sorry for that :D

**Comment by JarrodCColburn** [comment]
Are you creating a class, one version for browser and another for non-browser, then conditionally importing? 
Maybe you can create an example for others doing the same using the `service` library and submit a PR, or update the README

**Comment by dvaldivia** [comment]
+1 for the example @long1eu
