### ISSUE TITLE
Wrong link to grpc quickstart

### ISSUE THREAD

**Issue by manideepl** [grpc/grpc-dart#309]
In the **Usage** section of the package's [pub.dev](https://pub.dev/packages/grpc) page,
the quickstart link wrongly points to https://grpc.io/docs/languages/dart.html/quickstart.

Rather, it should point to https://grpc.io/docs/languages/dart/quickstart/.

**Comment by JarrodCColburn** [comment]
@manideepl 
I think this must have been fixed already. Just checked the pub.dev and the READE.md from which it was generated and it's got the link https://grpc.io/docs/quickstart/dart which works (reroutes to https://grpc.io/docs/languages/dart.html/quickstart). 
So I think you can close this ticket.

**Comment by manideepl** [comment]
Yes, it seems fixed now
