### ISSUE TITLE
int32 negative value turn into highest value int32 = 4294967295 on nodejs client

### ISSUE THREAD

**Issue by u007** [grpc/grpc-dart#313]
when i used nodejs library to retrieve int32 field from dart server,
negative value turn into highest value int32 = 4294967295.

Reproduction steps
create a dart grpc server , and send a field with type int32 with value -1 or -16

**Client Environment**
OS name, version and architecture: Ubuntu 18.04
Node version v12.9.1
Node installation method nvm
If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
Package name and version grpc 1.24.2

**Dart server environment:**
my dart running on:
Dart VM version: 2.8.2 (stable)
compiled via dart2native on Ubuntu 20.04 LTS
Package: GRPC 2.0.3

ive filed a bug here for nodejs, because i do not know if this is server or client issue.

https://github.com/grpc/grpc-node/issues/1469

**Comment by mraleph** [comment]
This is a bug in the protobuf implementation. I have discovered that we have never published a version of the protobuf package which contains the fix. I am going to publish it now.

**Comment by mraleph** [comment]
Protobuf package with fixes have been published.
