### ISSUE TITLE
increasing concurrent request handling

### ISSUE THREAD

**Issue by u007** [grpc/grpc-dart#314]
i have grpc services written in dart server, but each call to the service may take up to few minutes to call. i realised during the process, it is unable to process other requests or limited to certain amount of concurrent client at one time. i could separate the process into multiple ports, but i think this will limit my instances based on number of ports i need to setup. is there a way to only spawn 1 server and able to handle many more clients at one time? how do i optimise it to handle many more clients concurrently?

<version of the grpc-dart packages used; see your `pubspec.lock` file>
using dart2native Dart VM version: 2.8.2 (stable) (Unknown timestamp) on "linux_x64"
grpc 1.24.2

## Repro steps

1. create a service with long running stream, maybe 17k stream of message
1. spawn multiple client concurrently and calling server
1. nodejs client connection timeout on some client with 14 UNAVAILABLE: failed to connect to all addresses

Expected result: need a way to handle more concurrent clients

Actual result:  some clients encounter 14 UNAVAILABLE

**Comment by sigurdm** [comment]
https://github.com/grpc/grpc-dart/pull/253 added support for a shared socket.

Read more about the shared argument here: https://api.dart.dev/stable/2.8.4/dart-io/ServerSocket/bind.html

Then it should be possible to have several Isolates serving the same port, thus running concurrently.
