### ISSUE TITLE
Missing trailers

### ISSUE THREAD

**Issue by long1eu** [grpc/grpc-dart#318]
We are still getting `Missing trailers` error even on version 2.2.0. Our server is hosted in Cloud Run, so only unary calls.

**Comment by sessfeld** [comment]
We're facing the same issue. For context, we have clients in several other languages and they are not having that issue. @long1eu, was there a version that worked for you?

**Comment by long1eu** [comment]
@sessfeld actually there is not a specific version at witch it work. We ended up forking and removed that line that thrower.

**Comment by sessfeld** [comment]
As a quick followup: It turned out it was one point in our service routing where the trailers were lost.

**Comment by long1eu** [comment]
@sessfeld can you be a bit more specific? We are using Cloud run and Google Endpoints.

**Comment by sessfeld** [comment]
I'm not sure how it is for endpoints/cloud run, in our case, global HTTPS load balancer was not connecting to our k8s ingress with http2/https. You should make sure that the connection from endpoints to cloud run uses http2/https.

**Comment by mit-mit** [comment]
@long1eu can you provide some more details on what you patched in your fork?

**Comment by long1eu** [comment]
Unfortunately we just removed the check for trailers. So nothing fixed. But we have Google Endpoints in front of our Cloud Run service so might be that empty trailers are not passed.

**Comment by mraleph** [comment]
Unfortunately I don't think we can make much progress without a reproduction.

**Comment by mraleph** [comment]
gRPC specifications does not actually permit missing trailers, for either gRPC or gRPC-web (it is not clear from your report which version you are using). See `Response` grammar in the gRPC spec [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses) and **message framing** section [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md#protocol-differences-vs-grpc-over-http2). If you are seeing this error then something is wrong with your gRPC server or proxies which you hit on the way to it. 

As I have said in the comment above we can't really figure what exactly is wrong without a reproduction, so I am going to close this issue.
