### ISSUE TITLE
Can't use with Flutter because of crypto constraint

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-dart#321]
Excerpt from the [current `pubspec.yaml`](https://github.com/grpc/grpc-dart/blob/master/pubspec.yaml#L14):

```yaml
dependencies:
  crypto: ^2.1.5
```

When I try to use `grpc-dart ^2.2.0` in a simple Flutter client app (using Flutter@[stable v1.17.5](https://github.com/flutter/flutter/releases/tag/1.17.5)), I get the following dependency error:

```nocode
Running "flutter pub get" in myapp...                           
Because every version of flutter_test from sdk depends on crypto 2.1.4 and grpc 2.2.0 depends on crypto ^2.1.5, flutter_test from sdk is incompatible with grpc 2.2.0.
```

From the [crypto Changelog](https://pub.dev/packages/crypto#-changelog-tab-) we can read:

> ## 2.1.5 
> - Improve example and package description to address package site maintenance suggestions.
> ## 2.1.4 
> - BugFix: ...

Given that v2.1.5 only updated descriptions, **is there any reason not to depend on crypto ^2.1.4 instead?**

> Note: There is of course a workaround: to use a dependency override in my app, but I'd rather avoid that if possible especially since I'm putting this together for use in a simple tutorial.

**Comment by wayne-li2** [comment]
As a workaround, can you write your tutorial in grpc 2.1.3?

**Comment by wayne-li2** [comment]
Otherwise, on flutter beta channel, flutter_test is compatible with crypto 2.1.5

**Comment by BstevensG4G** [comment]
I'm a beginner trying to use the grpc package, are the instructions for installing different or is package using lower cryto version?

**Comment by wayne-li2** [comment]
@BstevensG4G This grpc package has dependencies crypto ^2.1.5, which means the version must be equal or higher than v2.1.5, and less than v2.2.0

Flutter stable currently has a hard dependency on crypto 2.1.4, which means you must use crypto v2.1.4

Therefore if you try to use grpc with Flutter together, you won't be able to fully resolve dependencies.

As a workaround, you can bump the grpc version down to a previous version, which depended on crypto 2.1.4, or you may use the flutter beta channel, which has upgraded crypto to 2.1.5. Your choice!

**Comment by BstevensG4G** [comment]
@wayne-li2 thank you, I used grpc version 2.1.3 and it is working. Takes a bit I've noticed sometimes! I tried changing pubspec.yaml and pubspec.lock to crypto 2.1.5 didn't help. Thank you though appreciate the help got grpc 2.1.3 working now!

**Comment by BstevensG4G** [comment]
@wayne-li2 btw, any recommendations on where to ask this question most of the examples are server and client related so I get a bit confused trying them? I'm trying to get a rpc client response from "upcdatabase.com" . similar to this python script
from xmlrpclib import ServerProxy, Error

rpc_key = 'myKeyNumber'

if __name__=='__main__':
    if len(sys.argv) != 2:
        print 'Usage: fetchupc.py <upc>'
        exit
    else:
        s = ServerProxy('https://www.upcdatabase.com/xmlrpc')
        params = { 'rpc_key': rpc_key, 'inputtedUPC': sys.argv[1] }
        print s.lookup(params)

**Comment by BstevensG4G** [comment]
think there were a few leading and ending underscores around name and main

**Comment by BstevensG4G** [comment]
believe lookup is the method call with params (rpc,upc)
