### ISSUE TITLE
Is gRPC Dart alive?

### ISSUE THREAD

**Issue by hasimyerlikaya** [grpc/grpc-dart#340]
Hi,
I am a Flutter developer. I started using Flutter since the beta phase and now I am professionally developing mobile applications for a software company.

After meeting Flutter, we naturally met Dart. When I was a backend developer with a background in C #, when I met Dart, it became a language I loved very much. I think Dart is a very talented and good programming language.

After some research to see if we can develop API applications instead of client applications such as Flutter, I first found the Aquaduct Rest API library. It is really well written and supported by their manufacturers. Later, when I saw that there was gRPC support, I did some research and investigation. I think gRPC is much better than REST APIs and I want to use gRPC in the backend of the applications I will develop.

I can explain how serious I am about this.
I wrote a package that scans proto files and generates Dart codes from them. [proto_builder](https://github.com/EFA-dev/proto_builder)

But there is a problem that this repository is the most critical for us. Frankly, I'm afraid to build our apps on this repository. Too many issues were opened, but they were not even answered properly. Critical errors have been reported, but no one is interested. As someone who loves darts very much and believes that he will come to a very good point in terms of gRPC and server applications, I would like to ask if it is possible to give us a statement about the road map.

Will Dart continue to support gRPC?
Will this repository continue to be developed?
Is it very inconvenient for us to build our applications on this repository?

If anyone reads, I would like them to inform me on these issues.

Thank you from now.

**Comment by gustav3d** [comment]
Your observations and worries are the same as mine.
My conclusion is that the project needs new people that have both time and passion.
That or there will have to be forks.

**Comment by listepo** [comment]
I guess not, but I think with a very low priority. Maybe @kevmoo and @mit-mit know more details

**Comment by mit-mit** [comment]
Sorry, we've had some personel issues. We're working to see if we can resolve this, please stay tuned. cc @vsmenon

**Comment by hasimyerlikaya** [comment]
@mit-mit Thank you for your response.

**Comment by gustav3d** [comment]
Its been like this for 1 year or so, its not a recent situation :/

**Comment by wayne-li2** [comment]
I'm not sure it's anyone's fault. COVID threw a lot of people awry. Economic uncertainties caused hiring slowdowns. Priorities needed to shift for a lot of companies.

However, I agree that ideally, it would be nice to add some community maintainers to this project.

**Comment by wayne-li2** [comment]
To add on, I'm sure many of us in the community would like to contribute, but seeing PRs go unaddressed for months makes me hesitant to spend time on this codebase to work on it.

At the very least, I am okay with having a maintenance-only roadmap for this project for the timebeing, so that the only requirements are that critical PRs get addressed in a timely fashion.

**Comment by mit-mit** [comment]
@mraleph started working through critical PRs and issues. Please have some patience; we're slowing making this better. Apologies again for the slowness.
