### ISSUE TITLE
Socket throws: Insecure socket connections are disallowed by platform

### ISSUE THREAD

**Issue by soloman817** [grpc/grpc-dart#344]
With the latest flutter master channel, invoke GRPC call will get `SocketException` exception.

GRPC dart package is 2.2.0, the latest one

## Repro steps

first `flutter channel master; flutter upgrade; flutter doctor`:

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-2.0.pre.140, on Mac OS X 10.15.6 19G2021, locale en-GB)
```

I try to launch a GRPC call with:

```dart
  String _host = "mydomain.com";
  int _port = 443;
  ChannelOptions _channelOptions = const ChannelOptions(
    credentials: const ChannelCredentials.secure(),
  );

  ClientChannel _channel;

  ClientChannel get channel {
    if (_channel == null) {
      _channel = ClientChannel(
        _host,
        port: _port,
        options: _channelOptions,
      );
    }
    return _channel;
  }
```

If I run my program, it hangs, but if I debug it with Android Studio, an exception is caught from socket.dart:

![image](https://user-images.githubusercontent.com/3477345/91708080-1858c200-eb81-11ea-9acb-caaf665cc9a4.png)

Here is the change from flutter side: https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android

I followed their instructions and added such network policy for android:

```xml
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">do01.coinic.io</domain>
    </domain-config>
```

Then it works, but if I turn `cleartextTrafficPermitted` to `false`, it still doesn't work. I think I used `ChannelCredentials.secure()`, why I cannot turn off the `cleartextTrafficPermitted`?

Expected result: No exception, I noticed, this new exception is added newly: https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android, I tried that, it works only if I set `cleartextTrafficPermitted` to `true`

Actual result: unexpected exception thrown even I added network policy but keep `cleartextTrafficPermitted` to `false`

**Comment by mit-mit** [comment]
cc @mraleph

**Comment by mraleph** [comment]
@soloman817 the code that is throwing was removed from Dart SDK dart-lang/sdk@5c4bf35a2b9fabd019a20af8c5e3f2ed4bb9dccb, the issue should be resolved if you upgrade your Flutter installation to pick latest changes.
