### ISSUE TITLE
client intercept for adding metadata

### ISSUE THREAD

**Issue by girirajthara** [grpc/grpc-dart#348]
Need of client intercept for adding metadata to a request

grpc:2.2.0

**Comment by mit-mit** [comment]
@girirajthara are you looking for something similar to https://godoc.org/google.golang.org/grpc#UnaryClientInterceptor & https://godoc.org/google.golang.org/grpc#StreamClientInterceptor ?

**Comment by girirajthara** [comment]
Yes I want to use it for adding auth id token to every rpc call, by using client interceptor.

**Comment by wayne-li2** [comment]
Looks like #338 is in-review and should address this case :)

**Comment by mraleph** [comment]
Duplicate of #121

**Comment by zbigniew-mandziejewicz-3r** [comment]
@girirajthara You can use `MetadataProvider`, it is specified in `CallOptions` that you can pass to `Client`.

**Comment by yingshaoxo** [comment]
Can any one tell me how exactly I can use intercept with this package?

I simply want to interact with a rust grpc service, it has the interceptor in it.

https://github.com/hyperium/tonic/blob/master/examples/src/interceptor/server.rs
