### ISSUE TITLE
404 errors when making grpc-web requests via Envoy proxy

### ISSUE THREAD

**Issue by smnz** [grpc/grpc-dart#356]
I'm attempting to build a Flutter app with gRPC support for mobile/desktop, and fallback to grpc-web for online, including server streaming support for unidirectional messages (that will presumably be base64 encoded in that case). I'm using Envoy gRPC bridge support. The native http/2 gRPC works fine, but via the http/1.1 bridge it gives a 404 error (although the paths are correct). I have produced a minimal example that reproduces the problem.

I have tested with dependencies:
  - protobuf: ^1.0.1
  - grpc: ^2.2.0

I'm also having the same problem testing now with latest grpc-dart from repo. Relevant pubspec.lock versions are:
  - protobuf 1.0.1
  - grpc: 2.2.0+1
  - http: 0.12.2

## Repro steps

1. Set up envoy-grpc bridged sample app at https://github.com/envoyproxy/envoy/tree/master/examples/grpc-bridge. This is a minimal key/value server that also runs a gRPC bridge with client and server. Steps as per their readme are essentially:
    1. Generate protobuf:
        ```docker-compose -f docker-compose-protos.yaml up --remove-orphans```
    1. Build and run sample app/bridges:
        ```docker-compose up --build```
    1. Check it works with sample client/server:
        ```docker-compose exec grpc-client /client/grpc-kv-client.py set foo bar```
        As expected, the Envoy and app logs show (response code 200):
```
grpc-server-proxy_1  | [2020-09-21T03:29:29.047Z] "POST /kv.KV/Set HTTP/1.1" 200 - 15 7 0 0 "172.22.0.5" "python-requests/2.24.0" "917cc95e-dbd3-489d-80ec-02ea00f89121" "grpc" "172.22.0.2:8081"
grpc-server_1        | 2020/09/21 03:29:29 set: foo = bar
```

2. Create dart version of the proto file:

```
protoc -I protos/ protos/kv.proto --dart_out=grpc:lib/src/generated
```

3. Build simple flutter app:

```
import 'package:flutter/material.dart';
import 'package:grpc/grpc_web.dart';
import 'package:kvtest/generated/kv.pbgrpc.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'KV Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _responseText = 'No response yet';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('KV Test'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            RaisedButton(onPressed: () => setValue(), child: Text('Set Value')),
            Text(
              _responseText,
            ),
          ],
        ),
      ),
    );
  }

  getRPCChannel() {
    final channel =
        GrpcWebClientChannel.xhr(Uri.parse('http://54.1.1.1:8811'));
    return KVClient(channel);

    /// The below works on a native (non-web) platform, talking directly to grpc
//    final channel = ClientChannel(
//      '54.1.1.1',
//      port: 8081,
//      options: const ChannelOptions(credentials: ChannelCredentials.insecure()),
//    );
//    return KVClient(channel);
  }

  setValue() async {
    setState(() {
      _responseText = 'Sending...';
    });
    final client = getRPCChannel();
    try {
      SetResponse response = await client.set(SetRequest()
        ..key = 'foo'
        ..value = 'bar');
      setState(() {
        _responseText = 'Response ${response.ok}';
      });
    } catch (e) {
      setState(() {
        _responseText = 'Exception ${e}';
      });
    }
  }
}
```

Expected result: This should say "Reponse true" and the server should set the value for key `foo` to `bar`.

Actual result: An exception is thrown locally:

```gRPC Error (14, XhrConnection status 0)``` (for repo HEAD)

```gRPC Error (14, XhrConnection connection-error)``` (for grpc 2.2.0)

The request is reaching the gRPC bridge, with the correct path (same as when it worked in the example above), but the Envoy logs are showing it was an OPTIONS request and returns a 404 error:

```
grpc-server-proxy_1  | [2020-09-21T03:37:02.860Z] "OPTIONS /kv.KV/Set HTTP/1.1" 404 NR 0 0 0 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "b6d7c9aa-9232-4785-aca7-25aced376cb2" "54.1.1.1:8811" "-"
```

My full app (working with native gRPC) has the same behaviour, so it's not just the Envoy bridge example that is failing.

## Details

When using the native gRPC support in a native application (using the commented out code in the example instead), then the result comes back true and the logs show success:

```
grpc-server_1        | 2020/09/21 03:41:55 set: foo = bar
```
Also, and I'm not sure this is useful, but if I use the grpc-web from a native app, it also fails but with exception `gRPC Error (14, XhrConnection status 404)` and a different log result:

```
grpc-server-proxy_1  | [2020-09-21T03:44:25.999Z] "POST /kv.KV/Set HTTP/1.1" 404 NR 0 0 0 - "-" "Dart/2.10 (dart:io)" "cff2cd16-212b-449e-873c-f72f4e148f0d" "54.1.1.1:8811" "-"
```

The difference is it's doing a POST rather than OPTIONS, which is more what I'd expect, but still gets a 404.

It initially seems like the problem is with the Envoy config, but the sample app is working so I think the problem is something to do with how grpc-web is talking to the bridge.

Any help appreciated, especially if you can point out where I've done a dumb or how I can resolve the issue.

**Comment by smnz** [comment]
In the meantime while I was trying to solve this problem, I also tried with the nginx proxy, and it's working fine with that. But it seems the nginx proxy doesn't support server streaming, so it doesn't help me much.

I've done some additional delving and here are some raw requests that are quite informative:

Request for original working Envoy example:
```
POST /kv.KV/Set HTTP/1.1
host: grpc
accept-encoding: gzip, deflate
accept: */*
user-agent: python-requests/2.24.0
content-type: application/grpc
content-length: 15
x-forwarded-for: 172.22.0.4
x-forwarded-proto: http
x-envoy-internal: true
x-envoy-downstream-service-cluster: 
x-request-id: 271187d5-7ae6-4127-b50c-885c1de75e75
x-envoy-expected-rq-timeout-ms: 15000

...
```

Request for non-functional dart grpc-web example (not working and returns 404 error):
```
POST /kv.KV/Set HTTP/1.1
host: grpc
user-agent: Dart/2.10 (dart:io)
x-grpc-web: 1
x-user-agent: grpc-web-dart/0.1
accept-encoding: gzip
content-length: 15
content-type: application/grpc-web-text

...
```

After some manual tweaking, I can see that the 404 error occurs when content-type is `application/grpc-web-text` but it works okay when it's `application/grpc`. 

As far as I can tell from https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md, what grpc-dart (and grpc-web) are sending (ie `grpc-web-text`) is actually correct for a base64 response. It kind of looks like the Envoy example is sending the wrong header, and breaking when it gets the right one. Or perhaps it's a configuration issue?

According to that document, the client should also be specifying
```
Accept: application/grpc-web-text
```
which is not happening currently in grpc-dart. But I have tried that, and it still returns 404 if that's present.

I'm puzzled then how other people are managing to use Envoy successfully for streaming. Something somewhere along the chain of parts seems to be mismatched, unless I'm missing something (?).

I'm beginning to think now the problem, if there is one, could be downstream of grpc-dart, but it would be useful to hear if the current Envoy still works for people or if I need to use an old build, or something?

One other thing I note (when I have it working with nginx, for example), is that there are quite a lot of wasted round trips with OPTIONS requests that seem redundant and slow. But that's a separate problem I guess.

**Comment by smnz** [comment]
I think perhaps the problem is with grpc-web. The POST being sent out is still binary encoded proto bufs, so the content type probably shouldn't be `application/grpc-web-text`. It's the response coming back that should be that. But there should be an `Accept: application/grpc-web-text` header probably.

**Comment by mraleph** [comment]
This is an envoy proxy configuration issue. Notice that [README.md](https://github.com/envoyproxy/envoy/blob/master/examples/grpc-bridge/README.md#grpc-http11-to-http2-bridge) describes it as a "gRPC HTTP/1.1 to HTTP/2 bridge", not gRPC-web to gRPC bridge. If you update proxy configuration based on gRPC [documentation](https://grpc.io/docs/languages/web/basics/#configure-the-envoy-proxy), then things will start working. 

<details><summary>patch</summary>

```diff
diff --git a/examples/grpc-bridge/docker-compose.yaml b/examples/grpc-bridge/docker-compose.yaml
index 3ffaa5844..605463d40 100644
--- a/examples/grpc-bridge/docker-compose.yaml
+++ b/examples/grpc-bridge/docker-compose.yaml
@@ -31,32 +31,5 @@ services:
       - "8811:8811"
       - "8881:8881"

-  # Requires the build of the stubs first
-  grpc-client:
-    image: envoyproxy/example-kv-client
-    build:
-      context: client
-    environment:
-      - CLIENT_PROXY=http://kv-client-proxy:9911
-    networks:
-      envoymesh:
-        aliases:
-          - grpc-client
-
-  grpc-client-proxy:
-    build:
-      context: .
-      dockerfile: Dockerfile-client
-    networks:
-      envoymesh:
-        aliases:
-          - kv-client-proxy
-    expose:
-      - "9911"
-      - "9991"
-    ports:
-      - "9911:9911"
-      - "9991:9991"
-
 networks:
   envoymesh: {}
diff --git a/examples/grpc-bridge/server/envoy-proxy.yaml b/examples/grpc-bridge/server/envoy-proxy.yaml
index 2d6075e0b..b8231d87b 100644
--- a/examples/grpc-bridge/server/envoy-proxy.yaml
+++ b/examples/grpc-bridge/server/envoy-proxy.yaml
@@ -1,14 +1,12 @@
 static_resources:
   listeners:
-  - address:
-      socket_address:
-        address: 0.0.0.0
-        port_value: 8811
+  - name: listener_0
+    address:
+      socket_address: { address: 0.0.0.0, port_value: 8811 }
     filter_chains:
     - filters:
-      - name: envoy.filters.network.http_connection_manager
-        typed_config:
-          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
+      - name: envoy.http_connection_manager
+        config:
           codec_type: auto
           stat_prefix: ingress_http
           access_log:
@@ -20,33 +18,20 @@ static_resources:
             name: local_route
             virtual_hosts:
             - name: backend
-              domains:
-              - "*"
+              domains: ["*"]
               routes:
-              - match:
-                  prefix: "/"
-                  grpc: {}
-                route:
-                  cluster: backend_grpc_service
+              - match: { prefix: "/" }
+                route: { cluster: backend_grpc_service }
           http_filters:
-          - name: envoy.filters.http.router
-            typed_config: {}
+          - name: envoy.grpc_web
+          - name: envoy.router
   clusters:
   - name: backend_grpc_service
-    connect_timeout: 0.250s
-    type: strict_dns
-    lb_policy: round_robin
+    connect_timeout: 0.25s
+    type: logical_dns
     http2_protocol_options: {}
-    load_assignment:
-      cluster_name: backend_grpc_service
-      endpoints:
-      - lb_endpoints:
-        - endpoint:
-            address:
-              socket_address:
-                address: kv-backend-service
-                port_value: 8081
-
+    lb_policy: round_robin
+    hosts: [{ socket_address: { address: kv-backend-service, port_value: 8081 }}]
 admin:
   access_log_path: "/tmp/admin_access.log"
   address:
```
</details>

**Comment by smnz** [comment]
Oh yes, that's a rather important distinction I missed. Thanks. I hope this helps anyone else that makes the same mistake I made.
