### ISSUE TITLE
How to use the new protoc genereted files?

### ISSUE THREAD

**Issue by LeandroMoura3** [grpc/grpc-dart#362]
Hello,

I was follow the tutorial and have problem same as that issue: https://github.com/grpc/grpc-dart/issues/297

So, how I use that new version of file generated?

I can't found the "client" class to instance. And have a "ClientContext" that I don't know how to create.

Thanks.

**Comment by mraleph** [comment]
When asking questions please provide as much context as possible, otherwise it is impossible to help you. 

> I was follow the tutorial

Which tutorial (link)? Which step are you at in the tutorial? 

> So, how I use that new version of file generated?

Which file? Use where?

> I can't found the "client" class to instance. And have a "ClientContext" that I don't know how to create.

There is no `ClientContext` in Dart gRPC. Such thing is not even mentioned in the tutorial for Dart. Client setup is described [here](https://grpc.io/docs/languages/dart/basics/#client) in the tutorial.

**Comment by LeandroMoura3** [comment]
Sorry for the incomplete issue.

So, the tutorial that I follow is it that you mentioned in your answer.

The "new" and "old" files are mentioned by issue that I mentioned, I will re-write here:

Old files:
```
helloworld.pb.dart
helloworld.pbenum.dart
helloworld.pbgrpc.dart
helloworld.pbjson.dart
```

New files:
```
helloworld.pb.dart
helloworld.pbenum.dart
helloworld.pbjson.dart
helloworld.pbserver.dart

```
In this tutorial that you say, is generated the "old files", but here, in my protoc, as generated the "new files".

In the old file pbgrpc has the "client" that as mentioned in the tutorial that you mentioned in there command:
```
stub = RouteGuideClient(channel, options: CallOptions(timeout: Duration(seconds: 30)));
```
But in new files "pbserver" don't have that client, and I don't found it in any other files.

This ClientContext mentioned by me is a try to understand how to use this new pattern of files. There can be found in calls of the pbserver and pb files of that new generated files.

**Comment by mraleph** [comment]
Make sure that you use exactly the same `protoc` command that is provided in the tutorial. Seeing that you have `.pbserver.` generated means that you are missing `grpc:` in your `--dart_out=` flag value.

Tutorial instructs you to execute: 

```shell
$ protoc --dart_out=grpc:lib/src/generated -Iprotos protos/helloworld.proto
#                   ^^^^^ don't miss this part
```

I have made a PR for samples to highlight the importance of this part of the command line.

**Comment by LeandroMoura3** [comment]
Thank you.

I readed that message, but I thinked that is a old interface.

A mistake of mine. I get the correct files now.
