### ISSUE TITLE
stream.first doesn't properly close the stream

### ISSUE THREAD

**Issue by enyo** [grpc/grpc-dart#368]
I have created a service that returns a stream. I wrote a very simple client that consumes this stream which looks like this:

```dart
  try {
    final stream = projectClient.list(Empty());
    await stream.first;
    // await stream.cancel();
  } catch (e) {
    print('Error: $e');
  } finally {
    await channel.shutdown();
  }
```

This script will hang at the `channel.shutdown()` command because the `projectClient.list()` stream is still open.

If I uncomment the `await stream.cancel();` line it works as expected.

Interestingly, the server gets a `canceled` event properly, and aborts the call as expected.

`Dart 2.10.0`

**Comment by mraleph** [comment]
I think this should fix it: 

```diff
diff --git a/lib/src/client/call.dart b/lib/src/client/call.dart
index b30eb88..9c0a20e 100644
--- a/lib/src/client/call.dart
+++ b/lib/src/client/call.dart
@@ -198,7 +198,7 @@ class ClientCall<Q, R> implements Response {
       }
       _responses.onPause = _responseSubscription.pause;
       _responses.onResume = _responseSubscription.resume;
-      _responses.onCancel = _responseSubscription.cancel;
+      _responses.onCancel = cancel;
     }
   }
```

Cancelling subscription to the responses stream should be treated as call cancellation (rather than just a cancellation of the underlying subscriptions to transport stream.

I will make a PR later today.
