### ISSUE TITLE
[flutter] RPC Call never complete

### ISSUE THREAD

**Issue by raveltan** [grpc/grpc-dart#373]
## Decription

Flutter
when awaiting for an rpc call the future never finish.

version 2.3.0

## Repro steps

1. call a rpc, 
2. await for the data result
3. the future never complete

Expected result: Future complete and return the result

Actual result: Future never complete 

## Details
The future only completes if the client channel is shutdown premateurely.

```dart
 final c = ClientChannel(
                '127.0.0.1',
                port: 5050,
                options: const ChannelOptions(
                  credentials: ChannelCredentials.insecure(),
                  idleTimeout: Duration(minutes: 1),
                ),
              );
              var mc = MovieServiceClient(c);

              print("get data");
              mc.getMovieList(GetMovieListRequest()).then((x)async {
                print(x);
                print('done');
                await c.shutdown();
              });
```

**Comment by mraleph** [comment]
You would need to provide a minimal runnable repro and include information about which gRPC server you use, etc. 

Testing with something like https://github.com/grpc/grpc-dart/tree/master/example/helloworld does not reveal such behaviour - so there might be something wrong with your setup.

**Comment by raveltan** [comment]
After downgrading the version of async package, the problem disappear.

But i'm not sure how they are related as with the lastest async package even though the future never resolve, there was no error message

**Comment by chounry** [comment]
> After downgrading the version of async package, the problem disappear.
> 
> But i'm not sure how they are related as with the lastest async package even though the future never resolve, there was no error message

async package on your project or on the grpc package?

**Comment by raveltan** [comment]
> > After downgrading the version of async package, the problem disappear.
> > But i'm not sure how they are related as with the lastest async package even though the future never resolve, there was no error message
> 
> async package on your project or on the grpc package?

The async package on my project

**Comment by chounry** [comment]
@raveltan can u tell what the version u are using?

**Comment by mraleph** [comment]
Given that there was no information provided to reproduce the issue I am going to close this issue. I have tried reproducing this (including using  2.5.0-nullsafety.1 async package) and so far I was not successful.
