### ISSUE TITLE
Is there a reason for not having a tag for all version changes

### ISSUE THREAD

**Issue by long1eu** [grpc/grpc-dart#379]
In the change log file there are versions that are not published on pub, which is not a problem, but why doesn't they al least have a git tag. I have an issue with grpc that doesn't manifest in 2.3.0 but it does in 2.7.0. I can't actually see what version introduced the issue.

**Comment by mraleph** [comment]
We have not been consistently tagging releases (or even publishing them). We will try to do it more consistently going forward.

You can just bisect commits - you should not need tags for that.

**Comment by long1eu** [comment]
Thanks. Using tags would make it easier.
