### ISSUE TITLE
Cannot catch SocketException thrown when sending GRPC request

### ISSUE THREAD

**Issue by engelen** [grpc/grpc-dart#396]
When my GRPC server is unavailable, a `SocketException` is thrown in the `http2_connection.dart` file when I make a GRPC call; I appear to be unable to catch the error.

grpc-dart: 2.7.0

## Repro steps
1. Start the GRPC server
1. Open a client channel
1. Start a client
1. Stop the GRPC server
1. Run a GRPC call

```dart
import 'package:grpc/grpc.dart';

import 'package:mypackage/api/v1/myservice.pbgrpc.dart' as grpc;

var channel = ClientChannel(
  serverIP,
  port: serverPort,
  options: ChannelOptions(
    credentials: ChannelCredentials.insecure(),
    idleTimeout: Duration(seconds: 10),
  ),
);

var client = grpc.MyClient(channel);

client.myCall().then((response) {
  print('success');
}, onError: (error) {
  print('onError');
}).catchError((error) {
  print('catchError');
});
```

Expected result: printing 'onError'

Actual result:
```
Exception has occurred.
SocketException (SocketException: OS Error: Connection refused, errno = 111, address = 10.0.2.2, port = 43316)
```
on this line:
https://github.com/grpc/grpc-dart/blob/5b3a125914d30d430abbd7061a3376f94ad0752c/lib/src/client/http2_connection.dart#L311

Thanks for your help!

**Comment by mraleph** [comment]
I don't seem to be able to reproduce this. I see error correctly propagate. I have tried reproducing this using `helloworld` example doing two different things: 

- Run client without server. Got 
  ```
  Caught error: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 62017, details: null)
  ```
- Add loop repeating the call every 10s and killed server after the first successful call. Got 

  ```
  Greeter client received: Hello, world!
  Caught error: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 62066, details: null)
  ```

Could you provide the full runnable reproduction for the problem?

**Comment by engelen** [comment]
@mraleph Thanks a lot for your help. I'm sorry for not responding earlier; it turns out I had email notifications turned off.

I've downloaded the hello world example and tried to reproduce it, and it turns out the issue does not occur when I run dart from the command line directly, but it _does occur_ when I run dart using VS code. If I untick the checkbox "Uncaught Exceptions" in the "Breakpoints" settings screen, the problem does not occur anymore, and the error is nicely caught. (if the checkbox _is_ ticked, I get the problem I described in the issue description)

It seems like VS Code is marking this as an "Uncaught exception", although it is clearly caught. Could this issue be due to the way grpc-dart handles errors, or should I contact VS Code?

**Comment by engelen** [comment]
It looks a problem in VS Code / Dart itself:
https://github.com/flutter/flutter/issues/33427
https://github.com/Dart-Code/Dart-Code/issues/2063

**Comment by mraleph** [comment]
Thanks for the context! I would imagine that even when "Uncaught Exceptions" check box is ticked you should be able to resume execution - after which exception should be caught in the right place.

I have pinged https://github.com/dart-lang/sdk/issues/37953 (which is the upstream Dart bug tracking improvements in "pause on unhandled exceptions" functionality). Let's see what we can do about it.

**Comment by engelen** [comment]
Excellent, thanks a lot!
