### ISSUE TITLE
Socket.connect Attempts Only Once

### ISSUE THREAD

**Issue by nixzee** [grpc/grpc-dart#403]
Hello, I am developing a mobile application that communicates over spotty Wi-Fi to a Go server on-prem. At the moment the the mobile app has a single button that makes a hello world request to the Go server. If there is a "hiccup" in the connection to the server while performing the request, the RPC will timeout but it looks like the Socket.connect() in the http2_connection.dart @ Line 311 is still in play for two minutes. It seems that even if the server does come back up, the Socket.connect() will stay blocked for the full two minutes. In short, it will only attempt to connect once. Also, once the connect operation finishes and the server is up, the next attempt will automatically work.

I can easily recreate this by running both the Go and Dart code locally. If the server is stopped during a request and brought up while the request is in play, the socket.Connect() will remained blocked for the full two minutes.

I am maintaing the channel as a singleton instance to avoid recreation.

Is this expected behavior? I would assume if the connect operation is running while the server is up, it should connect. If need be, I can provide sanitized code.

  grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.0"

## Repro steps

1. Start a Go server and Dart/Flutter client using the gRPC "Greeter" protos found  at https://grpc.io/docs/languages/dart/quickstart/ bought with the client channel as a singleton that is not shutdown after each call and check functionality.
2. Stop the Go Server and fire the HelloRequest. Wait a few seconds and then start the Go server.
3. The Socket.Connect() will throw an exception 2 minutes later (even with the Go server running).

Expected result: The Socket.Connected() should connect withing the default timeout when the server is running.

Actual result: The Socket.Connect() will timeout after two minutes (even with the server running) and will work fine on the next call.

**Comment by mraleph** [comment]
Given the symptoms (your say `Socket.connect` hangs until timeout is reached) I don't think this has anything to do with gRPC, connection seems to be hanging in the networking stack. Not much we can do about that.
