### ISSUE TITLE
Breaking: `dart:html` not found

### ISSUE THREAD

**Issue by edTheGuy00** [grpc/grpc-dart#405]
I updated my project to use `2.8.0` And couldn't get it to run, I had to downgrade back to `2.2.0` and `protoc_plugin` to `19.1.0` 

I was getting the following errors, might I have missed something? 

```
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:17:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:40:9: Error: Type 'HttpRequest' not found.
  final HttpRequest _request;
        ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:168:27: Error: Type 'HttpRequest' not found.
  void _initializeRequest(HttpRequest request, Map<String, String> metadata) {
                          ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:178:3: Error: Type 'HttpRequest' not found.
  HttpRequest createHttpRequest() => HttpRequest();
  ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:40:9: Error: 'HttpRequest' isn't a type.
  final HttpRequest _request;
        ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:66:14: Error: Getter not found: 'HttpRequest'.
        case HttpRequest.HEADERS_RECEIVED:
             ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:69:14: Error: Getter not found: 'HttpRequest'.
        case HttpRequest.DONE:
             ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:82:30: Error: 'ProgressEvent' isn't a type.
    _request.onError.listen((ProgressEvent event) {
                             ^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:168:27: Error: 'HttpRequest' isn't a type.
  void _initializeRequest(HttpRequest request, Map<String, String> metadata) {
                          ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:178:38: Error: The method 'HttpRequest' isn't defined for the class 'XhrClientConnection'.
 - 'XhrClientConnection' is from 'package:grpc/src/client/transport/xhr_transport.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
  HttpRequest createHttpRequest() => HttpRequest();
                                     ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.8.0/lib/src/client/transport/xhr_transport.dart:197:11: Error: 'HttpRequest' isn't a type.
    final HttpRequest request = createHttpRequest();
          ^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:657:37)
<asynchronous suspension>
#2      writeDepfile (package:vm/kernel_front_end.dart:825:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:583:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
#5      starter (package:flutter_frontend_server/server.dart:180:27)
#6      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


Target kernel_snapshot failed: Exception
Failed to build bundle.

```

**Comment by mraleph** [comment]
It seems that you are importing `package:grpc/grpc_web.dart` in a native Flutter application. We currently don't support using gRPC-Web in native applications e.g. Flutter (not Flutter Web) apps. From those applications you should use native gRPC protocol. 

We used to briefly support that, but patch that introduced support for it was reverted. If this is for some reason important for you let us know on https://github.com/grpc/grpc-dart/issues/216 (though it is unlikely that we get to implement it ourselves any time soon).

**Comment by kaysman** [comment]
Having this issue with `grpc:3.0.0` and `grpc:3.0.2`. How did you manage to solve it? Please note that we use `grpc` in android & ios apps, NOT web.

Here is error:
`
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:17:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:40:9: Error: Type 'HttpRequest' not found.
  final HttpRequest _request;
        ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:174:27: Error: Type 'HttpRequest' not found.
  void _initializeRequest(HttpRequest request, Map<String, String> metadata) {
                          ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:184:3: Error: Type 'HttpRequest' not found.
  HttpRequest createHttpRequest() => HttpRequest();
  ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:40:9: Error: 'HttpRequest' isn't a type.
  final HttpRequest _request;
        ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:67:14: Error: Undefined name 'HttpRequest'.
        case HttpRequest.HEADERS_RECEIVED:
             ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:70:14: Error: Undefined name 'HttpRequest'.
        case HttpRequest.DONE:
             ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:77:30: Error: 'ProgressEvent' isn't a type.
    _request.onError.listen((ProgressEvent event) {
                             ^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:174:27: Error: 'HttpRequest' isn't a type.
  void _initializeRequest(HttpRequest request, Map<String, String> metadata) {
                          ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart:184:38: Error: The method 'HttpRequest' isn't defined for the class 'XhrClientConnection'.
 - 'XhrClientConnection' is from 'package:grpc/src/client/transport/xhr_transport.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.0/lib/src/client/transport/xhr_transport.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
  HttpRequest createHttpRequest() => HttpRequest();
                                     ^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:625:9)
<asynchronous suspension>
#4      starter (package:frontend_server/frontend_server.dart:1451:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
<asynchronous suspension>



FAILURE: Build failed with an exception.

`

Here is my `flutter doctor -v`

`
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.3 21E230 darwin-arm, locale en-US)
    • Flutter version 3.3.4 on channel stable at /Users/macbookpro/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (4 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM M315F (mobile) • RZ8N218LL1N • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

`

**Comment by mraleph** [comment]
@kaysman See https://github.com/grpc/grpc-dart/issues/405#issuecomment-733655643 which explains why you are getting the error. tldr version is that you are importing the wrong file somewhere.

**Comment by kaysman** [comment]
@mraleph you were right, I imported `package:grpc/grpc_web.dart` by mistake. Thanks!
