### ISSUE TITLE
Should be able to assign bearer token (e.g. JWT) to channel

### ISSUE THREAD

**Issue by saltatory** [grpc/grpc-dart#406]
I have a Flutter Dart application accessing a .NET server over GRPC. I am authenticating users with Auth0 and receiving a JWT. The JWT does not change during the session.

Once the user logs in and receives the JWT, I want to configure a single Channel with attached credentials. However, that is not available with the current implementation. What I have had to do instead is to implement per-call credentials as follows:

```dart
    final client = MyClient(_channel,
        options: CallOptions(metadata: {'authorization': 'Bearer ${state.token}'}));
```

**Comment by mraleph** [comment]
You can achieve this by implementing your own `ClientChannel` wrapper which delegates to default `ClientChannel` but at the same time augments call options, e.g. 

```dart
import 'package:grpc/service_api.dart' as $grpc;

class ClientChannelWithMetadata implements $grpc.ClientChannel {
  final $grpc.ClientChannel channel;
  final CallOptions options;

  @override
  Future<void> shutdown() => channel.shutdown();

  @override
  Future<void> terminate() => channel.terminate();

  @override
  ClientCall<Q, R> createCall<Q, R>(
      ClientMethod<Q, R> method, Stream<Q> requests, CallOptions options) {
    return channel.createCall<Q, R>(method, requests, this.options.mergedWith(options));        
  }
}
```

I think this does what you want.
