### ISSUE TITLE
How does lint exclude code generated from .proto?

### ISSUE THREAD

**Issue by shuniiiig** [grpc/grpc-dart#410]
When generate dart code from .proto, we got errros like a screenshot below.

<img width="640" alt="screenshot" src="https://user-images.githubusercontent.com/35192891/101456493-7dd5ff00-3977-11eb-92c1-be08d0852d78.png">

we need code completion by IDE and hide errors at same time.
2.8.0

```
analyzer:
  exclude:
    - "lib/data/grpc/**"
```

we write the code above in analysis_options.yaml, so that errors always don't appear.
Additionally, we want to let linter ignore code generated from .proto.

Thank you.

**Comment by mraleph** [comment]
Those errors seem a bit strange. Normally you should not have any errors when analysing generated code. Do you have something like `implicit-cast: false` in your analysis options? This is not really a supported analysis configuration for protobuf generator. (Though when protobuf generator starts generating 2.12 compliant code it would also pass `implicit-casts: false` mode).

Overall I think this is more of a question/issue for `dartanalyzer` (and thus should be filed under https://github.com/dart-lang/sdk repo) than a question for `grpc` package. I am going to close this issue - but feel free to ask more questions.
