### ISSUE TITLE
[client] big message considered corrupt

### ISSUE THREAD

**Issue by ekasetiawans** [grpc/grpc-dart#411]
tried to send a message over 20 MB in size but failed and was considered corrupt.
grpc 2.8.0

the current solution is to change the **DEFAULT_SIZE_LIMIT** in the protobuf repository in `protobuf/lib/src/protobuf/coded_buffer_reader.dart` to 200MB.

**Comment by mraleph** [comment]
Seems like you already filed a protobuf issue, so I will close this one.
