### ISSUE TITLE
how to add interceptor to request such (getTemplate)

### ISSUE THREAD

**Issue by len8657** [grpc/grpc-dart#412]
<short description>

<version of the grpc-dart packages used; see your `pubspec.lock` file>

## Repro steps

///
//  Generated code. Do not modify.
//  source: houseplan.proto
//
// @dart = 2.3
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type

import 'dart:async' as $async;

import 'dart:core' as $core;

import 'package:grpc/service_api.dart' as $grpc;
import 'houseplan.pb.dart' as $0;
export 'houseplan.pb.dart';

class HousePlanServicesClient extends $grpc.Client {
  static final _$getTemplate =
      $grpc.ClientMethod<$0.TemplateRequest, $0.TransactionPlanTemplateData>(
          '/grpcmodel.HousePlanServices/GetTemplate',
          ($0.TemplateRequest value) => value.writeToBuffer(),
          ($core.List<$core.int> value) =>
              $0.TransactionPlanTemplateData.fromBuffer(value));
  static final _$submitHousePlan =
      $grpc.ClientMethod<$0.HousePlan, $0.HousePlanResponse>(
          '/grpcmodel.HousePlanServices/SubmitHousePlan',
          ($0.HousePlan value) => value.writeToBuffer(),
          ($core.List<$core.int> value) =>
              $0.HousePlanResponse.fromBuffer(value));
  static final _$getHousePlan =
      $grpc.ClientMethod<$0.FindHousePlanRequest, $0.FindHousePlanResponse>(
          '/grpcmodel.HousePlanServices/GetHousePlan',
          ($0.FindHousePlanRequest value) => value.writeToBuffer(),
          ($core.List<$core.int> value) =>
              $0.FindHousePlanResponse.fromBuffer(value));
  static final _$housePlanPageable =
      $grpc.ClientMethod<$0.PageableRequest, $0.PageableResponse>(
          '/grpcmodel.HousePlanServices/HousePlanPageable',
          ($0.PageableRequest value) => value.writeToBuffer(),
          ($core.List<$core.int> value) =>
              $0.PageableResponse.fromBuffer(value));

  HousePlanServicesClient($grpc.ClientChannel channel,
      {$grpc.CallOptions options})
      : super(channel, options: options);

  $grpc.ResponseFuture<$0.TransactionPlanTemplateData> getTemplate(
      $0.TemplateRequest request,
      {$grpc.CallOptions options}) {
    final call = $createCall(
        _$getTemplate, $async.Stream.fromIterable([request]),
        options: options);
    return $grpc.ResponseFuture(call);
  }

  $grpc.ResponseFuture<$0.HousePlanResponse> submitHousePlan(
      $0.HousePlan request,
      {$grpc.CallOptions options}) {
    final call = $createCall(
        _$submitHousePlan, $async.Stream.fromIterable([request]),
        options: options);
    return $grpc.ResponseFuture(call);
  }

  $grpc.ResponseFuture<$0.FindHousePlanResponse> getHousePlan(
      $0.FindHousePlanRequest request,
      {$grpc.CallOptions options}) {
    final call = $createCall(
        _$getHousePlan, $async.Stream.fromIterable([request]),
        options: options);
    return $grpc.ResponseFuture(call);
  }

  $grpc.ResponseFuture<$0.PageableResponse> housePlanPageable(
      $0.PageableRequest request,
      {$grpc.CallOptions options}) {
    final call = $createCall(
        _$housePlanPageable, $async.Stream.fromIterable([request]),
        options: options);
    return $grpc.ResponseFuture(call);
  }
}

abstract class HousePlanServicesServiceBase extends $grpc.Service {
  $core.String get $name => 'grpcmodel.HousePlanServices';

  HousePlanServicesServiceBase() {
    $addMethod(
        $grpc.ServiceMethod<$0.TemplateRequest, $0.TransactionPlanTemplateData>(
            'GetTemplate',
            getTemplate_Pre,
            false,
            false,
            ($core.List<$core.int> value) =>
                $0.TemplateRequest.fromBuffer(value),
            ($0.TransactionPlanTemplateData value) => value.writeToBuffer()));
    $addMethod($grpc.ServiceMethod<$0.HousePlan, $0.HousePlanResponse>(
        'SubmitHousePlan',
        submitHousePlan_Pre,
        false,
        false,
        ($core.List<$core.int> value) => $0.HousePlan.fromBuffer(value),
        ($0.HousePlanResponse value) => value.writeToBuffer()));
    $addMethod(
        $grpc.ServiceMethod<$0.FindHousePlanRequest, $0.FindHousePlanResponse>(
            'GetHousePlan',
            getHousePlan_Pre,
            false,
            false,
            ($core.List<$core.int> value) =>
                $0.FindHousePlanRequest.fromBuffer(value),
            ($0.FindHousePlanResponse value) => value.writeToBuffer()));
    $addMethod($grpc.ServiceMethod<$0.PageableRequest, $0.PageableResponse>(
        'HousePlanPageable',
        housePlanPageable_Pre,
        false,
        false,
        ($core.List<$core.int> value) => $0.PageableRequest.fromBuffer(value),
        ($0.PageableResponse value) => value.writeToBuffer()));
  }

  $async.Future<$0.TransactionPlanTemplateData> getTemplate_Pre(
      $grpc.ServiceCall call, $async.Future<$0.TemplateRequest> request) async {
    return getTemplate(call, await request);
  }

  $async.Future<$0.HousePlanResponse> submitHousePlan_Pre(
      $grpc.ServiceCall call, $async.Future<$0.HousePlan> request) async {
    return submitHousePlan(call, await request);
  }

  $async.Future<$0.FindHousePlanResponse> getHousePlan_Pre(
      $grpc.ServiceCall call,
      $async.Future<$0.FindHousePlanRequest> request) async {
    return getHousePlan(call, await request);
  }

  $async.Future<$0.PageableResponse> housePlanPageable_Pre(
      $grpc.ServiceCall call, $async.Future<$0.PageableRequest> request) async {
    return housePlanPageable(call, await request);
  }

  $async.Future<$0.TransactionPlanTemplateData> getTemplate(
      $grpc.ServiceCall call, $0.TemplateRequest request);
  $async.Future<$0.HousePlanResponse> submitHousePlan(
      $grpc.ServiceCall call, $0.HousePlan request);
  $async.Future<$0.FindHousePlanResponse> getHousePlan(
      $grpc.ServiceCall call, $0.FindHousePlanRequest request);
  $async.Future<$0.PageableResponse> housePlanPageable(
      $grpc.ServiceCall call, $0.PageableRequest request);
}

Expected result: <describe what should have happened>

Actual result: <describe what actually happened>

## Details

<Include any other relevant details, logs, etc.>

**Comment by len8657** [comment]
protoc --dart_out=grpc:. houseplan.proto --plugin ~/.pub-cache/bin/protoc-gen-dart  to this code

**Comment by len8657** [comment]
houseplan.proto is a probuffer file

**Comment by mraleph** [comment]
Sorry, could you describe your problem in more details? I can't figure out what you are asking.

**Comment by mraleph** [comment]
I will close the issue until more details are provided.
