### ISSUE TITLE
question: What should be the lifetime of a stub?

### ISSUE THREAD

**Issue by dmayle** [grpc/grpc-dart#416]
Question in the title: What should be the lifetime of a grpc stub (and how does that map to the lifetimes of the underlying resources, like host lookup, TLS/TCP connection, etc.)?

Should I be trying to use a single stub for each host and sharing it around?  Should I create a new stub for each connection?  For each new page transition (in Flutter) ?

Is there any sort of connection pooling mechanism?

Do I have to worry about state if I share a stub?  As en example, if I use an interceptor to inject auth, can I update the state of the interceptor after successful login so that future calls on the stub use auth, or do I have to create a new connection because of ongoing connections?

**Comment by mraleph** [comment]
Connections are managed by `ClientChannel` rather than the stub. There is a single connection and no pooling. 

> As en example, if I use an interceptor to inject auth, can I update the state of the interceptor after successful login so that future calls on the stub use auth, or do I have to create a new connection because of ongoing connections?

That depends on the authentication mechanism. If your authentication mechanism is using per-call metadata for authentication then you can do that.
