### ISSUE TITLE
ChannelOptions::connectionTimeout is not what developers think it is (namely maximum connection establishment duration)

### ISSUE THREAD

**Issue by AndiDog** [grpc/grpc-dart#418]
`connectionTimeout` should mean the maximum time to wait for establishing a connection to the server. As in 99% of other libraries. The existing meaning however is unfortunately "maximum lifetime of a healthy connection" (= when to refresh).

Almost fell for it until I read that the default is 50 minutes, which relates to the very surprising meaning.

grpc-dart 2.8.0

See #5 which also requests connection timeouts as feature.

**Comment by mraleph** [comment]
Yeah, the name is a bit confusing. There is a doc comment on the setting though documenting the semantics. Changing the name now would be a breaking change, so I don't think we want that.
