### ISSUE TITLE
how to setup flutter web https certificate?

### ISSUE THREAD

**Issue by chounry** [grpc/grpc-dart#420]
## Enviroment
- Flutter : 1.24.0-10.2.pre • channel beta
- grpc-dart : 2.8.0

## Description
I setup the channel with this code 
```dart
GrpcWebClientChannel.xhr(Uri.parse('${ssl ? 'https' : 'http'}://$host:$port'));
```

- With the code, I can communicate with **HTTP server**
- The server is already configure to run https
- I have both `.crt` and '.key' file

What are the additional mandatory that I need to make it be able to request the https server?

**Comment by mraleph** [comment]
I am not sure I understand the question: if you just want to communicate with a gRPC server over https then you don't need to do anything beyond using `https` uri, the browser will take care of the rest.

Could you clarify what exactly are you asking?

**Comment by chounry** [comment]
yes, you are right. I am new to the ssl things.
