### ISSUE TITLE
Docs not complete

### ISSUE THREAD

**Issue by steeling** [grpc/grpc-dart#425]
grpc-web docs seem to be incomplete:

https://github.com/grpc/grpc-dart/tree/master/example/grpc-web

Mentions docker-compose, but there are no docker files anywhere

Following the example to run `webdev serve` gets a 404 on `main.dart.js`, so not runnable.

Lastly, when finally finding a way to run both the client and server, it doesn't work. Client requests fail with:

gRPC Error (code: 14, codeName: UNAVAILABLE, message: XhrConnection status 0, details: null)

I'm also getting this in other systems, but not in regular non grpc-web channels.

**Comment by mraleph** [comment]
Docs contain [Prerequisites](https://github.com/grpc/grpc-dart/tree/master/example/grpc-web#prerequistes) section which describe that you need to clone a different repository which contains the server. You are supposed to `docker-compose up echo-server envoy` in the clone of that repo.

> Following the example to run webdev serve gets a 404 on main.dart.js, so not runnable.

That's actually a regression introduced by c48af638a54225fe39200df726440ac7bde4225c, I am going to fix this. Thanks for reporting. 

> Lastly, when finally finding a way to run both the client and server, it doesn't work. Client requests fail with:

Check your setup, your server does not seem to be reachable. I have verified locally that following instructions (e.g. using `docker-compose up echo-server envoy` in `grpc-web` clone to start the server) makes things work.

**Comment by mraleph** [comment]
The issue with `webdev` compilation is now fixed on master.
