### ISSUE TITLE
gRPC Web streaming support

### ISSUE THREAD

**Issue by steeling** [grpc/grpc-dart#426]
Can you elaborate on the support for server side streaming to a grpc-web client? The grpc web readme https://github.com/grpc/grpc-web states that the mode `grpcwebtext` is required, however this term doesn't appear in this repo, nor does it employ a special protoc gen statement to include it

However the example implements a streaming request here https://github.com/grpc/grpc-dart/blob/master/example/grpc-web/protos/echo.proto#L40.

Can you comment?

**Comment by mraleph** [comment]
grpc-web readme talks about that specific implementation of grpc. Our implementation supports streaming.
