### ISSUE TITLE
Expose onStateChanged from Http2ClientConnection

### ISSUE THREAD

**Issue by long1eu** [grpc/grpc-dart#428]
Right now this field is marked as `visibleForTesting`. But it would be awesome to monitor the state of the stream and even expose a `Stream<ConnectionState>`.

**Comment by shekohex** [comment]
Yes, please!
one use case is when the connection is restored we can dequeue the failed/pending requests and send them again.

**Comment by Cobinja** [comment]
This would be great to have on the channel, similar to how it's done in the python implementation (https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py#L1493).

**Comment by Ludonope** [comment]
Any update on that?

It seems pretty essential to be able to know the state of the current connection.
I'm using gRPC for a Flutter app and being able to show the current connection state to the user is an important feature.

**Comment by micheljung** [comment]
Looks like this has been fixed with #565 (3.1.0).
