### ISSUE TITLE
Updating sdk requirement to >= 2.12 has broken grpc/grpc interop test

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc-dart#440]
Hi, over at the grpc/grpc repo, we have interop tests running against this repo. Recently after #432 is merged, we noticed that interop tests involving grpc-dart start failing. Here's an example: https://source.cloud.google.com/results/invocations/e8cb1358-66f2-4607-ae77-63e6ee3aa2fb/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log

Specific error message:
```
SLVR:   fact: every version of grpc from path requires SDK version >=2.12.0-0 <3.0.0
SLVR:   conflict: every version of grpc from path requires SDK version >=2.12.0-0 <3.0.0
SLVR:   ! grpc from path is satisfied by grpc from path
SLVR:   ! which is caused by "interop depends on grpc from path"
SLVR:   ! thus: version solving failed
SLVR: Version solving took 0:00:00.909279 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.922s).
ERR : The current Dart SDK version is 2.10.4.
    |
    | Because interop depends on grpc from path which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
```

I noticed that that's because in the [interop/pubspec.yaml](https://github.com/grpc/grpc-dart/blob/master/interop/pubspec.yaml#L13) file, we are attempting to the load the `grpc` module from the repo's root directory, and in a recent commit, the sdk requirement has been updated to >= 2.12. On the grpc side, we are using the base docker image of `google/dart:2.10`.

I tried updating that docker image to `google/dart:2.12-beta`, but ran into another error:

```
2021-01-29 12:30:30,244 ../lib/src/client/common.dart:64:19: Error: The argument type 'R Function(R?)' can't be assigned to the parameter type 'FutureOr<R> Function(R?)' because 'R' is nullable and 'R' isn't.
            .then(_ensureOneResponse));
                  ^

2021-01-29 12:30:30,244 FAILED: cloud_to_prod:dart:default:empty_unary:tls [ret=254, pid=27507, time=4.2sec]
```

Second attempt: I try to pin the grpc/grpc-dart to the released commit of 2.9.0 (d3f0ec7) before running our interop tests and that seems to have solved the issue (see https://github.com/grpc/grpc/pull/25305).

So my question is which of the following way is a better long term fix?
1. Perhaps in grpc-dart, interop/pubspec.yaml shouldn't be loading the grpc module from `../` which is basically tracking master/head, which may contain unreleased code? 
2. Perhaps grpc/grpc should update to the `google/dart:2.12` image? But we need the error above resolved.
3. Perhaps grpc/grpc should always check out a released version of the grpc-dart repo before running the interop tests?

Please let us know what is a better way going forward. Thanks!

**Comment by iinozemtsev** [comment]
Looking into that, will send a PR to upgrade interop later today
