### ISSUE TITLE
Regenerating files to no longer use super.CopyWith

### ISSUE THREAD

**Issue by MatthewBreeze45** [grpc/grpc-dart#447]
Help wanted. what are the requirements to generate the dart code so that it no longer uses copywith. Seems a little unclear on how to update the files or how to generate the new code  

version: 2.9.0-dev

**Comment by mraleph** [comment]
If you are getting warnings in the files in your project which were generated from protobuf descriptions, you can regenerate this files using the newest version of protobuf compiler. Follow the same approach you used to generated them in the first place.
