### ISSUE TITLE
unclear documentation

### ISSUE THREAD

**Issue by bernaferrari** [grpc/grpc-dart#459]
I was trying to follow the **quickstart documentation**, and this is was the line of logic I followed:

1. Install the protocol compiler for Dart.
2. Update the PATH
3. Change the code as requested
4. In "Regenerate gRPC code", execute `protoc ...`

Error, no `protoc`! Since I was dealing with PATH, I thought something was wrong.. 
But no. I just didn't have protoc installed. And the protoc page that is referred at the beginning of the tutorial doesn't even have how to install, it just sends you to GitHub repository. I had to Google and find [this page](http://google.github.io/proto-lens/installing-protoc.html) where the solution was a simple `brew install protobuf`.

I think you could add that info in that part, like, "hey, don't forget you need protobuf which is not protoc, check here to install" instead of linking to a website that links to the source.

**Comment by mraleph** [comment]
https://grpc.io/docs/languages/dart/quickstart/#prerequisites makes it quite clear that you need `protoc` and links you to installation instructions. 

Were you following some other quick start?

**Comment by bernaferrari** [comment]
It links to a website that has no clear `protoc` install instructions, and the website links to the GitHub repo which is even more unclear.
![image](https://user-images.githubusercontent.com/351125/111545107-4f28ab00-8754-11eb-8f02-be4f547e145d.png)

Having something like `brew install protobuf` there would help a lot of people.
