### ISSUE TITLE
Client can't connect to dotnet example server?

### ISSUE THREAD

**Issue by mhingston** [grpc/grpc-dart#465]
Version: grpc-dart 3.0.0

Hi, I have a .NET core gRPC server implementation based on the [Greeter example](https://github.com/grpc/grpc-dotnet/tree/master/examples/Greeter) in the grpc-dotnet repo. I can connect to this no problem using various gRPC clients, however when I try to connect to the server using a dart-grpc implementation based on the [helloworld example](https://github.com/grpc/grpc-dart/tree/master/example/helloworld) I'm finding [the client](https://github.com/mhingston/grpc-issue/blob/master/helloworld/bin/client.dart) just hangs indefinitely and I can't see what I'm missing. I've also tried taking out the codecs to see if that was causing an issue but the issue remains.

I have a test repro for this issue [here](https://github.com/mhingston/grpc-issue).

Any pointers would be appreciated.

Thanks

**Comment by mraleph** [comment]
This line https://github.com/mhingston/grpc-issue/blob/26ab4b2e17cf1b3e4ee240e198f89de01623a94c/server/Properties/launchSettings.json#L6 seems to indicate to me that your server is using TLS, but the client is configured with `insecure` credentials. You need to configure client using secure credentials mode if you want to talk over HTTPS
