### ISSUE TITLE
Supporting IPv6 DNS64/NAT64 Networks

### ISSUE THREAD

**Issue by gl-ihorkoblan** [grpc/grpc-dart#467]
We have been developing system where phone connects to camera and control it(like start/stop recording video).
client is mobile app(iOS/Android) wrote on Flutter uses GRPC v2.9.0
server is running on camera side.
They are communicating via WIFI

Couple of our clients who uses T-Mobile operator have an issue. The issue is that app can't connect to the camera if cellular data is on. And it connects fine if cellular data is off.

Earlier we had the same issue on our another iOS native app which communicates with camera server via Sockets. We used GCDAsyncSocket framework. So the fix was quite easy we replaced GCDAsyncSocket to AsyncSocket(_Here is what's the difference:
https://stackoverflow.com/questions/38237286/what-different-with-gcdasyncsocket-and-asyncsocket?fbclid=IwAR2qM1NG-K4u7gQPODP3vWIIViCgR2V4GSOvtWUAx_97fxp-uoGgkZWQ2gY_). But we have no alternative for GRPC framework in Flutter.
So as far as I understand there is no supporting DNS64/NAT64. **Please fix!**

Useful info I found:
https://github.com/robbiehanson/CocoaAsyncSocket/issues/429?fbclid=IwAR1pi-b1sP_1xJJKecHU-oqB2TOMTdBM6p3EJ28PO6XI9EHmwJv6_kO3YZI

https://developer.apple.com/forums/thread/77438?fbclid=IwAR0rEiiy_cacZuGT6jHl043OqFWgTFIYoQlrV54VfDAX794UgMy2nBFKpPo

https://developer.apple.com/forums/thread/46941?fbclid=IwAR03mdqJ2KpBG4iCUNDw-TM7NSCc0MIThgju72qX-1Lo1HlFm3tVVeemUjM

**Comment by mraleph** [comment]
It's not really a grpc package issue, by default grpc-dart just uses `dart:io` to establish network connections, so you should file a bug against `dart:io` over at https://github.com/dart-lang/sdk/issues providing as much detail as possible: e.g. WiFi network configuration (is it IPv6 only?) where it fails, what is the IP address assigned to camera? which interfaces does the camera bind to (IPv6/IPv4 or both)? how do you establish connection to the camera (e.g. which IP address do you use, how do you get that IP address?), maybe routing table information from the iOS device, etc. 

If you want a fast workaround then your best bet is to build your own transport - core of the grpc package is transport agnostic, so you can implement your own `ClientChannel` on top of native sockets. All necessary interfaces are exported through lib/grpc_connection_interface.dart
