### ISSUE TITLE
[Question] How to use :authority

### ISSUE THREAD

**Issue by BatanGaming** [grpc/grpc-dart#469]
What do I want to achieve - customize url from `localhost/<service_name>` to `localhost/mobile/<service_name>`

In this issue https://github.com/grpc/grpc-dart/issues/468 I was suggested to use `:authority` header for customizing url. I tried to use it like this:
```
ClientChannel(
  'localhost', 
  port: 80,
  options: ChannelOptions(
    credentials: ChannelCredentials.insecure(authority: 'localhost/mobile')
    )
  );
```
But it doesn't work. Also I tried add port - `authority: 'localhost:80/mobile'` and still it doesn't work (it doesn't work with `envoyproxy` and I'm not sure on which side problem is) . So, how to properly customize it?

P.S Sorry for being so stupid but I really cannot understand where the problem is.

**Comment by mraleph** [comment]
> What do I want to achieve - customize url from `localhost/<service_name>` to `localhost/mobile/<service_name>`

As I have said before: this sort of customization is incompatible with the gRPC over HTTP2 specification. You would not be able to achieve that through `:authority`. 

What you can achieve with `:authority` is to split trafic based on a subdomain, e.g. `mobile.localhost` and `whatever.localhost`. 

Please refer to envoy documentation to see how that is configured. 

(Also please don't file new issues - just ask clarifying questions on your original issue, if something is unclear).

**Comment by BatanGaming** [comment]
Ah, ok, now I get it. Thank you very much for full explanation
