### ISSUE TITLE
"dart migrate" throws "$async.Future isn't a type"

### ISSUE THREAD

**Issue by boldt** [grpc/grpc-dart#475]
## System

* Windows 10
* Flutter 2.2.0
* Dart 2.13.0
*  grpc: 3.0.0

## Issue

We're trying to migrate a small library to null-safety. Running `dart migrate` throws plenty of the the following error:

```
  error • $async.Future isn't a type at lib\generated\appService.pbgrpc.dart:49:3 • (not_a_type)
```

**Comment by mraleph** [comment]
Seems like a `dart migrate` issue. Please file at https://github.com/dart-lang/sdk
