### ISSUE TITLE
Sample Not Correct? (Instantiation of Abstract Class)

### ISSUE THREAD

**Issue by MelbourneDeveloper** [grpc/grpc-dart#499]
It appears that the sample in the documentation does not compile

V3

## Repro steps

1. Add grpc package V3 to your pubscpec
1. Punch in this code from [here](https://grpc.io/docs/languages/dart/quickstart/)

```Dart
    final channel = ClientChannel(
      'localhost',
      port: 5000,
      options: const ChannelOptions(credentials: ChannelCredentials.insecure()),
    );
```

> Abstract classes can't be instantiated.
Try creating an instance of a concrete subtype.

`ClientChannel` is abstract. We can't instantiate it.

The examples in this repo do work, but they seem to be pointing to the code in the repository and not the published Dart package called grpc. There seems to be differences between the repo and the published package. You can see [here] that the example doesn't point to the actual package. When you look at the code for the `ClientChannel` class in the package, this is what you see:

```Dart
/// A channel to a virtual RPC endpoint.
abstract class ClientChannel {
  /// Shuts down this channel.
  ///
  /// No further RPCs can be made on this channel. RPCs already in progress will
  /// be allowed to complete.
  Future<void> shutdown();

  /// Terminates this channel.
  ///
  /// RPCs already in progress will be terminated. No further RPCs can be made
  /// on this channel.
  Future<void> terminate();

  /// Initiates a new RPC on this connection.
  ClientCall<Q, R> createCall<Q, R>(
      ClientMethod<Q, R> method, Stream<Q> requests, CallOptions options);
}
```

The [code in this repo](https://github.com/grpc/grpc-dart/blob/c982597faea6079712182b663779bf3098d25578/lib/src/client/channel.dart#L26) seems to match the above so I have no idea how the examples instantiate `ClientChannel` when there are no constructors.

**Comment by MelbourneDeveloper** [comment]
It turns out that there are multiple versions of `ClientChannel`. This one is http2_channel.dart

**Comment by mraleph** [comment]
If you import `package:grpc/grpc.dart` you should get the right `ClientChannel`. You should not really be able to get to `ClientChannel` base class, because that it not exported.
