### ISSUE TITLE
OSError (OS Error: No such host is known. , errno = 11001)

### ISSUE THREAD

**Issue by MelbourneDeveloper** [grpc/grpc-dart#503]
<short description>

I have a gRPC service running on Cloud Run over http2. I can easily hit it with a .NET gRPC client, but when I try to hit it with my flutter app running as a Windows app, I get this error:

![image](https://user-images.githubusercontent.com/16697547/125910012-43b98d63-3f96-42d5-bb45-3a881e0c3eb1.png)

The code runs fine on Flutter Windows when the host address is `http://localhost:5000`

<version of the grpc-dart packages used; see your `pubspec.lock` file>

3.0.0

## Repro steps

Put a gRPC service up somewhere and set it up for http2 with a HTTPS address.

Generate the code from the protos and hit the service with this code on a Windows app:

```Dart
  final channel = ClientChannel(
    'https://[URL]/',
    options: ChannelOptions(
      credentials: const ChannelCredentials.insecure(),
      codecRegistry:
          CodecRegistry(codecs: const [GzipCodec(), IdentityCodec()]),
    ));

    final client = TheServiceClient(channel);
```

You should see the error.

## Details

This is the code it hits when it gets the exception

```Dart
  static Future<List<InternetAddress>> lookup(String host,
      {InternetAddressType type: InternetAddressType.any}) {
    return _IOService._dispatch(_IOService.socketLookup, [host, type._value])
        .then((response) {
      if (isErrorResponse(response)) {
        throw createError(response, "Failed host lookup: '$host'");
      }
      return [
        for (var result in response.skip(1))
          _InternetAddress(InternetAddressType._from(result[0]), result[1],
              host, result[2], result[3])
      ];
    });
  }
```
![image](https://user-images.githubusercontent.com/16697547/125911363-c2cd68ca-5b34-477e-9ddb-62db856ee07b.png)

**Comment by mraleph** [comment]
@MelbourneDeveloper please notice that [documentation](https://pub.dev/documentation/grpc/latest/grpc_connection_interface/ClientChannel/ClientChannel.html) for `ClientChannel` constructor is quite explicit in saying that the first parameter is `host` not a uri.

You are looking for something like this: 

```dart
ClientChannel(
    serverHostname,
    port: serverPort, // if different from defaults
    options: ChannelOptions(
      credentials: const ChannelCredentials.secure(), // to use HTTPS
      codecRegistry:
          CodecRegistry(codecs: const [GzipCodec(), IdentityCodec()]),
    ));
```

**Comment by MelbourneDeveloper** [comment]
@mraleph isn't secure the default? I tried without any arguments and it didn't work.

**Comment by MelbourneDeveloper** [comment]
@mraleph I tried this just now:

```Dart
  final channel = ClientChannel(
    "https://server-7a4toqe3ka-km.a.run.app",

    options: ChannelOptions(
      credentials: const ChannelCredentials.secure(), // to use HTTPS
      codecRegistry:
          CodecRegistry(codecs: const [GzipCodec(), IdentityCodec()]),
    ));
```

And, I get the same error.

Note that I have to add this ignore:

> // ignore_for_file: avoid_redundant_argument_values

**Comment by MelbourneDeveloper** [comment]
@mraleph why did you close this? I'm still getting the error despite using your code.

**Comment by mraleph** [comment]
Oh, yeah. `credentials` are secure by default. You don't need that. 

> ```dart
>     "https://[URL]",
> ```

But this you need to fix. This parameter should just be a host name as I have said. Not a uri.

**Comment by MelbourneDeveloper** [comment]
@mraleph got it! Thank. That's awesome.

> This parameter should just be a host name as I have said. Not a uri

This is not consistent with other platforms. On .NET you use a uri.

**Comment by mraleph** [comment]
> This is not consistent with other platforms. On .NET you use a uri.

Yeah, we seem to have departed from what is described in https://github.com/grpc/grpc/blob/master/doc/naming.md for unclear reasons. I don't know why, maybe original implementors did not see that document.
