### ISSUE TITLE
proto3 'optional' keyword support

### ISSUE THREAD

**Issue by zs-dima** [grpc/grpc-dart#507]
Currently `optional Timestamp` and `optional Duration` generate non-nullable types.
However proto3 'optional' keyword means nullable types.

Could be nice to fix this issue to be able to have nullable and non-nullable proto3 types processed correctly.

related issues:
https://github.com/protocolbuffers/protobuf/issues/2168
https://github.com/protocolbuffers/protobuf/issues/8822
https://github.com/grpc/grpc-dart/issues/502

Thanks in advance

**Comment by mraleph** [comment]
Closing in favor of https://github.com/google/protobuf.dart/issues/523
