### ISSUE TITLE
example/grpc-web fails to build main.dart.js

### ISSUE THREAD

**Issue by Mahfuzur-Rahman-Masud** [grpc/grpc-dart#515]
<grpc-web build failure>

<version of the grpc-dart packages 3.0.1>

webdev 2.7.4
'webdev serve web:9000' as instructed in the readme file of grpc-web doesn't work, because main.dart.js is missing.
'webdev build' fails to produce main.dart.js --> with following complain:

"[WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling grpc_web|web/main.dart with dart2js because some of its transitive libraries have sdk dependencies that are not supported on this platform:"
"grpc|lib/src/shared/status.dart
 grpc|lib/src/server/call.dart"

Above 2 files contain imports from **'dart.io'** which causes the failure. When I remove reference to dart.io from above 2 files, build succeeds. 

## Repro steps

1. step1: Clone grpc-dart
2. step2 : cd grpcdart/example/grpc-web
3. step3 webdev build    or  webdev serve web:9000
 
with: webdev 2.7.4

**Comment by Yassineelkasmy** [comment]
Web is not supported yet , think of using a proxy instead in case of Web platform.

**Comment by mraleph** [comment]
Thanks for the report and sorry for the breakage. I have published 3.0.2 that fixes the problem.
