### ISSUE TITLE
SocketException: Failed host lookup address

### ISSUE THREAD

**Issue by jeremylingg** [grpc/grpc-dart#518]
Wanted to connect to local address and get the following error:

SocketException: Failed host lookup: 'myaddress.local' (OS Error: No address associated with hostname, errno = 7)

grpc version: "3.0.2"

## Repro steps

 ClientChannel(
      'myaddress.local',
      port: 10009,
      options: ChannelOptions(
        credentials: ChannelCredentials.secure(certificates: Uint8List.fromList(buffer.toString().codeUnits)),
         ),
    );

Connect to the host.

Resultet in error: 

SocketException: Failed host lookup: 'myaddress.local' (OS Error: No address associated with hostname, errno = 7)

**Comment by mraleph** [comment]
Well, looks like a name resolution failure. Does not have anything to do with grpc package itself.
