### ISSUE TITLE
How to handling error in grpc stream client?

### ISSUE THREAD

**Issue by bonetoy** [grpc/grpc-dart#524]
Client code:
```dart
final clientCall = rpcClient.streamFunc(rpcStreamController.stream);
await for (var response in clientCall){
   ...
}
````
---
I saw some grpc error in locat like this:
```log
Unhandled Exception: gRPC Error (code: xx, codeName: Internal, message: Ops, details: [], rawResponse: null, trailers: {})
```

I can't find a suspicious place for me to throw or handle exceptions. 😂

**Comment by mraleph** [comment]
Does 

```
try {
  final clientCall = rpcClient.streamFunc(rpcStreamController.stream);
  await for (var response in clientCall){
   ...
  }
} catch (e) {
}
```

not catch it?

**Comment by bonetoy** [comment]
> Does
> 
> ```
> try {
>   final clientCall = rpcClient.streamFunc(rpcStreamController.stream);
>   await for (var response in clientCall){
>    ...
>   }
> } catch (e) {
> }
> ```
> 
> not catch it?

yep, not catch it. but this working! Thank you for inspiring me. 😀
```dart 
Futrue<void> callRpc() async {
  ....
}
....
callRpc().onError((e)=>...);
```
