### ISSUE TITLE
Struct support?

### ISSUE THREAD

**Issue by datdefboi** [grpc/grpc-dart#533]
I use Struct type in the following message:
```proto
message Product{
  int32 id = 1;
  bool is_alcohol = 2;
  string brand = 3;
  google.protobuf.Struct parameters_map = 4;
  string title = 5;
  double weight = 6;
  bool is_fractional = 7;
}
```

Unfortunately, protoc generates the following import:
```dart
import 'google/protobuf/struct.pb.dart' as $0;
```
Obviously, I have no generated file

Build script:
```ps1
protoc --dart_out=grpc:lib/generated -I../proto ../proto/models.proto
```

**Comment by sigurdm** [comment]
You need to include the well-known proto definitions yourself.

See: https://github.com/google/protobuf.dart/issues/170
