### ISSUE TITLE
Should grpc depend on googleapis_auth?

### ISSUE THREAD

**Issue by eseidel** [grpc/grpc-dart#561]
Not a huge deal, but odd that package:grpc depends on googleapis_auth.

Maybe protos are only/mostly used at/around Google and thus that makes sense?

**Comment by guyluz11** [comment]
I think you are right and it does not fit here at grpc-dart package.

It is used only in 2 files
https://github.com/grpc/grpc-dart/blob/master/lib/src/auth/auth.dart
https://github.com/grpc/grpc-dart/blob/master/lib/src/auth/auth_io.dart

First commit sais

> Authenticated cloud-to-prod interop tests

Maybe it was added for testing?

**Comment by mraleph** [comment]
I think this is optimising/simplifying for the case when gRPC is used in Google Cloud environment (e.g. to invoke Cloud APIs), which is a common use case. To break the dependency we would either need to move this code into some separate package (e.g. `grpc_googleapis_auth`) or we need to introduce some package for shared interface for handling OAuth2 tokens and use it here. It's unclear if breaking this dependency is worth it.

**Comment by nvi9** [comment]
In my opinion it would worth moving googleapis_auth related code to a different package. If one would like to use strictly only gRPC for some reason, having a lot of unnecessary transitive dependencies is everything but optimized/simple. This package exists separated from everything else Google Cloud related for some reason, not just included in a single big package.

I'm not in favor of having packages like [is_even](https://pub.dev/packages/is_even) (just for negating the result of [is_odd](https://pub.dev/packages/is_even)), but separate packages for different functionalities with descriptive names help to keep the ecosystem clean and well structured.
