### ISSUE TITLE
grpc-web might need to default grpc-status to 0 when missing

### ISSUE THREAD

**Issue by mraleph** [grpc/grpc-dart#566]
It seems there is a discrepancy in how native protocol and gRPC-Web are handling `grpc-status`. This discrepancy does not seem to be documented in gRPC-Web spec [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md), but it becomes obvious when comparing implementations. 

Native gRPC protocol [describes](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses) `grpc-status` as an always present:

>  **Status** must be sent in **Trailers** even if the status code is OK.

Implementations handle missing `grpc-status` as an error. See e.g. [Java implementation](https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/core/src/main/java/io/grpc/internal/Http2ClientStreamTransportState.java#L190-L207).

gRPC-Web protocol description does not mention any difference to native protocol with respect to status handling, but [looking at the implementation](https://github.com/grpc/grpc-web/blob/35284bfe156fc41bbcdd554ac423a587d93ff8da/javascript/net/grpc/web/grpcwebclientreadablestream.js#L196-L202) we discover that it defaults status to OK if it is missing.

We have not observed such behaviour when testing with Envoy, but apparently there are servers out there which would omit OK status. 

It's unclear whether server is compliant to gRPC-Web specificiation here or whether default implementation is simply lenient. @wenbozhu could you provide the guidance here?

**Comment by sampajano** [comment]
As per @wenbozhu, `grpc-status` should be mandatory.

But I'm not sure why exactly is the grpc-web code allows it to be empty. :)

**Comment by mraleph** [comment]
Thanks @sampajano. 

Resolving this as the current behaviour matches the intent.
