### ISSUE TITLE
Don't import implementation files from another package

### ISSUE THREAD

**Issue by medz** [grpc/grpc-dart#569]
Don't import implementation files from another package.

```yaml
grpc: ^3.0.2
protobuf: ^2.1.0
```

## Repro steps

1. step1 protobuf import 'google/protobuf/timestamp.proto'
1. step2 gen proto to dart classes

Expected result: 
```dart
///
//  Generated code. Do not modify.
//  source: google/protobuf/timestamp.proto
//
// @dart = 2.12
// ignore_for_file: annotate_overrides,camel_case_types,constant_identifier_names,directives_ordering,library_prefixes,non_constant_identifier_names,prefer_final_fields,return_of_invalid_type,unnecessary_const,unnecessary_import,unnecessary_this,unused_import,unused_shown_name, implementation_imports
```

Actual result: 
```dart
///
//  Generated code. Do not modify.
//  source: google/protobuf/timestamp.proto
//
// @dart = 2.12
// ignore_for_file: annotate_overrides,camel_case_types,constant_identifier_names,directives_ordering,library_prefixes,non_constant_identifier_names,prefer_final_fields,return_of_invalid_type,unnecessary_const,unnecessary_import,unnecessary_this,unused_import,unused_shown_name
```

## Details

<img width="588" alt="image" src="https://user-images.githubusercontent.com/5564821/179804636-7291476b-eab8-4cc6-bf3d-256d983e762b.png">
<img width="691" alt="image" src="https://user-images.githubusercontent.com/5564821/179804687-5691dcf5-0df7-4b82-8ef3-1b79363ae0fa.png">

**Comment by medz** [comment]
In the `protobuf.dart` repository https://github.com/google/protobuf.dart/issues/328

Issue submission time is 2019, although this does not affect actual use. However, there are always warnings and errors in the development toolbar, which affect the development experience.

**Comment by mraleph** [comment]
Already reported in https://github.com/google/protobuf.dart/issues/328.
