### ISSUE TITLE
Active maintainer wanted

### ISSUE THREAD

**Issue by krjw-eyev** [grpc/grpc-dart#571]
I read somewhere in the comments of a pull request that this project has no active maintainer. Is this still the case?
The last release is a year old and there are a lot of open issues and open pull requests.
I feel like this project should be actively maintained.

Maybe this could be more advertised (pinned issue, added to README) so that someone from the community has the chance to take over and maintain this project.

**Comment by mraleph** [comment]
> I read somewhere in the comments of a pull request that this project has no active maintainer. Is this still the case?

Yes, though we are looking at different ways to solve this problem. 

> someone from the community has the chance to take over and maintain this project.

I don't think passing the ownership of this package to community is an option at this stage.
