### ISSUE TITLE
Safe to use this library?

### ISSUE THREAD

**Issue by bit-void** [grpc/grpc-dart#580]
I'm starting a new project and unsure about the state of this library. There hasn't been a release in over a year and I read a few places there is no active maintainers, but it's not appropriate for community maintenance (I agree). Is google still supporting this or is it better to hold off until there's more information? We're going with flutter and would like to use gRPC for the communication layer but are nervous given the project state. No worries either way, just seeking information! Thanks!

**Comment by domesticmouse** [comment]
The package is maintained, as you can see by inspecting https://github.com/grpc/grpc-dart/commits/master

A new release is probably worth doing. Thoughts @mraleph?

**Comment by mraleph** [comment]
I can make a release. 

The library does not have an active maintainer (in a sense that somebody is doing things with it on a regular basis), but we fix critical issues and try to review PRs which fix critical issues.

That being said: library works and is used in production both internally and by third parties, so you can certainly depend on it.

**Comment by bit-void** [comment]
Thank you for the clarification, would definitely appreciate a new release!
