### ISSUE TITLE
 Is it possible to use proxy?

### ISSUE THREAD

**Issue by Williamredondo** [grpc/grpc-dart#595]
Good evening, is it possible to use a proxy in some way?

**Comment by mraleph** [comment]
Could you clarify your question?

**Comment by Williamredondo** [comment]
I have an application that is being used by companies, where it needs to communicate with the server via proxy, if I was using http/rest for example, I would have the code below as an example to use:

@override
  HttpClient createHttpClient(SecurityContext context) {
    return super.createHttpClient(context)
      // set proxy
      ..findProxy = (uri) {
        return _host != null ? "PROXY $_host:$_port;" : 'DIRECT';
      };
  }
}

with grpc, do we have something similar? or any way to go through a proxy server?

**Comment by Williamredondo** [comment]
I believe this should suit me. Thanks for the answer.
