### ISSUE TITLE
optional in protobuf not working in grpc-dart

### ISSUE THREAD

**Issue by yingshaoxo** [grpc/grpc-dart#599]
# What I wrote

Here is my protobuf code:
```proto
syntax = "proto3";
package account_storage_service;

option go_package = "./account_storage_service";

service AccountStorageService {
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
}

message CreateUserRequest {
    optional string email = 1;
}

message CreateUserResponse {
    string result = 1;
    optional string error = 2;
}
```

Here is my grpc build command:
```bash
protoc --dart_out=grpc:lib/generated_grpc --proto_path ../party_protocols/protocols --experimental_allow_proto3_optional account_storage_service.proto
```

Here is my flutter code:
```dart
CreateUserRequest createUserRequest = CreateUserRequest();
createUserRequest.email = updateUserRequest.email;

CreateUserResponse response = await client.createUser(createUserRequest,
          options: get_JWT_CallOptions_for_GRPC());
if (response.error != null && response.error != "") {
    return default_response;
}
```

<img width="659" alt="image" src="https://user-images.githubusercontent.com/17190829/212817300-ae3d6b59-0177-482d-ad8e-2031276fb8f9.png">

# What I expect
The`email` property in `CreateUserRequest ` should be a null-safe variable, which means it could be null

The `error` property in `CreateUserResponse` should be a null-safe variable, which means it could be null

# What I see is
**They are all not null-able variables, it seems like the compiler ignores the `optional` string in the protobuf definition.**

<img width="702" alt="image" src="https://user-images.githubusercontent.com/17190829/212817067-5615c0bd-84ea-45b0-a67b-1400537960c4.png">

<img width="892" alt="image" src="https://user-images.githubusercontent.com/17190829/212817037-02ff02bb-6407-449f-99c6-ee09e4ed636a.png">

<img width="763" alt="image" src="https://user-images.githubusercontent.com/17190829/212817113-43e00e6f-e656-48e6-b38d-8dea8acf2c4f.png">

**Comment by yingshaoxo** [comment]
I found someone did a pull, but didn't get merged yet.

https://github.com/google/protobuf.dart/pull/790

**Comment by mraleph** [comment]
It's a protobuf issue, so it should be handled on protobuf repositiory. I asked protobuf.dart maintainer to take a look at the PR. 

That being said: we can't just make these fields nullable because that is going to be massively breaking change. It probably could be an opt-in option for the protoc.
