### ISSUE TITLE
Is there an equivalent of Java's NettyChannelBuilder?

### ISSUE THREAD

**Issue by juskek** [grpc/grpc-dart#609]
Hi there,

I am new to this package and was just wondering if there was an equivalent of java-grpc's [NettyChannelBuilder](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyChannelBuilder.html)

Thank you!

**Comment by mraleph** [comment]
There is no equivalent. You just create `ClientChannel` instances directly.
