### ISSUE TITLE
CORS not supported on a Dart server

### ISSUE THREAD

**Issue by Levi-Lesches** [grpc/grpc-dart#611]
<short description>

When using `package:grpc` on a Dart server, you make a `Server` and then call `server.serve()`. This server cannot handle CORS requests in the way `package:shelf` can, and so all requests from the Flutter side are broken.

grpc version: `v3.1.0`

## Repro steps

```dart
// LoginService is a regular rpc service
void main() async {
  final server = Server([LoginService()]);
  await server.serve(port: 9000);
  print("Server running on http://localhost:9000");
}
```

Expected result: Sending requests to this server works

Actual result: 
```
gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP request completed without a status (potential CORS issue)
```

**Comment by mraleph** [comment]
Note that the server implementation only talks gRPC native protocol, does not support gRPC-Web clients directly. Hence no CORS support or anything like that. You need a proxy in between which would convert gRPC-Web to gRPC.

**Comment by Levi-Lesches** [comment]
Yes, I saw that elsewhere. Would it be possible to provide, in this package or another, native Dart support for `gRPC-Web` without the need for a separate proxy?

**Comment by mraleph** [comment]
It is definitely possible and I think we will accept a PR implementing gRPC-Web server.
