### ISSUE TITLE
Server.create constructor is deprecated, need to update sample code

### ISSUE THREAD

**Issue by craiglabenz** [grpc/grpc-dart#617]
Existing sample code suggests creating servers like so:

```dart
grpc.Server.create(services: [RouteGuideService()])
```

But that seems like it should be updated to:

```dart
grpc.Server([RouteGuideService()])
```

**Comment by mraleph** [comment]
Hmm, I am puzzled. It is the other way around and samples were in fact updated to use `Server.create`.

```
  /// Create a server for the given [services].
  @Deprecated('use Server.create() instead')
  Server(...);
```

We do need to update the basics guide though which is hosted in some other repo: https://grpc.io/docs/languages/dart/basics/

**Comment by broderix** [comment]
UP.
@mraleph , thanks for response. I think you should bump new version 3.1.1 from master. Because example correct with version in master, that uses  `Server.create()` .

**Comment by mraleph** [comment]
@mosuem could you take a look at releasing the new version? (maybe we can even use this as an opportunity to configure publishing from GitHub actions for this repo). 

(I have created PR to update docs: https://github.com/grpc/grpc.io/pull/1145)
