### ISSUE TITLE
Upgrade http to ver 1.0.0

### ISSUE THREAD

**Issue by mbn18** [grpc/grpc-dart#632]
<short description>
Got the following error while trying to upgrade flutter_map to ver 5.0.0

```
Because no versions of grpc match >3.1.0 <4.0.0 and grpc 3.1.0 depends on http ^0.13.0, grpc ^3.1.0 requires http ^0.13.0.
And because flutter_map >=5.0.0 depends on http ^1.0.0, grpc ^3.1.0 is incompatible with flutter_map >=5.0.0.
```

<version of the grpc-dart packages used; see your `pubspec.lock` file>

    • Flutter version 3.10.3 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (4 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

**Comment by broderix** [comment]
@mbn18 please check this out [PR-629](https://github.com/grpc/grpc-dart/pull/629) 
It seems issues was resolved

**Comment by domesticmouse** [comment]
`grpc` v3.2.1 will work with both `http` versions.

**Comment by kevmoo** [comment]
Yup!
