### ISSUE TITLE
Interop dart server is timing out

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-dart#650]
The cross-language interop tests have been failing since Jun 7th. That was initially due to a dart compilation failure (the first failure, [build 33753](https://source.cloud.google.com/results/invocations/b162c57d-aae6-4ffe-b8ec-ff7ecd9ed6f5). On Jun 21 (build 34003), that issue was fixed, but it was replaced with various tests failing when hitting the dart server. ([Google-Internal CI link](https://fusion2.corp.google.com/ci/kokoro/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_tocloud/
) for all builds)

The recent [build 34251](https://source.cloud.google.com/results/invocations/aeb4acc4-6444-4360-953b-e1caa977f616). Java client fails "AssertionError: Timed out waiting for response". `cloud_to_cloud:java:dart_server:ping_pong:tls` test . The other `dart_server:ping_pong:tls` tests (including javaokhttp client) passed in about a second. That one failed in 17. The code has a 15s timeout.

[Build 34243](https://source.cloud.google.com/results/invocations/d07d7340-1187-442d-99f5-2a06d86c264e) passed with Java but failed with:
```
2023-07-07 00:47:11,227 TIMEOUT: cloud_to_cloud:dart:dart_server:ping_pong:tls [pid=210107, time=180.1sec]
```

[Build 34240](
https://source.cloud.google.com/results/invocations/549f706d-fa5a-4299-a61f-bdbf67c067ba) had 7 timeouts to dart_server.

**Comment by ejona86** [comment]
I believe all of these tests are against master. A different suite tests released versions.

**Comment by mraleph** [comment]
Probably related to recent changes @mosuem

**Comment by mosuem** [comment]
This is tracked internally in b/288120247 and seems related to the Dart version rev in the docker build script, but I am investigating.
