### ISSUE TITLE
How to create GrpcError with details?

### ISSUE THREAD

**Issue by CoMatu** [grpc/grpc-dart#655]
For testing some functionality, I need to create some instance of `GrpcError` with custom `details`, like this:

` when(() => registerRepository.registerUser(
        any(),
        any(),
        any(),
      )).thenThrow(GrpcError.custom(13, 'Internal', []));`

My problem is how to create custom details of `GrpcError`, as `List<GeneratedMessage>` with data:
`gRPC Error (code: 13, codeName: INTERNAL, message: Internal, details: [typeUrl: type.googleapis.com/office.ResponseResult
  value: [8, 2, 16, 24]
  ],)`

**Comment by 0xManjeet** [comment]
@CoMatu how did you fix it? I'm not able to import 'ANY'.

**Comment by CoMatu** [comment]
I create class:
`class AnyMessage extends GeneratedMessage {
  final String typeUrl;
  final Uint8List value;

  AnyMessage(this.typeUrl, this.value);

  @override
  GeneratedMessage clone() {
    return AnyMessage(typeUrl, value);
  }

  @override
  GeneratedMessage createEmptyInstance() {
    return AnyMessage(typeUrl, value);
  }

  @override
  BuilderInfo get info_ => BuilderInfo('AnyMessage');

  @override
  String toString() => typeUrl;
}`
