### ISSUE TITLE
Flutter app with grpc-dart, fails with flutter_test: "Package hrpc has no versions that match 0.3.1

### ISSUE THREAD

**Issue by tjerkw** [grpc/grpc-dart#66]
When trying to use grpc dart in my flutter app im keep getting the following error:

`
Running "flutter packages get" in boomrang_app...
Package async has no versions that match 2.0.4 derived from:
- boomrang_app depends on version ^1.13.3
- flutter_test 0.0.0 depends on version 2.0.4
- grpc 0.3.1 depends on version ^1.13.3
- http 0.11.3+16 depends on version >=1.10.0 <3.0.0
`

I can resolve it by removing my dev_dependencies from the following pubspec.yaml file:

pubspec.yaml:

`name: boomrang_app
description: Boomrang mobile app

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  contact_picker: "^0.0.1+2"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  grpc: "^0.3.1"
  protobuf: ^0.7.0

  async: ^1.13.3

dev_dependencies:
  test: ^0.12.0
  flutter_test:
    sdk: flutter
`

Also why do i need to specify the async dependecies ?  And can i remove the "test: 0.12.0" dependency in the dev_depencies?

Anyway removing dev_dependecies resolves it, but thats not a proper solution.

**Comment by jakobr-google** [comment]
Dup of #63, should be fixed in v0.4.0.

Problem was that flutter has a dependency on async 2.0.4, which was outside grpc's range.
