### ISSUE TITLE
[BUG] gRPC Web Error if server supports gzip compression

### ISSUE THREAD

**Issue by zs-dima** [grpc/grpc-dart#668]
gRPC server supports gzip compression:
```python
server = aio.server(compression=aio.grpc.Compression.Gzip
```

gRPC Web client calls method (server side streaming) without compression:
```dart
client.testServerStream(rpc.TestRequest(), options: CallOptions(compression: const IdentityCodec())
```
```proto
    rpc TestServerStream (TestRequest) returns (stream TestResponce);
```

Client error: `Error code: 12, codeName: UNIMPLEMENTED, message: Invalid frame type: 1`

For the non-Web clients this method executes successfully in both cases:
```dart
client.testServerStream(rpc.TestRequest(), options: CallOptions(compression: const GzipCodec())
client.testServerStream(rpc.TestRequest(), options: CallOptions(compression: const IdentityCodec())
```
And the same `grpc-web` protocol client works fine when I disable compression option on server.

Response Headers:
```
content-type: application/grpc-web+proto
grpc-encoding: gzip
grpc-accept-encoding: identity, deflate, gzip
server: envoy
transfer-encoding: chunked
```
Envoy configuration:
https://gist.github.com/zs-dima/1b113f4c07e5accd7e751771d48b9e59

Flutter: 3.13.1
protobuf: ^3.1.0
grpc: ^3.2.3
Browser: Chrome

Python: 3.11.5
grpcio==1.58.0rc1
grpcio-tools==1.58.0rc1
protobuf==4.24.2

**Comment by mosuem** [comment]
Could you specify if you are using `grpc` or `grpc-web` as a protocol, and what the expected behavior is?

**Comment by zs-dima** [comment]
@mosuem 
As I mentioned above `grpc-web` protocol client throwing an exception: `Error code: 12, codeName: UNIMPLEMENTED, message: Invalid frame type: 1`
In the same time `grpc` protocol client (the same Flutter Web application connecting the same gRPC server) working well.

**Comment by zs-dima** [comment]
@mosuem 
As I mentioned above the `grpc-web` protocol client throws an exception: `Error code: 12, codeName: UNIMPLEMENTED, message: Invalid frame type: 1`
At the same time the `grpc` protocol client (the same Flutter Web application connecting to the same gRPC server) works fine.

I expect `grpc-web` protocol clients to work well at least without compression. Ideally with compression.

**Comment by zs-dima** [comment]
@mosuem updated my answer above

**Comment by zs-dima** [comment]
Solved with Envoy cofiguration update:
```
cors:
    allow_headers: "*"
```
