### ISSUE TITLE
https://pub.dev/documentation/grpc/latest/ API redirects to itself

### ISSUE THREAD

**Issue by RubenGarcia** [grpc/grpc-dart#670]
<short description>
At https://pub.dev/documentation/grpc/latest/ 
clicking on 
[API reference](https://grpc.io/docs/languages/dart/api)
redirects to itself.

<version of the grpc-dart packages used; see your `pubspec.lock` file>
All

## Repro steps

Expected result:
A list of classes and documentation about the classes should be provided in web form.

Actual result: <describe what actually happened>
Redirect to 
https://pub.dev/documentation/grpc/latest/
with no information about the API

**Comment by RubenGarcia** [comment]
Also
https://[pub.dev/documentation/grpc/latest/example](https://pub.dev/documentation/grpc/latest/example)
is a broken link.

**Comment by mosuem** [comment]
> ## Repro steps
> Expected result: A list of classes and documentation about the classes should be provided in web form.

This is because this is the readme page, which contains a link to the API page. So displaying the readme on the API page leads to a no-op link. But this is still WAI, as the page _is_ the API page - or what should it link to instead?

**Comment by mosuem** [comment]
> Also https://[pub.dev/documentation/grpc/latest/example](https://pub.dev/documentation/grpc/latest/example) is a broken link.

Closing in favor of https://github.com/dart-lang/pub-dev/issues/7062
