### ISSUE TITLE
security vulnerability in `archive` <= 3.3.7

### ISSUE THREAD

**Issue by mockturtl** [grpc/grpc-dart#677]
GitHub's Dependabot notified me of security vulnerabilities in `archive`, which is used by [`GzipCodec`](https://github.com/grpc/grpc-dart/blob/master/lib/src/shared/codec.dart#L16).

> An issue in Archive v3.3.7 allows attackers to execute a path traversal via extracting a crafted zip file.

> An issue in Archive v3.3.7 allows attackers to spoof zip filenames which can lead to inconsistent filename parsing.
 
Details, CVE: https://pub.dev/packages/archive/changelog#338---september-02-2023

You may wish to consider bumping the version constraint to `archive: ^3.3.8`.

**Comment by mraleph** [comment]
These vulnerabilities don't affect grpc because there are no files extracted to disk or archives being traversed.
