### ISSUE TITLE
Cannot read HTTP headers of client response

### ISSUE THREAD

**Issue by spreeni** [grpc/grpc-dart#683]
I can't find a way to parse HTTP headers of a grpc client response.

I am trying to connect to an API which answers with a `set-cookie` header that I need to parse.

grpc-dart version: 3.2.4

## Repro steps

1. Send a request from a grpc client
2. Examine the response, it just contains the deserialized data and none of the header information
3. This is the same in a `ClientInterceptor` (e.g. https://stackoverflow.com/questions/72949714/how-to-intercept-grpc-response/72949742#72949742)

Expected result: I can somehow access header information of the response

Actual result: The response just contains the deserialized data and none of the header information

I am a Dart/gRPC newbie, so I might not be familiar with a possible solution here, but am open to any suggestions.

**Comment by mraleph** [comment]
Is this native gRPC (i.e. in the mobile app) or a gRPC-Web (i.e. in the browser)?

In the browser you will not be able to access Set-Cookie because it is a [forbidden response header](https://fetch.spec.whatwg.org/#forbidden-response-header-name) and will be hidden from the client code.

**Comment by mraleph** [comment]
On the native side I would have expected all headers to be passed back to the client without any filtering. Does `response.headers` not contain cookie header?

**Comment by spreeni** [comment]
Maybe I am missing something, but the deserialized response seems to not have a `headers` attribute. It implements the abstract class `protobuf.GeneratedMessage` and just contains a `_fieldSet`.

![image](https://github.com/grpc/grpc-dart/assets/35889034/24333de7-43a6-48ec-bf66-94d09e29e0db)

**Comment by mraleph** [comment]
I am talking about [`Response.headers`](https://pub.dev/documentation/grpc/latest/grpc/Response/headers.html) property. 

You need to try something like:

```dart
final call = client.someMethod(...);
final headers = await call.headers;
final response = await call; 
```

to get access to them.

**Comment by spreeni** [comment]
Oh thanks for the solution! I was just executing
```
final response = await client.someMethod(...);
```
directly and skipping the header retrieval completely. 🙈 Thanks for the quick and very helpful answers, closing this issue again then.
