### ISSUE TITLE
does not work properly on windows 10 protoc-gen-dart: The system cannot find the specified file.

### ISSUE THREAD

**Issue by rhelenagh** [grpc/grpc-dart#71]
protoc-gen-dart: The system cannot find the specified file.

0.7.10

## Repro steps
1. install pub global activate protoc_plugin
2. protoc-gen-dart, is installed in %PATH%
3. protoc --dart_out=grpc:. -I. <the protofile.proto>

Expected result: it should convert my IDL,  generate the classes in Dart.

Actual result: --dart_out: protoc-gen-dart: The system cannot find the specified file.

## Details

Dart version
Dart VM version: 2.0.0-dev.28.0.flutter-0b4f01f759 (Tue Feb 20 17:53:06 2018 +0000) on "windows_x64" 
Windows 10

Thanks!

**Comment by nevi-me** [comment]
Hi @rhelenagh 

Something like this can help: 

```
$ protoc -Iproto proto/[file].proto --plugin=protoc-gen-dart=c:\Users\[youruser]\AppData\Roaming\Pub\Cache\bin\protoc-gen-dart.bat --dart_out=grpc:lib/generated
```

I also struggled a bit at first.

**Comment by rhelenagh** [comment]
Hi @nevi-me 

thank you very much Nevi!
It has worked!

This closes the ticket.
For future beginner users (like me) it would be very helpful to include this tip in the official documentation. -"first steps in the window environment".

Thanks again for your time and information
