### ISSUE TITLE
package import statement generated with well-defined type is not correct.

### ISSUE THREAD

**Issue by rhodee** [grpc/grpc-dart#76]
When compiling using the following command, the import statement is not Dart code. Are there any examples for how to handle this - thank you!

<version of the grpc-dart packages used; see your `pubspec.lock` file>
```
  grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0"
```

## Repro steps

1. Run: `protoc -Iprotos -I $(GOPATH)src/github.com/golang/protobuf/ptypes/timestamp --dart_out=grpc:proto_out/service.proto`

Expected result: Usable dart import package declaration for the well-defined types

Actual result: package import declaration causes an error and compilation is not possible.

## Details

Below is a snipped of the `.proto` file. I am trying to create a client stub (the server is written in Go). I have confirmed the client stub exported from Go works. 

```proto
syntax = "proto3";

package mypackage;

option go_package = "github.com/mypackage;

import "google/protobuf/timestamp.proto";

message Timestamp {
    google.protobuf.Timestamp created = 1;
    google.protobuf.Timestamp updated = 2;
    google.protobuf.Timestamp synced = 3;
}
... implementation details to follow...
```

Upon running the `protoc` command the output is:

```dart
/// service.pb.dart

///
//  Generated code. Do not modify.
///
// ignore_for_file: non_constant_identifier_names,library_prefixes
library my_service;

// ignore: UNUSED_SHOWN_NAME
import 'dart:core' show int, bool, double, String, List, override;

import 'package:protobuf/protobuf.dart';

import 'google/protobuf/timestamp.pb.dart' as $google$protobuf;

import 'service.pbenum.dart';

export 'service.pbenum.dart';

/// ...generated code continues...
```

**Comment by jakobr-google** [comment]
Imports look correct to me. What error are you getting?

If I try your sample as is, I get this error when trying to analyze the project:
```
error • Target of URI hasn't been generated: 'google/protobuf/timestamp.pb.dart' at proto_out/service.pb.dart:12:8 • uri_has_not_been_generated
```
if that's the error you're seeing, then the reason is that you haven't generated Dart sources for `google/protobuf/timestamp.proto`.

Somewhat unfortunately, the protoc compiler only generates sources for the files you've listed on the command line, so you'll need to add timestamp there as well. On my machine, it's `/usr/include/google/protobuf/timestamp.proto', YMMV.

If you're getting another error, please let me know what it is.

**Comment by rhodee** [comment]
That is exactly the error I am getting. I tried following the example for what you suggested, using the only example I could find was in C#. I have a similar path similar to the one you suggested in my GOPATH. Is there a Dart equivalent?

**Comment by rhodee** [comment]
That did not solve the problem.


I have tried adding the following code on OSX:

```make
PROTO_ROOT_DIR = $(shell brew --prefix)/Cellar/protobuf/3.5.1_1/include/google/protobuf

.PHONY: mobile-stub
mobile-stub:
	@mkdir -p lib/client
	@protoc -I. -I$(PROTO_ROOT_DIR)/timestamp.proto --dart_out=grpc:lib/client service.proto
```

I originally wrote the code in Go and tried to compile to Dart. I attempted to move the service.proto to the dart app - and it created the same output as when I originally opened the issue.

**Comment by jakobr-google** [comment]
You need to have protoc generate the Dart stubs for google/protobuf/timestamp.proto as well, so you either have to add `$PROTO_DIR/google/protobuf/timestamp.proto` to the end of the command line, or add a separate call to protoc for it:
```
protoc -I$(PROTO_DIR) --dart_out=lib/client $(PROTO_DIR)/google/protobuf/timestamp.proto
```

On my macOS box, `PROTO_DIR` is `/usr/local/include`, but you can also use `$(shell brew --prefix)/Cellar/protobuf/3.5.1_1/include`.

The reason you don't need to do this for Go, is that the Go protobuf package includes prebuilt stubs for these types.

**Comment by rhodee** [comment]
Very clear and thank you for your patience. This issue can be closed.

**Comment by Ali-Mbacho** [comment]
I had the same problem dealing with money.proto and my solution was.
1. I manually added from [money.proto](https://github.com/googleapis/googleapis/blob/master/google/type/money.proto) file to my _/usr/incude/google/protobuf/..._.  
2. added money.proto to my project.
3. I generated both myproto.proto and money.proto files separately with protobuf.
4. Lastly I imported 'package:PATH TO/money.pb.dart' in myproto.pb.dart.
