### ISSUE TITLE
Dart2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [grpc/grpc-dart#84]
running tests in dart 2 mode, see failures like

type 'ArgMatcher' is not a subtype of type 'List<Header>' where...
type 'ArgMatcher' is not a subtype of type 'List<Header>' where
  ArgMatcher is from package:mockito/src/mock.dart
  List is from dart:core
  Header is from package:http2/src/hpack/hpack.dart
../../dart/grpc/test/src/client_utils.dart 126:32  ClientHarness.setUp

**Comment by keertip** [comment]
@mravn-google , @kevmoo

**Comment by mravn-google** [comment]
@jakobr-google
