### ISSUE TITLE
NoSuchMethodError: The method '&' was called on null.

### ISSUE THREAD

**Issue by dvaldivia** [grpc/grpc-dart#87]
I'm trying to stream a image file to a grpc server using `1KB` chunks

As soon as I get the `File` on dart, I convert it to a Stream<ImageRequest>

```dart
Stream<ImageRequest> chunkFileBytes(List<int> stream) async* {
  List<int> buffer = new List<int>(1024);
  var counter = 0;
  print("Total bytes: ${stream.length}");
  for (var i = 0; i < stream.length; i++) {
    buffer[counter] = stream[i];
    counter++;
    if (counter == 1024) {
      var req = new ImageRequest();
      req.content = buffer;
      counter = 0;
      buffer = new List<int>(1024);
      yield req;
    }
    if (counter > 0) {
      var req = new ImageRequest();
      req.content = buffer;
      yield req;
    }
  }
}
```

and pass this to grpc 

```dart
var bytes = image.readAsBytesSync();
final post = await stub.postImage(chunkFileBytes(bytes));
```

But that's throwing  error
```
gRPC Error (2, NoSuchMethodError: The method '&' was called on null.
Receiver: null
Tried calling: &(255))
#0      _FeedScreen.getImage (package:myapp/feed.dart:71:18)
<asynchronous suspension>
```

I'm suspecting something is trying to use the very first byte of the first chunk of my stream as a function and that's blowing up.

Using
grpc: "^0.4.1"

**Comment by mit-mit** [comment]
cc @sigurdm, any idea what's going on here?

**Comment by sigurdm** [comment]
I think I need to know more about the type of `stub` and the implementation of `postImage` to really help here. You are right that it looks like you are using the first byte as a method name. You should be calling a named remote method with the content as a parameter.

As a side-comment, I think your `chunkFileBytes` has a mistake in the second if-statement. It should be outside the for-loop I think. Otherwise it will send chunks of length '1, 2, 3, 4...'.

**Comment by dvaldivia** [comment]
Nice catch on the `chunkFileBytes` function @sigurdm 

Some extra details on the stub, I have a service declared as

```
service PostService {
    rpc PostImage (stream ImageRequest) returns (PostResponse) {
    }
}
```
And the respective messages

```
message ImageRequest {
    bytes content = 1;
}

message PostResponse {
    string id = 1;
    string url = 2;
}
```

**Comment by dvaldivia** [comment]
An update, seems like that last block I have over here, that @sigurdm pointed out
```
if (counter > 0) {
      var req = new ImageRequest();
      req.content = buffer;
      yield req;
    }
```
which probably has a different size is the problem, in the main loop I can actually stream and send full 1024 chunks, but the very last chunk throws the error, I'm assuming there's a termination character that I'm getting from dart that I'm trying to pass to grpc which should probably be handled differently?

**Comment by dvaldivia** [comment]
The problem was I was trying to send a buffer of size 1024 with only 462 bytes populated, I just had to build a buffer of the right size, before passing it to grpc
