### ISSUE TITLE
Could grpc-dart work on secure state? example are just the 'insecure' .

### ISSUE THREAD

**Issue by hjlp20150803** [grpc/grpc-dart#88]
here are the example for client
https://github.com/grpc/grpc-dart/blob/master/example/route_guide/lib/src/client.dart
and the client cold are here:
    channel = new ClientChannel('127.0.0.1',
        port: 8080,
        options: const ChannelOptions(
            credentials: const ChannelCredentials.insecure()));
the example are same as the golang example(https://github.com/grpc/grpc-go/tree/master/examples/route_guide).
Some time the dart client can't work with golang server, sometime it works, I checked and find out cause the client has not use the secure and the dart server do too.
I want to try fill the option to secure the connection, but I don't know how in dart. And I want to find AES in dart and I failed, so I worry about dart can't work in secure state.

If grpc-dart can work in secure state, could anybody give a demo?

**Comment by jakobr-google** [comment]
Absolutely! Secure is the default state for the client, so if you just want to use your system's built-in trust roots, you don't need to pass any options.

You only need to pass options on the client side if you want to provide your own certificates to trust, or if you want to use insecure transport. On the server side, you'll need to provide the certificate and private key if you want to enable TLS.

The interoperability test client and server demonstrate both. Take a look at https://github.com/grpc/grpc-dart/blob/master/interop/lib/src/client.dart#L98 for the client code, and https://github.com/grpc/grpc-dart/blob/master/interop/bin/server.dart#L136 for the server.
