### ISSUE TITLE
Failed to generate the grpc code for Dart --dart_out: protoc-gen-dart: Plugin failed with status code 252.

### ISSUE THREAD

**Issue by tanphathuynh** [grpc/grpc-dart#93]
I follow the instruction to download and install protoc and protoc plugin for dart [here](https://grpc.io/docs/quickstart/dart.html#generate-grpc-code).
I use Linux
protoc version 3.6.0

I could not generate the code for dart and this error message came out:
`--dart_out: protoc-gen-dart: Plugin failed with status code 252.`
and  
`
Crash when compiling file:///home/phat/.pub-cache/global_packages/protoc_plugin/bin/protoc_plugin.dart.snapshot,
at character offset null:
String starting with ' must end with '.
#0      ErrorToken.lexeme (package:front_end/src/fasta/scanner/error_token.dart:74:24)
#1      _withArgumentsExpectedDeclaration (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/front_end/lib/src/fasta/fasta_codes_generated.dart:1989:25)
#2      Parser.reportRecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:6020:20)
`

Thank you!

**Comment by lvh1g15** [comment]
@tanphathuynh did you manage to solve this as I am having the same issue

**Comment by tanphathuynh** [comment]
@lvh1g15 I am still having this problem on my computer. But I tried to generate on another new machine, it works. Still not sure what the problem is.

**Comment by Mohammed90** [comment]
Try re-install/upgrade protoc_plugin everytime Dart is updated on your system. That solves it for me.

**Comment by lvh1g15** [comment]
@Mohammed90 thanks for the help

**Comment by RdeWilde** [comment]
Any link/info on simple way to reinstall the plugin?

**Comment by RdeWilde** [comment]
`pub global activate protoc_plugin`

**Comment by mit-mit** [comment]
Closing as assume resolved. Please reopen with more details if not.
