### ISSUE TITLE
Eliminate uses of deprecated CONSTANTS

### ISSUE THREAD

**Issue by leafpetersen** [grpc/grpc-dart#97]
This package still uses deprecated Dart 1 SCREAMING CAPS CONSTANTS. These will be removed shortly in Dart 2. This rewriting tool can be used to automatically migrate code in most cases: https://github.com/dart-lang/dart2_fix .

**Comment by leafpetersen** [comment]
Looks like one got missed here:  https://github.com/grpc/grpc-dart/blob/master/test/src/utils.dart#L30

cc @munificent

**Comment by munificent** [comment]
I'll take a look.

**Comment by leafpetersen** [comment]
Also uses of PI and JSON under examples/route_guide

**Comment by munificent** [comment]
Yep, I got 'em all.
